import { AppStateTsApi } from "../figma_app/763686";
import { mg, atom, createRemovableAtomFamily } from "../figma_app/27355";
import { setupRemovableAtomFamily } from "../figma_app/615482";
import { setupObservableAtomFamily } from "../905/508457";
setupObservableAtomFamily(() => AppStateTsApi.cmsState().bindingCollectionId);
let o = setupObservableAtomFamily(() => AppStateTsApi.cmsState().bindingFieldSchema);
let $$l2 = mg(o, e => e?.id);
let $$d4 = setupRemovableAtomFamily(() => atom(null));
let $$c7 = atom(new Set());
let $$u0 = createRemovableAtomFamily(() => atom(void 0));
let $$p1 = setupRemovableAtomFamily(() => atom(new Set()));
setupRemovableAtomFamily(() => atom(null));
let $$_8 = atom(480);
let $$h5 = atom(!1);
let $$m6 = setupRemovableAtomFamily(() => atom(null));
let $$g3 = setupRemovableAtomFamily(() => atom(null));
export const Mj = $$u0;
export const UU = $$p1;
export const dC = $$l2;
export const hl = $$g3;
export const iO = $$d4;
export const lT = $$h5;
export const lf = $$m6;
export const ou = $$c7;
export const rx = $$_8;