import { Ez5 } from "../figma_app/763686";
import { AD } from "../905/871411";
import { eU } from "../figma_app/27355";
import { vv } from "../905/508457";
let $$o1 = vv(() => Ez5?.singleSlideView().focusedNodeId, AD);
let $$l4 = vv(() => Ez5?.singleSlideView().isInFocusedNodeView, !0);
let $$d3 = eU([]);
let $$c2 = eU(null);
let $$u0 = eU(null);
export const TD = $$u0;
export const ed = $$o1;
export const hD = $$c2;
export const uY = $$d3;
export const v2 = $$l4;