import { atom } from 'jotai';
import { createConditionalObservableAtom } from '../905/508457';
import { defaultSessionLocalIDString } from '../905/871411';
import { AppStateTsApi } from '../figma_app/763686';
let $$o1 = createConditionalObservableAtom(() => AppStateTsApi?.singleSlideView().focusedNodeId, defaultSessionLocalIDString);
let $$l4 = createConditionalObservableAtom(() => AppStateTsApi?.singleSlideView().isInFocusedNodeView, !0);
let $$d3 = atom([]);
let $$c2 = atom(null);
let $$u0 = atom(null);
export const TD = $$u0;
export const ed = $$o1;
export const hD = $$c2;
export const uY = $$d3;
export const v2 = $$l4;