export var $$n3 = (e => (e.COMMUNITY = "community", e))($$n3 || {});
let $$i5 = 2e3;
let $$a1 = "DROPDOWN_TYPE_GENERIC_COMMENT_MENU";
let $$s0 = "DROPDOWN_TYPE_COMMUNITY_PROFILE_MORE_ACTIONS_MENU";
var $$o2 = (e => (e.ALL_DISABLED = "all_disabled", e.PINNED_DISABLED = "pinned_disabled", e.ENABLED = "enabled", e))($$o2 || {});
var $$l4 = (e => (e.REPORT = "report", e.REPORT_AND_HIDE = "report_and_hide", e))($$l4 || {});
export const N9 = $$s0;
export const Ng = $$a1;
export const Ni = $$o2;
export const ej = $$n3;
export const nI = $$l4;
export const wT = $$i5;