import { parsePxNumber } from "../figma_app/783094";
import { XD, vO, Mm, sF } from "../figma_app/827329";
import { Np$, K_L, pUJ, e7, hIF } from "../figma_app/27776";
import { A } from "../svg/645728";
import { A as _$$A } from "../svg/437082";
import { A as _$$A2 } from "../svg/943701";
import { A as _$$A3 } from "../svg/569339";
import { A as _$$A4 } from "../svg/381071";
let $$u0 = parsePxNumber(Np$);
let $$p20 = parsePxNumber(K_L);
let $$_19 = parsePxNumber(pUJ);
let $$h3 = parsePxNumber(e7);
let $$m8 = parsePxNumber(hIF);
let $$g27 = 112;
let $$f23 = 120;
let $$E16 = $$h3 + 2.7 * $$_19;
let $$y22 = "advanced";
let $$b14 = "shapes-sidebar";
let $$T32 = "shapes-sidebar-main-panel";
let $$I17 = "shapes-sidebar-search-token";
let $$S26 = "shapes-sidebar-search-token-close-button";
let $$v4 = "shapes-secondary-panel-back-button";
let $$A7 = "shapes-panel-close-button";
let $$x15 = "swt-collection";
let $$N29 = "connector-collection";
let $$C11 = "platform-shapes-library-section";
let $$w34 = "platform-shapes-library-card";
let $$O25 = "shapes-sidebar-empty-search-result";
let $$R21 = "recents-section";
let $$L10 = "shapes-sidebar-swt";
let $$P6 = "platform-shapes-library-item-tile";
let $$D13 = "shapes-sidebar-connector";
let $$k9 = "section-header";
let $$M30 = "library-card";
let $$F31 = "shapes-instance-swapper-item";
let $$j24 = "instance-swapper-row";
let $$U1 = "recent-diagramming-shapes-figjam";
let $$B28 = 8;
let $$G33 = "shape-with-text";
let $$V5 = ["BASIC", "DIAGRAMMING"];
let $$H18 = new Map([["BASIC", ["SQUARE", "ELLIPSE", "DIAMOND", "TRIANGLE_UP", "TRIANGLE_DOWN", "ROUNDED_RECTANGLE", "PENTAGON", "OCTAGON", "PLUS", "ARROW_LEFT", "ARROW_RIGHT", "CHEVRON", "STAR", "SPEECH_BUBBLE"]], ["DIAGRAMMING", ["PARALLELOGRAM_RIGHT", "PARALLELOGRAM_LEFT", "ENG_DATABASE", "ENG_QUEUE", "ENG_FILE", "ENG_FOLDER", "DOCUMENT_SINGLE", "DOCUMENT_MULTIPLE", "PREDEFINED_PROCESS", "SHIELD", "TRAPEZOID", "MANUAL_INPUT", "HEXAGON", "INTERNAL_STORAGE", "OR", "SUMMING_JUNCTION"]]]);
let $$z12 = new Map([["ELBOWED", _$$A], ["STRAIGHT", _$$A3], ["CURVED", A], ["STRAIGHT_NO_ENDPOINTS", _$$A2], ["MINDMAP_TREE_NUCLEUS", _$$A4]]);
let $$W2 = new Map([["ELBOWED", XD], ["STRAIGHT", vO], ["CURVED", Mm], ["STRAIGHT_NO_ENDPOINTS", sF]]);
export const $s = $$u0;
export const Ec = $$U1;
export const F_ = $$W2;
export const GN = $$h3;
export const Jg = $$v4;
export const KQ = $$V5;
export const Kv = $$P6;
export const NQ = $$A7;
export const OS = $$m8;
export const Pr = $$k9;
export const QA = $$L10;
export const UC = $$C11;
export const X5 = $$z12;
export const Xi = $$D13;
export const YV = $$b14;
export const Yu = $$x15;
export const Zu = $$E16;
export const _U = $$I17;
export const aq = $$H18;
export const d5 = $$_19;
export const du = $$p20;
export const eu = $$R21;
export const iJ = $$y22;
export const kv = $$f23;
export const lK = $$j24;
export const lO = $$O25;
export const m3 = $$S26;
export const pD = $$g27;
export const qA = $$B28;
export const qD = $$N29;
export const uI = $$M30;
export const uO = $$F31;
export const w4 = $$T32;
export const yR = $$G33;
export const zk = $$w34;