var $$n0 = (e => (e.TOP_RIGHT = "top-right", e.CENTER = "center", e.BOTTOM_LEFT = "bottom-left", e.BOTTOM_RIGHT = "bottom-right", e))($$n0 || {});
var $$i3 = (e => (e.LEFT_TITLE = "left_title", e.RIGHT_TITLE = "right_title", e))($$i3 || {});
var a = (e => (e[e.TOP = 0] = "TOP", e[e.BOTTOM = 1] = "BOTTOM", e[e.RIGHT_TITLE = 2] = "RIGHT_TITLE", e[e.RIGHT_BODY = 3] = "RIGHT_BODY", e[e.LEFT_TITLE = 4] = "LEFT_TITLE", e[e.TOP_RIGHT = 5] = "TOP_RIGHT", e))(a || {});
var s = (e => (e.FALLBACK = "fallback", e.BEST_EFFORT = "best_effort", e))(s || {});
var $$o4 = (e => (e.DRAGGABLE = "draggable", e.FEATURE_UPDATE = "feature_update", e.WELCOME = "welcome", e.SELF_CONTAINED = "self_contained", e.WALK_THROUGH = "walk_through", e.ANNOUNCEMENT_POINTER = "announcement_pointer", e.POINTER = "pointer", e))($$o4 || {});
export let $$l2 = 740;
export var $$d1 = (e => (e.ON_DARK = "on_dark", e.ON_LIGHT = "on_light", e.HIGH_CONTRAST = "high_contrast", e.HIDDEN = "hidden", e))($$d1 || {});
export const LN = $$n0;
export const M_ = $$d1;
export const No = $$l2;
export const _L = $$i3;
export const q3 = $$o4;