import { z7E } from "../figma_app/763686";
import { eU } from "../figma_app/27355";
import { h0, zu, JJ } from "../figma_app/61403";
let $$s4 = 2e3;
let $$o6 = 2e3;
let $$l10 = eU($$s4);
let $$d5 = eU($$o6);
let $$c12 = eU("");
let $$u2 = eU(0);
let $$p11 = eU(!1);
let $$_1 = eU(null);
let $$h7 = eU(h0.AWAITING_PLAYBACK);
let $$m8 = eU(z7E.DEFAULT);
let $$g3 = eU(zu.DEFAULT);
let $$f13 = eU(void 0);
let $$E0 = eU(JJ.CANVAS);
let $$y9 = eU(0);
export const $i = $$E0;
export const Dh = $$_1;
export const Ds = $$u2;
export const H7 = $$g3;
export const Lw = $$s4;
export const Sf = $$d5;
export const WW = $$o6;
export const a8 = $$h7;
export const iB = $$m8;
export const jE = $$y9;
export const jr = $$l10;
export const mH = $$p11;
export const nG = $$c12;
export const oO = $$f13;