import { atom } from 'jotai';
import { setupRemovableAtomFamily } from '../figma_app/615482';
let $$a12 = setupRemovableAtomFamily(() => atom(null));
let $$s0 = setupRemovableAtomFamily(() => atom(null));
let $$o3 = setupRemovableAtomFamily(() => atom([]));
let $$l7 = setupRemovableAtomFamily(() => atom(null));
let $$d11 = setupRemovableAtomFamily(() => atom(null));
let $$c2 = setupRemovableAtomFamily(() => atom(null));
let $$u13 = setupRemovableAtomFamily(() => atom(null));
let $$p4 = setupRemovableAtomFamily(() => atom(null));
let $$_8 = setupRemovableAtomFamily(() => atom(null));
let $$h9 = setupRemovableAtomFamily(() => atom(null));
let $$m5 = setupRemovableAtomFamily(() => atom(null));
let $$g6 = setupRemovableAtomFamily(() => atom(null));
let $$f10 = setupRemovableAtomFamily(() => atom(void 0));
let $$E1 = setupRemovableAtomFamily(() => atom('initial'));
export const Av = $$s0;
export const I = $$E1;
export const KV = $$c2;
export const L2 = $$o3;
export const Op = $$p4;
export const ZM = $$m5;
export const az = $$g6;
export const eF = $$l7;
export const iS = $$_8;
export const ky = $$h9;
export const rJ = $$f10;
export const rT = $$d11;
export const yd = $$a12;
export const zZ = $$u13;