import { V5 } from "src/figma_app/847597";
import { nf } from "src/figma_app/847597";
import { Qi as _$$Qi } from "src/figma_app/847597";
import { mb as _$$mb } from "src/figma_app/847597";
import { tI as _$$tI } from "src/figma_app/847597";
import { JT as _$$JT } from "src/figma_app/847597";
import { Tm as _$$Tm } from "src/figma_app/847597";
import { NU as _$$NU } from "src/figma_app/847597";
import { kj as _$$kj } from "src/figma_app/847597";
import { SI as _$$SI } from "src/figma_app/847597";
import { CM as _$$CM } from "src/figma_app/847597";
import { r3 as _$$r } from "src/figma_app/847597";
let $$n8 = _$$r;
let $$i0 = _$$CM;
let $$a4 = _$$SI;
let $$s6 = _$$kj;
let $$o2 = _$$NU;
let $$l5 = _$$Tm;
let $$d1 = _$$JT;
nf;
V5;
let $$c9 = _$$tI;
let $$u7 = _$$mb;
let $$p3 = _$$Qi;
export const CM = $$i0;
export const JT = $$d1;
export const NU = $$o2;
export const Qi = $$p3;
export const SI = $$a4;
export const Tm = $$l5;
export const kj = $$s6;
export const mb = $$u7;
export const r3 = $$n8;
export const tI = $$c9;
