var $$n2 = (e => (e.SET_CHAT = "setChat", e.CLEAR_CHAT = "clearChat", e.TARGET_DOM_NODE = "targetDOMNode", e.TARGET_SCENE_NODE = "targetSceneNode", e.INSERT_NODE = "insertNode", e.ADJUST_ZOOM_LEVEL = "adjustZoomLevel", e.MOVE_CURSOR_TO_CENTER_SCREEN = "moveCursorToCenterScreen", e.CHANGE_TOOL = "changeTool", e.MOVE_VIEWPORT = "moveViewport", e.SET_CURSOR_DIRECTION = "setCursorDirection", e.SET_PROPERTIES_PANEL_TAB = "setPropertiesPanelTab", e.UPDATE_SELECTED_NODE_PROPERTIES = "updateSelectedNodeProperties", e.SCROLL_PROPERTIES_PANEL = "scrollPropertiesPanel", e.FOCUS_INPUT = "focusInput", e.SELECT_SCENE_NODE = "selectSceneNode", e.SET_VIEWPORT_FRAME_TYPE = "setViewportFrameType", e))($$n2 || {});
var $$i3 = (e => (e.CANVAS = "canvas", e.PROPERTIES_PANEL = "properties-panel", e.TEXT_PANEL = "text-panel", e))($$i3 || {});
var $$a10 = (e => (e.DEFAULT = "left", e.RIGHT = "right", e))($$a10 || {});
var $$s6 = (e => (e[e.DEFAULT = 0] = "DEFAULT", e[e.INSIDE_SCENE_NODE = 1] = "INSIDE_SCENE_NODE", e[e.CANVAS_COORDINATE = 2] = "CANVAS_COORDINATE", e))($$s6 || {});
var $$o0 = (e => (e[e.TOP_LEFT = 0] = "TOP_LEFT", e[e.BOTTOM_LEFT = 1] = "BOTTOM_LEFT", e[e.BOTTOM_RIGHT = 2] = "BOTTOM_RIGHT", e))($$o0 || {});
var $$l9 = (e => (e.CREATE_FRAME = "How to draw a frame", e.FORMAT_FRAME = "How to use the design panel", e.CREATE_TEXT = "Add words where needed", e.FORMAT_TEXT = "How to format text", e))($$l9 || {});
var $$d7 = (e => (e.PLAYING = "playing", e.AWAITING_PLAYBACK = "awaitingPlayback", e))($$d7 || {});
var $$c1 = (e => (e.LEFT = "left", e.CENTER = "center", e.RIGHT = "right", e))($$c1 || {});
var $$u5 = (e => (e.TOP = "top", e.CENTER = "center", e.BOTTOM = "bottom", e))($$u5 || {});
var $$p4 = (e => (e.TEST = "test", e.PRODUCT_FRAME = "productFrame", e.PRODUCT_FRAME_CHERRIES_FRAME = "productFrameCherriesFrame", e.PRODUCT_FRAME_TOMATO_FRAME = "productFrameTomatoFrame", e.CHERRIES_FRAME_CHERRIES_IMAGE = "cherriesFrameCherriesImage", e.CHERRIES_FRAME_CHERRIES_TEXT = "cherriesFrameCherriesText", e.CHERRIES_FRAME_PRICE_TEXT = "cherriesFramePriceText", e.CHERRIES_FRAME_GROWN_TEXT = "cherriesFrameGrownText", e.NO_BASICS_FILE_FRAME = "noBasicsFileFrame", e.NO_BASICS_FILE_TEXT = "noBasicsFileText", e))($$p4 || {});
var $$_8 = (e => (e.ESC_KEY = "esc key", e.STOP_BTN = "stop button", e.NEXT_BTN = "next tutorial button", e.PREV_BTN = "previous tutorial button", e.STATE_MANAGER_ERROR = "state manager error", e))($$_8 || {});
export const $2 = $$o0;
export const GF = $$c1;
export const HQ = $$n2;
export const JJ = $$i3;
export const Le = $$p4;
export const NI = $$u5;
export const bn = $$s6;
export const h0 = $$d7;
export const mf = $$_8;
export const wn = $$l9;
export const zu = $$a10;