let $$n6 = "components";
let $$i10 = "examples";
let $$a1 = "templates";
let $$s2 = "assets";
let $$o11 = "privateToThisFile";
var $$l3 = (e => (e[e.HEADER = 0] = "HEADER", e[e.SUGGESTIONS = 1] = "SUGGESTIONS", e[e.BREADCRUMB = 2] = "BREADCRUMB", e[e.CONTENTS = 3] = "CONTENTS", e))($$l3 || {});
var $$d8 = (e => (e[e.LIBRARIES = 0] = "LIBRARIES", e[e.PAGES = 1] = "PAGES", e[e.ASSETS = 2] = "ASSETS", e))($$d8 || {});
var $$c9 = (e => (e[e.SEARCH_AND_FILTER = 0] = "SEARCH_AND_FILTER", e[e.LIBRARY_SEARCH_CHIP = 1] = "LIBRARY_SEARCH_CHIP", e))($$c9 || {});
var $$u4 = (e => (e[e.SEARCH = 0] = "SEARCH", e[e.VISUAL_SEARCH_BUTTON = 1] = "VISUAL_SEARCH_BUTTON", e[e.SETTINGS = 2] = "SETTINGS", e))($$u4 || {});
var $$p5 = (e => (e[e.BACK = 0] = "BACK", e[e.LIBRARY = 1] = "LIBRARY", e[e.ELLIPSIS = 2] = "ELLIPSIS", e[e.STUBS = 3] = "STUBS", e))($$p5 || {});
var $$_12 = (e => (e[e.SITE_KIT = 0] = "SITE_KIT", e[e.TEMPLATES = 1] = "TEMPLATES", e[e.EXAMPLES = 2] = "EXAMPLES", e[e.COMPONENTS = 3] = "COMPONENTS", e[e.FOLDERS = 4] = "FOLDERS", e))($$_12 || {});
var $$h7 = (e => (e[e.SITE_KIT = 0] = "SITE_KIT", e[e.LOCAL_AND_SUBSCRIBED = 1] = "LOCAL_AND_SUBSCRIBED", e[e.PRESETS = 2] = "PRESETS", e[e.VISUAL_ASSETS = 3] = "VISUAL_ASSETS", e))($$h7 || {});
var m = (e => (e[e.LIBRARIES = 0] = "LIBRARIES", e))(m || {});
var $$g14 = (e => (e[e.CTA = 0] = "CTA", e[e.UI_KITS = 1] = "UI_KITS", e))($$g14 || {});
var $$f13 = (e => (e.DESIGN = "design", e.SITE = "site", e))($$f13 || {});
export function $$E0(e) {
  return void 0 !== e.embeds;
}
export const AZ = $$E0;
export const JS = $$a1;
export const Mk = $$s2;
export const ON = $$l3;
export const Wy = $$u4;
export const Yv = $$p5;
export const c_ = $$n6;
export const gP = $$h7;
export const lM = $$d8;
export const my = $$c9;
export const nE = $$i10;
export const o8 = $$o11;
export const tM = $$_12;
export const yW = $$f13;
export const zr = $$g14;