import { oo, Vk, dX, NU, Ye, Z1, NY, UY } from "../905/75000";
import { FE, Ii, j3, rB, WG, wn, _j, hM } from "../905/581923";
import { yu, Se } from "../905/926939";
import { wP, Cb, Sn } from "../905/327738";
import { A } from "../905/970762";
import { Y, R } from "../905/872568";
export const BOOLEAN_TYPE_REPR = oo;
export const COMPONENT_PREFIX = FE;
export const CUSTOM_IMAGE_TYPE_STR = Vk;
export const IMAGE_NAME_FORMAT = Ii;
export const IMAGE_TYPE_REPR = dX;
export const STRING_TYPE_REPR = NU;
export const cleanComponentPropNameForUsage = j3;
export const extractModifiersFromProp = rB;
export const filterComponentProps = A;
export const getComponentInfoById = Ye;
export const getComponentInfoByIdUncached = Z1;
export const getComponentJSXName = WG;
export const getInstanceIdsForDef = wn;
export const getInstanceNodeProps = Y;
export const getNestedImageNodes = _j;
export const getNodeParentPath = yu;
export const getTypeInfoCached = NY;
export const groupByCommonPrefixSorted = hM;
export const isPartOfGroup = Se;
export const moveNumbersToEnd = wP;
export const resetTypeInfoCache = UY;
export const toCamelCase = Cb;
export const toTitleCase = Sn;
export const usagePropsToRawProps = R;