import { eU, E3 } from "../figma_app/27355";
import { Wh } from "../figma_app/615482";
let $$a3 = Wh(() => eU({}));
let $$s2 = eU({});
let $$o5 = eU(!1);
let $$l4 = E3("codeDrawerTab", "console");
let $$d8 = E3("codeDrawerHeight", 300);
let $$c0 = Wh(() => eU(""));
let $$u6 = Wh(() => eU(null));
let $$p1 = Wh(() => eU(null));
let $$_7 = Wh(() => eU(0));
export const Cb = $$c0;
export const JL = $$p1;
export const KL = $$s2;
export const TJ = $$a3;
export const Vo = $$l4;
export const YD = $$o5;
export const f3 = $$u6;
export const kb = $$_7;
export const rO = $$d8;