import { atom, createLocalStorageAtom } from "../figma_app/27355";
import { setupRemovableAtomFamily } from "../figma_app/615482";
let $$a3 = setupRemovableAtomFamily(() => atom({}));
let $$s2 = atom({});
let $$o5 = atom(!1);
let $$l4 = createLocalStorageAtom("codeDrawerTab", "console");
let $$d8 = createLocalStorageAtom("codeDrawerHeight", 300);
let $$c0 = setupRemovableAtomFamily(() => atom(""));
let $$u6 = setupRemovableAtomFamily(() => atom(null));
let $$p1 = setupRemovableAtomFamily(() => atom(null));
let $$_7 = setupRemovableAtomFamily(() => atom(0));
export const Cb = $$c0;
export const JL = $$p1;
export const KL = $$s2;
export const TJ = $$a3;
export const Vo = $$l4;
export const YD = $$o5;
export const f3 = $$u6;
export const kb = $$_7;
export const rO = $$d8;