import { then } from "../1a115cee/810755";
import { then as _$$then } from "../1a115cee/110138";
import { then as _$$then2 } from "../1a115cee/110138";
import { createModalConfig, registerModal } from "../905/102752";
import { A } from "../905/560427";
let a = A.createLazyComponent(() => _$$then2(e => e.AutosaveLogOutModal), createModalConfig("AutosaveLogOutModal"));
let $$s2 = registerModal(a);
let o = A.createLazyComponent(() => _$$then(e => e.HasAutosaveChangesModal), createModalConfig("HasAutosaveChangesModal"));
let $$l0 = registerModal(o);
let d = A.createLazyComponent(() => then(e => e.AutosaveLearnMoreModal), createModalConfig("AutosaveLearnMoreModal"));
let $$c1 = registerModal(d);
export const EO = $$l0;
export const wZ = $$c1;
export const xv = $$s2;