import { NC } from "../905/17179";
let $$i5 = NC("CANVAS_SEARCH_SET_MODE");
let $$a2 = NC("CANVAS_SEARCH_SET_SCOPE");
let $$s4 = NC("CANVAS_SEARCH_CLEAR_CATEGORY_FILTERS");
let $$o6 = NC("CANVAS_SEARCH_SWITCH_CATEGORY_FILTER_EXCLUSIVE");
let $$l0 = NC("CANVAS_SEARCH_TOGGLE_CATEGORY_FILTER");
let $$d1 = NC("CANVAS_SEARCH_SET_QUERY");
let $$c3 = NC("CANVAS_SEARCH_RESET");
export const DI = $$l0;
export const NY = $$d1;
export const V2 = $$a2;
export const cL = $$c3;
export const dY = $$s4;
export const sV = $$i5;
export const zx = $$o6;