import { eU } from "../figma_app/27355";
import { Wh } from "../figma_app/615482";
var $$a7 = (e => (e.LOADING = "loading", e.AUTH = "auth", e.CREATE_PROJECT = "create_project", e.CONNECT_TO_EXISTING_PROJECTS = "connect_to_existing_projects", e.CONNECTED_PROJECT = "connected_project", e.CONNECTING_TO_PROJECT = "connecting_to_project", e))($$a7 || {});
let $$s4 = Wh(() => eU(null));
let $$o3 = Wh(() => eU("loading"));
let $$l2 = Wh(() => eU(!1));
let $$d0 = Wh(() => eU(!1));
export var $$c1 = (e => (e.INIT = "init", e.DEPLOYING = "deploying", e))($$c1 || {});
let $$u5 = Wh(() => eU("init"));
let $$p6 = Wh(() => eU(!0));
export const GV = $$d0;
export const Ut = $$c1;
export const Xl = $$l2;
export const hR = $$o3;
export const kz = $$s4;
export const p7 = $$u5;
export const rK = $$p6;
export const s8 = $$a7;