import { eU } from "../figma_app/27355";
import { fD } from "../figma_app/816671";
var $$a2 = (e => (e.NOT_STARTED = "NOT_STARTED", e.MODAL_SHOWING = "MODAL_SHOWING", e.USE_CASE_STEPS = "USE_CASE_STEPS", e.COMPLETED = "COMPLETED", e))($$a2 || {});
let $$s3 = eU("NOT_STARTED");
let $$o1 = eU(fD.NONE);
let $$l0 = eU(!1);
export const aG = $$l0;
export const l5 = $$o1;
export const tX = $$a2;
export const w = $$s3;