export var $$n12 = (e => (e.VIEWER = 'viewer', e.EDITOR = 'editor', e))($$n12 || {})
let $$i8 = 'Quick Actions Search'
let $$a11 = 'open-quick-actions'
let $$s5 = 'Quick Actions Search Query Result'
let $$o9 = 'search-quick-actions'
export var $$l10 = (e => (e.EXTENSION = 'extension', e.ACTION = 'action', e))($$l10 || {})
let $$d4 = 'Quick Actions Action'
let $$c1 = 'Quick Actions Panel Button'
let $$u6 = 'Quick Actions Suggestion Toast Shown'
let $$p7 = 'quick_actions_v1'
let $$_0 = 'quick_actions_v2'
let $$h3 = 'frecency'
let $$m2 = 'string-match'
let $$g14 = 'extensions'
let $$f13 = 'assets'
export const $L = $$_0
export const Be = $$c1
export const NP = $$m2
export const Nv = $$h3
export const OW = $$d4
export const RA = $$s5
export const Sq = $$u6
export const U3 = $$p7
export const W3 = $$i8
export const gc = $$o9
export const l4 = $$l10
export const mP = $$a11
export const qE = $$n12
export const tq = $$f13
export const uP = $$g14
