export let $$n3 = "copy selection nudge to lint";
var $$i2 = (e => (e.UNINITIALIZED = "UNINITIALIZED", e.INITIALIZED = "INITIALIZED", e.IDLE = "IDLE", e.DETECTION_REQUESTED = "DETECTION_REQUESTED", e.DETECTING = "DETECTING", e.GROUPING_PENDING = "GROUPING_PENDING", e.GROUPING_COMPLETE = "GROUPING_COMPLETE", e.RESPONDING_TO_CANVAS_CHANGE = "RESPONDING_TO_CANVAS_CHANGE", e))($$i2 || {});
var $$a0 = (e => (e.LANDING_PAGE_WELCOME = "LANDING_PAGE_WELCOME", e.LANDING_PAGE_NO_SELECTION = "LANDING_PAGE_NO_SELECTION", e.LANDING_PAGE_LIMIT_EXCEEDED = "LANDING_PAGE_LIMIT_EXCEEDED", e.LIBRARY_SELECTOR_INITIAL = "LIBRARY_SELECTOR_INITIAL", e.LIBRARY_SELECTOR_FROM_ALL_GROUPS_VIEW = "LIBRARY_SELECTOR_FROM_ALL_GROUPS_VIEW", e.LIBRARY_SELECTOR_FROM_SELECTED_GROUP_VIEW = "LIBRARY_SELECTOR_FROM_SELECTED_GROUP_VIEW", e.ALL_VISUAL_GROUPS_VIEW = "ALL_VISUAL_GROUPS_VIEW", e.SELECTED_VISUAL_GROUP_VIEW = "SELECTED_VISUAL_GROUP_VIEW", e))($$a0 || {});
var $$s1 = (e => (e.LOADING = "LOADING", e.EMPTY = "EMPTY", e.CONTENT = "CONTENT", e.ERROR = "ERROR", e))($$s1 || {});
export const FR = $$a0;
export const oV = $$s1;
export const td = $$i2;
export const xp = $$n3;