var $$n1 = (e => (e.ADMIN = "admin", e.DIRECTORY = "directory", e))($$n1 || {});
var $$i3 = (e => (e.TEAMS = "teams", e))($$i3 || {});
export let $$a0 = ["teams"];
export var $$s4 = (e => (e.TEAMS = "teams", e.MEMBERS = "members", e.LIBRARIES = "libraries", e.SETTINGS = "settings", e))($$s4 || {});
let $$o5 = ["members", "teams", "libraries", "settings"];
let $$l2 = $$o5[0];
export const Fi = $$a0;
export const V0 = $$n1;
export const _C = $$l2;
export const dN = $$i3;
export const m2 = $$s4;
export const rj = $$o5;