import { atom } from "src/figma_app/27355";
import { createReduxSubscriptionAtomWithState } from "src/905/270322";
let $$a4 = createReduxSubscriptionAtomWithState(e => e.user);
let $$s2 = atom(e => e($$a4)?.id);
let $$o3 = atom(e => e($$a4)?.created_at);
let $$l1 = createReduxSubscriptionAtomWithState(e => e.userStateLoaded);
let $$d0 = createReduxSubscriptionAtomWithState(e => e.isStarterUser);
export const UQ = $$d0;
export const VF = $$l1;
export const kS = $$s2;
export const mp = $$o3;
export const p9 = $$a4;
