export function $$n2(e) {
  return !!e && void 0 !== e.query;
}
var $$i1 = (e => (e.accessibility = "accessibility", e.bannerTemplates = "banner-templates", e.brainstorming = "brainstorming", e.cardTemplates = "card-templates", e.classroomActivities = "classroom-activities", e.dataTemplates = "data-templates", e.designInspirations = "design-inspirations", e.designTemplates = "design-templates", e.designTools = "design-tools", e.designTutorials = "design-tutorials", e.desktopAppsWebsites = "website-templates", e.development = "development", e.deviceMockups = "device-mockups", e.diagramming = "diagramming", e.editingEffects = "editing-effects", e.education = "education", e.facebookTemplates = "facebook-templates", e.fileOrganization = "file-organization", e.fontsTypography = "fonts-typography", e.funGames = "fun-games", e.flyerTemplates = "flyer-templates", e.icons = "icons", e.illustrations = "illustrations", e.importExport = "import-export", e.instagramTemplates = "instagram-templates", e.invitationTemplates = "invitation-templates", e.lessonPlans = "lesson-plans", e.libraries = "libraries", e.linkedinTemplates = "linkedin-templates", e.make = "make", e.mobileApps = "mobile-apps", e.nameTagTemplates = "name-tag-templates", e.onePagerTemplates = "one-pager-templates", e.invoiceTemplates = "invoice-templates", e.letterheadTemplates = "letterhead-templates", e.portfolios = "portfolio-templates", e.printableTemplates = "printable-templates", e.calendarTemplates = "calendar-templates", e.posterTemplates = "poster-templates", e.presentations = "presentations", e.prototypingAnimation = "prototyping-animation", e.resumes = "resume-templates", e.shapesColors = "shapes-colors", e.socialMediaTemplates = "social-media-templates", e.stockPhotography = "stock-photography", e.strategicPlanning = "strategic-planning", e.teamMeetings = "team-meetings", e.tiktokTemplates = "tiktok-templates", e.tutorials = "design-tutorials", e.uiKits = "ui-kits", e.visualAssets = "visual-assets", e.webAds = "web-ads", e.websiteTemplates = "website-templates", e.whiteboarding = "whiteboarding", e.wireframes = "wireframes", e.workshopTemplates = "workshop-templates", e.xTwitterTemplates = "x-twitter-templates", e.youtubeTemplates = "youtube-templates", e.zoomBackgroundTemplates = "zoom-background-templates", e))($$i1 || {});
var $$a0 = (e => (e.blogWebsites = "blog", e.businessWebsites = "business", e.landingPageTemplates = "landing-pages", e.portfolioWebsiteTemplates = "portfolio", e.photographyWebsites = "photography", e.weddingWebsites = "wedding", e.interiorDesignWebsites = "interior-design", e))($$a0 || {});
var $$s3 = (e => (e.LANDING = "landing", e.NAV = "nav", e))($$s3 || {});
let $$o5 = {
  "es-es": {
    accesibilidad: "accessibility",
    "actividades-del-aula": "classroom-activities",
    "animacion-prototipo": "prototyping-animation",
    "anuncios-web": "web-ads",
    "aplicaciones-moviles": "mobile-apps",
    bibliotecas: "libraries",
    brainstorming: "brainstorming",
    "creacion-de-diagramas": "diagramming",
    desarrollo: "development",
    educacion: "education",
    "efectos-edicion": "editing-effects",
    "formas-colores": "shapes-colors",
    "fotografia-de-archivo": "stock-photography",
    "fuentes-tipografia": "fonts-typography",
    "herramientas-de-diseno": "design-tools",
    iconos: "icons",
    ilustraciones: "illustrations",
    "importar-exportar": "import-export",
    "inspiraciones-de-diseno": "design-inspirations",
    "juegos-divertidos": "fun-games",
    make: "make",
    "maquetas-dispositivos": "device-mockups",
    "organizacion-de-archivos": "file-organization",
    "planes-de-leccion": "lesson-plans",
    "planificacion-estrategica": "strategic-planning",
    "plantillas-calendario": "calendar-templates",
    "plantillas-curriculum": "resume-templates",
    "plantillas-datos": "data-templates",
    "plantillas-de-banners": "banner-templates",
    "plantillas-de-carteles": "poster-templates",
    "plantillas-de-diseno": "design-templates",
    "plantillas-de-facebook": "facebook-templates",
    "plantillas-de-fondo-de-zoom": "zoom-background-templates",
    "plantillas-de-linkedin": "linkedin-templates",
    "plantillas-de-membretes": "letterhead-templates",
    "plantillas-de-portafolios": "portfolio-templates",
    "plantillas-de-redes-sociales": "social-media-templates",
    "plantillas-de-sitios-web": "website-templates",
    "plantillas-de-taller": "workshop-templates",
    "plantillas-de-tarjetas": "card-templates",
    "plantillas-de-tiktok": "tiktok-templates",
    "plantillas-de-una-sola-pagina": "one-pager-templates",
    "plantillas-de-x-twitter": "x-twitter-templates",
    "plantillas-de-youtube": "youtube-templates",
    "plantillas-etiquetas-identificativas": "name-tag-templates",
    "plantillas-facturas": "invoice-templates",
    "plantillas-instagram": "instagram-templates",
    "plantillas-invitacion": "invitation-templates",
    "plantillas-para-imprimir": "printable-templates",
    "plantillas-volantes": "flyer-templates",
    presentaciones: "presentations",
    "recursos-visuales": "visual-assets",
    reticulas: "wireframes",
    "reuniones-de-equipo": "team-meetings",
    "tutoriales-diseno": "design-tutorials",
    "ui-kits": "ui-kits",
    "uso-de-las-pizarras": "whiteboarding"
  },
  "es-la": {
    accesibilidad: "accessibility",
    "actividades-para-el-aula": "classroom-activities",
    "animacion-de-prototipo": "prototyping-animation",
    "anuncios-web": "web-ads",
    "aplicaciones-moviles": "mobile-apps",
    bibliotecas: "libraries",
    desarrollo: "development",
    diagramacion: "diagramming",
    educacion: "education",
    "efectos-de-edicion": "editing-effects",
    "formas-y-colores": "shapes-colors",
    "fotografia-de-archivo": "stock-photography",
    "fuentes-tipografia": "fonts-typography",
    "herramientas-de-diseno": "design-tools",
    iconos: "icons",
    ilustraciones: "illustrations",
    "importar-exportar": "import-export",
    "inspiraciones-de-diseno": "design-inspirations",
    "juegos-diversion": "fun-games",
    "lluvia-de-ideas": "brainstorming",
    make: "make",
    "maquetas-de-dispositivos": "device-mockups",
    "organizacion-de-archivos": "file-organization",
    pizarra: "whiteboarding",
    "planes-de-lecciones": "lesson-plans",
    "planificacion-estrategica": "strategic-planning",
    "plantillas-de-banners": "banner-templates",
    "plantillas-de-calendario": "calendar-templates",
    "plantillas-de-carteles": "poster-templates",
    "plantillas-de-curriculum": "resume-templates",
    "plantillas-de-datos": "data-templates",
    "plantillas-de-diseno": "design-templates",
    "plantillas-de-etiquetas-de-nombre": "name-tag-templates",
    "plantillas-de-facebook": "facebook-templates",
    "plantillas-de-facturas": "invoice-templates",
    "plantillas-de-fondo-de-zoom": "zoom-background-templates",
    "plantillas-de-instagram": "instagram-templates",
    "plantillas-de-invitacion": "invitation-templates",
    "plantillas-de-linkedin": "linkedin-templates",
    "plantillas-de-membrete": "letterhead-templates",
    "plantillas-de-portafolio": "portfolio-templates",
    "plantillas-de-redes-sociales": "social-media-templates",
    "plantillas-de-sitios-web": "website-templates",
    "plantillas-de-taller": "workshop-templates",
    "plantillas-de-tarjetas": "card-templates",
    "plantillas-de-tiktok": "tiktok-templates",
    "plantillas-de-una-pagina": "one-pager-templates",
    "plantillas-de-volantes": "flyer-templates",
    "plantillas-de-x-twitter": "x-twitter-templates",
    "plantillas-de-youtube": "youtube-templates",
    "plantillas-imprimibles": "printable-templates",
    presentaciones: "presentations",
    "recursos-visuales": "visual-assets",
    "reuniones-de-equipo": "team-meetings",
    "tutoriales-de-diseno": "design-tutorials",
    "ui-kit": "ui-kits",
    wireframes: "wireframes"
  },
  "pt-br": {
    acessibilidade: "accessibility",
    "anuncios-online": "web-ads",
    "aplicativos-moveis": "mobile-apps",
    apresentacoes: "presentations",
    "atividades-sala-de-aula": "classroom-activities",
    bibliotecas: "libraries",
    brainstorming: "brainstorming",
    desenvolvimento: "development",
    diagramas: "diagramming",
    "edicao-efeitos": "editing-effects",
    educacao: "education",
    "ferramentas-design": "design-tools",
    "fontes-tipografia": "fonts-typography",
    "formas-cores": "shapes-colors",
    "fotografia-banco-de-imagens": "stock-photography",
    icones: "icons",
    ilustracoes: "illustrations",
    "importar-exportar": "import-export",
    "inspiracao-design": "design-inspirations",
    "jogos-divertidos": "fun-games",
    make: "make",
    "mockups-dispositivo": "device-mockups",
    "modelos-banners": "banner-templates",
    "modelos-calendario": "calendar-templates",
    "modelos-cartazes": "poster-templates",
    "modelos-cartoes": "card-templates",
    "modelos-convites": "invitation-templates",
    "modelos-crachas": "name-tag-templates",
    "modelos-curriculo": "resume-templates",
    "modelos-dados": "data-templates",
    "modelos-design": "design-templates",
    "modelos-documentos-uma-pagina": "one-pager-templates",
    "modelos-facebook": "facebook-templates",
    "modelos-fatura": "invoice-templates",
    "modelos-folhetos": "flyer-templates",
    "modelos-imprimiveis": "printable-templates",
    "modelos-instagram": "instagram-templates",
    "modelos-linkedin": "linkedin-templates",
    "modelos-papel-timbrado": "letterhead-templates",
    "modelos-plano-de-fundo-zoom": "zoom-background-templates",
    "modelos-portfolio": "portfolio-templates",
    "modelos-redes-sociais": "social-media-templates",
    "modelos-site": "website-templates",
    "modelos-tiktok": "tiktok-templates",
    "modelos-workshops": "workshop-templates",
    "modelos-x-twitter": "x-twitter-templates",
    "modelos-youtube": "youtube-templates",
    "organizacao-arquivos": "file-organization",
    "planejamento-estrategico": "strategic-planning",
    "planos-de-aula": "lesson-plans",
    "prototipagem-animacao": "prototyping-animation",
    "quadro-branco": "whiteboarding",
    "recursos-visuais": "visual-assets",
    "reunioes-equipe": "team-meetings",
    "tutoriais-design": "design-tutorials",
    "ui-kits": "ui-kits",
    wireframes: "wireframes"
  }
};
let l = Object.entries($$o5).reduce((e, [t, r]) => (e[t] = Object.entries(r).reduce((e, [t, r]) => (e[r] = t, e), {}), e), {});
export function $$d6(e, t) {
  let r = $$o5[t];
  if (r) return r[e];
}
export function $$c4(e, t) {
  let r = l[t];
  if (r) return r[e];
}
export const HP = $$a0;
export const LJ = $$i1;
export const OE = $$n2;
export const PF = $$s3;
export const Tr = $$c4;
export const gT = $$o5;
export const zU = $$d6;