var $$n10 = (e => (e[e.V3 = 3] = "V3", e[e.V4 = 4] = "V4", e[e.MIN = 3] = "MIN", e[e.MAX = 4] = "MAX", e))($$n10 || {});
var $$i12 = (e => (e.Whiteboard = "whiteboard", e))($$i12 || {});
var $$a3 = (e => (e[e.V5 = 5] = "V5", e[e.V6 = 6] = "V6", e[e.MIN = 5] = "MIN", e[e.MAX = 6] = "MAX", e))($$a3 || {});
var $$s9 = (e => (e[e.$$default = 0] = "default", e[e.last = 1] = "last", e))($$s9 || {});
var $$o2 = (e => (e[e.none = 0] = "none", e[e.leading = 1] = "leading", e[e.trailing = 2] = "trailing", e[e.both = 3] = "both", e))($$o2 || {});
var $$l6 = (e => (e[e.horizontal = 0] = "horizontal", e[e.vertical = 1] = "vertical", e))($$l6 || {});
var $$d1 = (e => (e[e.horizontal = 0] = "horizontal", e[e.vertical = 1] = "vertical", e))($$d1 || {});
var $$c13 = (e => (e[e.utility = 0] = "utility", e[e.drawing = 1] = "drawing", e))($$c13 || {});
var $$u0 = (e => (e[e.automatic = 0] = "automatic", e[e.persistent = 1] = "persistent", e))($$u0 || {});
var $$p8 = (e => (e.enterCropMode = "enterCropMode", e.exitCropMode = "exitCropMode", e))($$p8 || {});
var $$_4 = (e => (e[e.gradient = 0] = "gradient", e[e.base = 1] = "base", e))($$_4 || {});
var $$h11 = (e => (e[e.hoveringAboveBar = 0] = "hoveringAboveBar", e[e.sideEdge = 1] = "sideEdge", e[e.secondarySideEdge = 2] = "secondarySideEdge", e[e.pinnedToFloatingBar = 3] = "pinnedToFloatingBar", e))($$h11 || {});
var $$m14 = (e => (e[e.presetColor = 0] = "presetColor", e[e.presetImage = 1] = "presetImage", e[e.colorPicker = 2] = "colorPicker", e[e.imagePicker = 3] = "imagePicker", e))($$m14 || {});
var $$g7 = (e => (e[e.normal = 0] = "normal", e[e.destructive = 1] = "destructive", e))($$g7 || {});
var $$f5 = (e => (e[e.presetColor = 0] = "presetColor", e[e.customColor = 1] = "customColor", e[e.presetImage = 2] = "presetImage", e[e.customImage = 3] = "customImage", e))($$f5 || {});
export const $x = $$u0;
export const B9 = $$d1;
export const JI = $$o2;
export const MY = $$a3;
export const Pi = $$_4;
export const Ud = $$f5;
export const Vq = $$l6;
export const _3 = $$g7;
export const _E = $$p8;
export const _$$in = $$s9;
export const pc = $$n10;
export const pf = $$h11;
export const sg = $$i12;
export const xH = $$c13;
export const xf = $$m14;