let $$n1 = ["STROKE", "FILL"];
let $$i0 = ["RECTANGLE_BOTTOM_LEFT_CORNER_RADIUS", "RECTANGLE_BOTTOM_RIGHT_CORNER_RADIUS", "RECTANGLE_TOP_LEFT_CORNER_RADIUS", "RECTANGLE_TOP_RIGHT_CORNER_RADIUS", "STACK_SPACING_HORIZONTAL", "STACK_SPACING_VERTICAL", "STACK_PADDING_TOP", "STACK_PADDING_BOTTOM", "STACK_PADDING_LEFT", "STACK_PADDING_RIGHT"];
export const P = $$i0;
export const p = $$n1;