var $$r4 = (e => (e.INSERTS_MENU = "inserts_menu", e))($$r4 || {});
var $$n0 = (e => (e.MoveTools = "MoveTools", e))($$n0 || {});
var $$a1 = (e => (e[e.ACTIVATE_TOOL = 0] = "ACTIVATE_TOOL", e[e.TOGGLE_SUBMENU_AND_TOOL = 1] = "TOGGLE_SUBMENU_AND_TOOL", e[e.TOGGLE_COMMENTS = 2] = "TOGGLE_COMMENTS", e[e.TOGGLE_ACTIONS = 3] = "TOGGLE_ACTIONS", e))($$a1 || {});
var $$s3 = (e => (e.DrawingTools = "DrawingTools", e.StickyTools = "StickyTools", e.DiagrammingTools = "DiagrammingTools", e))($$s3 || {});
var $$o2 = (e => (e.SELECT = "toolDefault", e.HAND = "toolHand", e.PENCIL = "toolPencil", e.HIGHLIGHER = "toolHighlighter", e.WASHI_TAPE = "toolWashiTape", e.ERASER = "toolEraser", e.STICKY = "toolSticky", e.SHAPES = "shapes", e.TEXT = "toolText", e.SECTION = "toolSection", e.TABLE = "toolTable", e.STAMP = "toolStamp", e.COMMENT = "toolComment", e.ACTIONS = "buttonActions", e.INSERTS = "buttonInserts", e))($$o2 || {});
export const Ls = $$n0;
export const fo = $$a1;
export const hj = $$o2;
export const w = $$s3;
export const zK = $$r4;