var $$n5 = (e => (e[e.NONE = 0] = "NONE", e[e.PENDING = 1] = "PENDING", e[e.SHOWING = 2] = "SHOWING", e))($$n5 || {});
var $$r3 = (e => (e[e.BELOW = 0] = "BELOW", e[e.LEFT = 1] = "LEFT", e[e.RIGHT = 2] = "RIGHT", e[e.ABOVE = 3] = "ABOVE", e))($$r3 || {});
var $$a4 = (e => (e[e.CENTER = 0] = "CENTER", e[e.LEFT = 1] = "LEFT", e[e.RIGHT = 2] = "RIGHT", e))($$a4 || {});
var $$s2 = (e => (e[e.ELEMENT = 0] = "ELEMENT", e[e.KEY = 1] = "KEY", e[e.TEXT = 2] = "TEXT", e))($$s2 || {});
var $$o0 = (e => (e.TEXT = "text", e.LOOKUP = "lookup", e.SPECIAL = "special", e))($$o0 || {});
var $$l1 = (e => (e.HYPERLINK_POPUP = "tooltip-hyperlink-popup", e))($$l1 || {});
export const Ib = $$o0;
export const MW = $$l1;
export const Ui = $$s2;
export const Zj = $$r3;
export const qd = $$a4;
export const zr = $$n5;