/**
 * Enum representing various upsell and modal types.
 * Original variable: $$n0
 */
export enum UpsellModalType {
  UNSET = "",
  TILES_VIEW_UPSELL = "Tiles View Upsell",
  STARTER_TEAM_BADGE = "Starter Team Badge",
  STARTER_TEAM_FILE_BADGE = "Starter Team File Badge",
  LIBRARY_UPSELL_BADGE = "Library Upsell Badge",
  LIBRARY_MODAL_UPSELL = "Library Modal Upsell",
  PAGE_TRACKER_UPSELL = "Page Tracker Upsell",
  FILE_TRACKER_MODAL = "File Tracker Modal",
  BILLING_SETTINGS = "Billing Settings",
  UPGRADE_SECTION = "Upgrade Section",
  TEAM_SETTINGS_MODAL = "Team Settings Modal",
  BANNER = "Banner",
  SINGLE_TEAM_EVERGREEN_ORG_UPGRADE_SECTION = "Single-Team Evergreen Org Upgrade Section",
  MULTI_TEAM_EVERGREEN_ORG_UPGRADE_SECTION = "Multi-Team Evergreen Org Upgrade Section",
  AUDIO_PAYWALL = "Audio Paywall",
  UNIVERSAL_UPGRADE_SECTION = "Universal Upgrade Section",
  EDU_UPGRADE_SECTION = "Edu Upgrade Section",
  UNIVERSAL_UPGRADE_SEQUENCE_MACHINE = "Universal Upgrade Sequence Machine",
  SETTINGS_VIEW = "Settings View",
  UPGRADE_NEW_TEAM = "Upgrade New Team",
  UPGRADE_NEW_TEAM_V2 = "Upgrade New Team V2",
  PRO_TRIAL_UPSELL_MODAL = "Pro Trial V3",
  TEAM_WELCOME = "Team Welcome",
  HISTORY_UPSELL = "History Upsell",
  ORG_UPGRADE_SECTION = "Org Upgrade Section",
  BILLING_OVERVIEW = "Billing Overview",
  STARTER_TEAM_FOOTER = "Starter Team Footer",
  STARTER_TEAM_PROJECT_FOOTER = "Starter Team Project Footer",
  LOCKED_TEAM_BADGE = "Locked Team Badge",
  LOCKED_TEAM_FILE_BADGE = "Locked Team File Badge",
  LIBRARY_DUPLICATE_OSS_SALES_UPSELL = "Library Duplicate OSS Sales Upsell",
  UPSELL_LIBRARIES_REUSE_COMPONENTS_OVERLAY = "Upsell Libraries Reuse Components Overlay",
  CREATE_NEW_PAID_TEAM = "Create New Paid Team",
  UPGRADE_EXISTING_FROM_TEAM_CREATION = "Upgrade Existing From Team Creation",
  OSS_EXPOSURE_BRANCHING_UPSELL_MODAL = "OSS Exposure Branching Upsell Modal",
  FONT_PICKER_UPSELL = "Font Picker Upsell",
  MISSING_FONTS_UPSELL = "Missing Fonts Upsell",
  COLLECTIVE_UPSELLS_MODAL = "Collective Upsells Modal",
  ADVANCED_PROTOTYPING_UPSELL = "Advanced Prototyping Upsell",
  DEV_MODE_UPSELL = "Dev Mode Upsell",
  DEV_MODE_STARTER_TRIAL_ENDED_PAYWALL = "Dev Mode Starter Trial Ended Paywall",
  FOLDER_UPSELL_CARD = "Folder Upsell Card",
  STARTER_LIMIT_OVERVIEW = "Starter Limit Overview",
  DEEPLINK = "Deeplink",
  FIGJAM_UPSELL_MODAL = "FigJam Upsell Modal",
  FIGJAM_COMPARISON_MODAL = "Figjam Comparison Modal",
  DRAFT_FILE_BADGE = "Draft File Badge",
  DESIGN_DRAFT_FILE_BADGE = "Design Draft File Badge",
  DEV_MODE_STARTER_TRIAL_BANNER = "Dev Mode Starter Trial Banner",
  FOLDER_PERMISSION_MODAL = "Folder permission modal",
  SHARE_MODAL = "Share Modal",
  SITES_PUBLISH_MODAL = "Sites Publish Modal",
  SITES_DOMAIN_SETTINGS = "Sites Domain Settings",
  ADD_EDITOR = "Add Editor",
  FOLDER_CREATION_MODAL = "Folder Creation Modal",
  FOLDER_MOVE_MODAL = "Folder Move Modal",
  FILE_MOVE_MODAL = "File Move Modal",
  FILE_DUPLICATE = "File Duplicate",
  ADD_VARIABLE_MODES = "Add Variable Modes",
  ADD_VIDEO = "Add Video",
  PROTOTYPING_MULTIPLE_ACTIONS = "Prototyping Multiple Actions",
  PROTOTYPING_CONDITIONAL_ACTIONS = "Prototyping Conditional Actions",
  PROTOTYPING_VARIABLES = "Prototyping Variables",
  TEAM_CREATION_SPEED_BUMP = "Team Creation Speed Bump",
  SHAPES_SIDEBAR = "Shapes Sidebar",
  CONNECTED_PROJECT_INVITE = "Connected Project Invite",
  TEAM_SETTINGS_VIEW = "Team Settings View",
  BILLING_PLAN_TIER = "Billing Plan Tier",
  OSS_SALES_UPSELL_MODAL = "OSS Sales Upsell Modal",
  CONNECTED_PROJECTS_MAXIMUM_CONNECTIONS = "Connected Projects Maximum Connections",
  STARTER_VIEW_ONLY_BANNER = "Starter View Only Banner",
  FIGMAKE_METER_LIMIT_TOAST = "FigMake Meter Limit Toast",
  LIVING_DESIGNS_METER_LIMIT_TOAST = "Living Designs Meter Limit Toast",
  MCP_MODAL = "MCP Modal",
  CODE_CHAT_LIBRARY_IMPORT = "Code Chat Library Import",
  FIGMAKE_PUBLISH_SITE = "Make Publish Site",
  CREATE_NEW_FILE = "Create New File",
  CREATE_NEW_PAGE = "Create New Page",
  BILLING_FAQ_WIDGET = "Billing FAQ Widget",
  RESUBSCRIBE_SECTION = "Resubscribe Section"
}

/** 
 * Exported alias for UpsellModalType enum.
 * Original export: b = $$n0
 */
export const b = UpsellModalType;
