let $$n16 = 'banner__root__inu1D'
let $$r5 = 'banner__content__w-Bvk'
let $$a12 = 'banner__message__5vNg-'
let $$s10 = 'banner__messageTitle__05l4s'
let $$o13 = 'banner__link__xTpa-'
let $$l15 = 'banner__iconContainer__OJjv2'
let $$d7 = 'banner__fullWidthType__Z5YjP'
let $$c8 = 'banner__closeWrapper__LDSV6'
let $$u11 = 'banner__inlineType__5DSqf'
let $$p0 = 'banner__informationalType__TRLt9'
let $$m14 = 'banner__defaultVariant__j5VVa'
let $$h3 = 'banner__brandVariant__bdDQa'
let $$g2 = 'banner__insetModalType__iKAqf'
let $$f9 = 'banner__insetType__r9XLp'
let $$_4 = 'banner__dangerVariant__yECLr'
let $$A6 = 'banner__warnVariant__E2xQR'
let $$y1 = 'banner__successVariant__1VyPp'
export const Ck = $$p0
export const FM = $$y1
export const LC = $$g2
export const LO = $$h3
export const P2 = $$_4
export const Qs = $$r5
export const Sp = $$A6
export const W = $$d7
export const YE = $$c8
export const e1 = $$f9
export const eJ = $$s10
export const eW = $$u11
export const iU = $$a12
export const nf = $$o13
export const tp = $$m14
export const zc = $$l15
export const zr = $$n16
