var $$n1 = (e => (e.UPGRADE_NOT_NEEDED = "UPGRADE_NOT_NEEDED", e.CAN_UPGRADE = "CAN_UPGRADE", e.CANNOT_UPGRADE = "CANNOT_UPGRADE", e))($$n1 || {});
var $$r0 = (e => (e.ADMIN_AUTO_PATHWAY = "ADMIN_AUTO_PATHWAY", e.AUTO_PATHWAY = "AUTO_PATHWAY", e.PROVISIONAL_PATHWAY = "PROVISIONAL_PATHWAY", e.RE_REQUEST_PATHWAY = "RE_REQUEST_PATHWAY", e))($$r0 || {});
export const J = $$r0;
export const q = $$n1;