import { noop } from "../figma_app/465776";
export let $$r2 = {
  NONE: "NONE",
  DOCUMENT: "DOC",
  CANVAS: "CANV",
  GROUP: "GROUP",
  FRAME: "FRAME",
  BOOLEAN_OPERATION: "BOOL",
  VECTOR: "VECT",
  STAR: "STAR",
  LINE: "LINE",
  ELLIPSE: "ELLPS",
  RECTANGLE: "RECT",
  REGULAR_POLYGON: "POLY",
  ROUNDED_RECTANGLE: "RRECT",
  TEXT: "TEXT",
  TEXT_PATH: "TXPTH",
  SLICE: "SLICE",
  SYMBOL: "SYMB",
  STATE: "STATE",
  PRIMARY_INSTANCE: "PINST",
  NESTED_INSTANCE: "NINST",
  STICKY: "STCKY",
  SHAPE_WITH_TEXT: "SWTXT",
  CONNECTOR: "CONN",
  CODE_BLOCK: "CODE",
  WIDGET: "WIDGT",
  STAMP: "STAMP",
  MEDIA: "MEDIA",
  HIGHLIGHT: "HIGH",
  SECTION: "SECT",
  SECTION_OVERLAY: "SECTO",
  WASHI_TAPE: "WASHI",
  STATE_GROUP: "STGRP",
  FILL_STYLE: "FSTYL",
  STROKE_STYLE: "SSTYL",
  TEXT_STYLE: "TSTYL",
  EFFECT_STYLE: "ESTYL",
  EXPORT_STYLE: "XSTYL",
  GRID_STYLE: "GSTYL",
  VARIABLE: "VAR",
  VARIABLE_COLLECTION: "V_COL",
  VARIABLE_OVERRIDE: "V_OVR",
  TABLE: "TABLE",
  TABLE_CELL: "TCELL",
  SLIDE: "SLIDE",
  SLIDE_ROW: "SROW",
  SLIDE_GRID: "SGRID",
  ASSISTED_LAYOUT: "ALAYO",
  INTERACTIVE_SLIDE_ELEMENT: "FLAPP",
  MODULE: "MOD",
  RESPONSIVE_SET: "RESET",
  CODE_LIBRARY: "<LIB>",
  CODE_FILE: "<FIL>",
  CODE_COMPONENT: "<COM>",
  CODE_INSTANCE: "<INS>",
  JOURNAL_ENTRY: "JRNL",
  DIFF_CHUNK: "CHUNK",
  CODE_LAYER: "<LAY>",
  BRUSH: "BRUSH",
  MANAGED_STRING: "MGSTR",
  TRANSFORM: "TRSFM",
  CMS_RICH_TEXT: "CRTXT",
  REPEATER: "RPTR",
  JSX: "JSX",
  EMBEDDED_PROTOTYPE: "PROTO",
  REACT_FIBER: "FIBER",
  RESPONSIVE_NODE_SET: "RNS",
  WEBPAGE: "WEBP"
};
export var $$a0 = (e => (e[e.DesignSystems = 0] = "DesignSystems", e[e.FigJam = 1] = "FigJam", e[e.Editor = 2] = "Editor", e[e.Page = 3] = "Page", e[e.Other = 4] = "Other", e))($$a0 || {});
export function $$s1(e) {
  switch (e) {
    case "CODE_COMPONENT":
    case "CODE_INSTANCE":
    case "CODE_LIBRARY":
    case "CODE_FILE":
    case "CODE_LAYER":
    case "EFFECT_STYLE":
    case "EXPORT_STYLE":
    case "FILL_STYLE":
    case "GRID_STYLE":
    case "MODULE":
    case "NESTED_INSTANCE":
    case "PRIMARY_INSTANCE":
    case "STATE_GROUP":
    case "STATE":
    case "STROKE_STYLE":
    case "SYMBOL":
    case "TEXT_STYLE":
    case "VARIABLE_COLLECTION":
    case "VARIABLE_OVERRIDE":
    case "VARIABLE":
      return 0;
    case "BOOLEAN_OPERATION":
    case "BRUSH":
    case "ELLIPSE":
    case "LINE":
    case "RECTANGLE":
    case "REGULAR_POLYGON":
    case "ROUNDED_RECTANGLE":
    case "STAR":
    case "VECTOR":
      return 2;
    case "CODE_BLOCK":
    case "CONNECTOR":
    case "HIGHLIGHT":
    case "MEDIA":
    case "SECTION_OVERLAY":
    case "SHAPE_WITH_TEXT":
    case "STAMP":
    case "STICKY":
    case "TABLE":
    case "WASHI_TAPE":
      return 1;
    case "CANVAS":
    case "DIFF_CHUNK":
    case "DOCUMENT":
    case "JOURNAL_ENTRY":
      return 3;
    case "ASSISTED_LAYOUT":
    case "FRAME":
    case "GROUP":
    case "INTERACTIVE_SLIDE_ELEMENT":
    case "NONE":
    case "NONE":
    case "RESPONSIVE_SET":
    case "SECTION":
    case "SLICE":
    case "SLIDE_GRID":
    case "SLIDE_ROW":
    case "SLIDE":
    case "TABLE_CELL":
    case "TEXT_PATH":
    case "TEXT":
    case "WIDGET":
    case "MANAGED_STRING":
    case "TRANSFORM":
    case "CMS_RICH_TEXT":
    case "REPEATER":
    case "JSX":
    case "EMBEDDED_PROTOTYPE":
    case "REACT_FIBER":
    case "RESPONSIVE_NODE_SET":
    case "WEBPAGE":
      return 4;
    default:
      noop(e);
      return 4;
  }
}
export const SP = $$a0;
export const p7 = $$s1;
export const uy = $$r2;