let $$n17 = "AI Action Started";
let $$r8 = "AI Action Ended";
var $$a12 = (e => (e.COMPLETED = "completed", e.FAILED = "failed", e))($$a12 || {});
var $$s7 = (e => (e.ERROR = "error", e.EMPTY_GENERATION = "empty_generation", e.STOPPED = "stopped", e.SUCCESS = "success", e))($$s7 || {});
export let $$o1 = "AI Action Prompt Interaction";
var $$l10 = (e => (e.GENERATE = "generate", e.SELECT_KIT = "select_kit", e))($$l10 || {});
var $$d11 = (e => (e.BUTTON_CLICK = "button_click", e.KEYBOARD_SHORTCUT = "keyboard_shortcut", e))($$d11 || {});
export let $$c9 = "AI Action Instruction Interaction";
var $$u18 = (e => (e.DISMISS = "dismiss", e.EXECUTE = "execute", e.VIEW = "view", e))($$u18 || {});
var $$p13 = (e => (e.BUTTON_CLICK = "button_click", e.KEYBOARD_SHORTCUT = "keyboard_shortcut", e.VIEW = "view", e))($$p13 || {});
export let $$m19 = "AI Action Progress Interaction";
var $$h6 = (e => (e.STOP = "stop", e))($$h6 || {});
var $$g14 = (e => (e.BUTTON_CLICK = "button_click", e.KEYBOARD_SHORTCUT = "keyboard_shortcut", e))($$g14 || {});
export let $$f5 = "AI Action Iteration Interaction";
var $$_0 = (e => (e.DEFAULT_SUCCESS = "default_success", e.SUCCESS_WITH_REVIEW = "success_with_review", e.SUCCESS_WITH_ITERATION = "success_with_iteration", e.NO_CHANGES_MADE = "no_changes_made", e.ERROR = "error", e))($$_0 || {});
var $$A20 = (e => (e.COMPLETED = "completed", e.FAILED = "failed", e))($$A20 || {});
var $$y22 = (e => (e.DISMISS = "dismiss", e.UNDO = "undo", e.REVIEW = "review", e.MAKE_CHANGES = "make_changes", e.LEARN_MORE = "learn_more", e.RETRY = "retry", e.GO_BACK = "go_back", e.SAVE_AND_RELOAD = "save_and_reload", e.ACCEPT = "accept", e.GALLERY_SELECT = "gallery_select", e.GALLERY_ACCEPT = "gallery_accept", e.UNDO_MAKE_CHANGES = "undo_make_changes", e.BOOST_ANYWAY = "boost_anyway", e.POST_ACTION_EDIT = "post_action_edit", e.SELECT = "select", e))($$y22 || {});
var $$b3 = (e => (e.BUTTON_CLICK = "button_click", e.KEYBOARD_SHORTCUT = "keyboard_shortcut", e.NODE_EDITED = "node_edited", e.AUTO = "auto", e.FULLSCREEN_UNDO = "fullscreen_undo", e))($$b3 || {});
export let $$v16 = "AI Action Sentiment Feedback";
var $$I21 = (e => (e.THUMB_RATING = "thumb-rating", e))($$I21 || {});
var $$E2 = (e => (e[e.NEGATIVE = 0] = "NEGATIVE", e[e.POSITIVE = 1] = "POSITIVE", e))($$E2 || {});
export let $$x15 = "AI Action Additional Feedback";
export var $$S4 = (e => (e.FREE_TEXT = "free-text", e))($$S4 || {});
export const $J = $$_0;
export const Bq = $$o1;
export const Cb = $$E2;
export const Cq = $$b3;
export const EM = $$S4;
export const Ec = $$f5;
export const Ek = $$h6;
export const F9 = $$s7;
export const G5 = $$r8;
export const Lv = $$c9;
export const NI = $$l10;
export const bp = $$d11;
export const dM = $$a12;
export const dk = $$p13;
export const eb = $$g14;
export const f0 = $$x15;
export const hA = $$v16;
export const j4 = $$n17;
export const lc = $$u18;
export const m0 = $$m19;
export const o2 = $$A20;
export const s7 = $$I21;
export const sd = $$y22;