export let DESIGN_TYPES = ["CUSTOM", "TWITTER_POST", "LINKEDIN_POST", "INSTA_POST_SQUARE", "INSTA_POST_PORTRAIT", "INSTA_STORY", "INSTA_AD", "FACEBOOK_POST", "FACEBOOK_COVER_PHOTO", "FACEBOOK_EVENT_COVER", "FACEBOOK_AD_PORTRAIT", "FACEBOOK_AD_SQUARE", "PINTEREST_AD_PIN", "TWITTER_BANNER", "LINKEDIN_POST_SQUARE", "LINKEDIN_POST_PORTRAIT", "LINKEDIN_POST_LANDSCAPE", "LINKEDIN_PROFILE_BANNER", "LINKEDIN_ARTICLE_BANNER", "LINKEDIN_AD_LANDSCAPE", "LINKEDIN_AD_SQUARE", "LINKEDIN_AD_VERTICAL", "YOUTUBE_THUMBNAIL", "YOUTUBE_BANNER", "YOUTUBE_AD", "TWITCH_BANNER", "GOOGLE_LEADERBOARD_AD", "GOOGLE_LARGE_AD", "GOOGLE_MED_AD", "GOOGLE_MOBILE_BANNER_AD", "GOOGLE_SKYSCRAPER_AD", "CARD_HORIZONTAL", "CARD_VERTICAL", "PRINT_US_LETTER", "POSTER", "BANNER_STANDARD", "BANNER_WIDE", "BANNER_ULTRAWIDE", "NAME_TAG_PORTRAIT", "NAME_TAG_LANDSCAPE", "INSTA_REEL_COVER", "ZOOM_BACKGROUND"] as const


export const designTypeToIndex: Map<string, number> = new Map(
  DESIGN_TYPES.map((type, index) => [type, index])
);

/**
 * Maps each index to its corresponding design type.
 * (Original: $$a2)
 */
export const indexToDesignType: Map<number, string> = new Map(
  DESIGN_TYPES.map((type, index) => [index, type])
);
export const XH = DESIGN_TYPES;
export const n5 = designTypeToIndex;
export const po = indexToDesignType;
