import { getFeatureFlags } from "../905/601108";
import { debugState } from "../905/407919";
import { t as _$$t } from "../905/303541";
import { Qn } from "../figma_app/12796";
let n;
export function $$l0(e, t) {
  n || (n = {
    "toggle-spell-check": _$$t("fullscreen_actions.toggle-spell-check"),
    "redo-spell-checking": _$$t("fullscreen_actions.redo-spell-checking"),
    "spell-check-menu": _$$t("fullscreen_actions.spell-check-menu"),
    "spell-check-menu-add-word": _$$t("fullscreen.spell-check-menu-add-word"),
    "abandon-reattach": _$$t("fullscreen_actions.abandon_and_reattach_multiplayer"),
    "accessibility-settings": _$$t("viewer.options_menu.accessibility_settings"),
    "adapt-content-for-screenreaders": _$$t("fullscreen_actions.adapt_content_for_screenreaders"),
    "add-annotation": _$$t("dev_handoff.layers.add_annotation"),
    "add-comment": _$$t("comments.add_a_comment"),
    "add-prototype-starting-point": _$$t("fullscreen_actions.add-prototype-starting-point"),
    "add-selection-ready-status": _$$t("fullscreen_actions.ready-status-add"),
    "add-table-row-above": _$$t("fullscreen_actions.add-table-row-above"),
    "add-table-row-below": _$$t("fullscreen_actions.add-table-row-below"),
    "add-table-column-before": _$$t("fullscreen_actions.add-table-column-before"),
    "add-table-column-after": _$$t("fullscreen_actions.add-table-column-after"),
    "add-variant": _$$t("fullscreen_actions.add-variant"),
    "add-variant-to-template-set": _$$t("fullscreen_actions.add-variant"),
    "after-selecting-points": _$$t("fullscreen_actions.after_selecting_points"),
    "align-bottom": _$$t("fullscreen_actions.align-bottom"),
    "align-centers": _$$t("fullscreen_actions.align_centers"),
    "align-horizontal-center": _$$t("fullscreen_actions.align-horizontal-center"),
    "align-left": _$$t("fullscreen_actions.align-left"),
    "align-left-right": _$$t("fullscreen_actions.align_left_right"),
    "align-right": _$$t("fullscreen_actions.align-right"),
    "align-top": _$$t("fullscreen_actions.align-top"),
    "align-top-bottom": _$$t("fullscreen_actions.align_top_bottom"),
    "align-vertical-center": _$$t("fullscreen_actions.align-vertical-center"),
    "align-bottom-as-group": _$$t("fullscreen_actions.align-bottom-to-frame"),
    "align-horizontal-center-as-group": _$$t("fullscreen_actions.align-horizontal-center-to-frame"),
    "align-left-as-group": _$$t("fullscreen_actions.align-left-to-frame"),
    "align-right-as-group": _$$t("fullscreen_actions.align-right-to-frame"),
    "align-top-as-group": _$$t("fullscreen_actions.align-top-to-frame"),
    "align-vertical-center-as-group": _$$t("fullscreen_actions.align-vertical-center-to-frame"),
    "always-show-tabs-when-presenting": _$$t("fullscreen_actions.always_show_tabs_when_presenting"),
    "apply-palette-to-selection": "Apply palette to selection",
    "apply-transform-modifiers": _$$t("fullscreen_actions.apply-transform-modifiers"),
    "aspect-ratio-lock": _$$t("fullscreen_actions.aspect-ratio-lock"),
    "aspect-ratio-unlock": _$$t("fullscreen_actions.aspect-ratio-unlock"),
    "arrange-menu": _$$t("fullscreen_actions.arrange-menu"),
    "auto-suggest-eval": _$$t("fullscreen_actions.auto-suggest-eval"),
    "back-to-files": _$$t("fullscreen_actions.back-to-files"),
    "bend-tool": _$$t("fullscreen_actions.bend_tool"),
    "cut-tool": _$$t("fullscreen_actions.cut_tool"),
    bevel: _$$t("fullscreen.properties_panel.stroke_settings.bevel"),
    "bidi-update-info": _$$t("type_settings.bidi_update_tooltip"),
    "boolean-menu": _$$t("fullscreen_actions.boolean-menu"),
    "bring-forward": _$$t("fullscreen_actions.bring-forward"),
    "bring-to-front": _$$t("fullscreen_actions.bring-to-front"),
    "browse-all-resources-modal": _$$t("fullscreen_actions.browse-all-resources-modal"),
    "browse-all-resources-dlt": _$$t("fullscreen_actions.browse-all-resources-dlt"),
    "browse-all-resources-dlt-description": _$$t("fullscreen_actions.browse-all-resources-dlt-description"),
    "browse-all-resources-dlt-overflow": _$$t("fullscreen_actions.browse-all-resources-dlt-overflow"),
    "browse-all-resources-dlt-overflow-description": _$$t("fullscreen_actions.browse-all-resources-dlt-overflow-description"),
    "browse-plugins": _$$t("fullscreen_actions.manage-plugins"),
    "browse-widgets": _$$t("fullscreen_actions.manage-widgets"),
    "set-widget-thumbnail": _$$t("fullscreen_actions.set-widget-thumbnail"),
    "select-all-widgets": _$$t("fullscreen_actions.select-all-widgets"),
    "select-all-slides": _$$t("fullscreen_actions.select-all-slides"),
    "focus-mode": _$$t("fullscreen_actions.focus-mode"),
    "focus-mode-exit": _$$t("fullscreen_actions.focus-mode-exit"),
    "focus-mode-component-set-toggle": _$$t("fullscreen_actions.focus-mode-component-set-toggle"),
    "multi-edit-text": _$$t("fullscreen_actions.multi-edit-text"),
    "canvas-search": _$$t("fullscreen_actions.find"),
    "canvas-search-next": _$$t("fullscreen_actions.find-next"),
    "canvas-search-prev": _$$t("fullscreen_actions.find-prev"),
    "canvas-search-replace": _$$t("fullscreen_actions.canvas-search-replace"),
    "center-resize-drag": _$$t("fullscreen_actions.resize_from_center"),
    "change-feature-flags": _$$t("feature_flag_overrides.help_menu_button"),
    "choose-instance": _$$t("fullscreen_actions.choose_instance"),
    "clear-component-props-data-for-selection": _$$t("fullscreen_actions.clear-component-props-data-for-selection"),
    "clear-favicon": _$$t("fullscreen_actions.clear_favicon"),
    "create-brush-menu": _$$t("fullscreen_actions.create-brush-menu"),
    "create-stretch-brush": _$$t("fullscreen_actions.create-stretch-brush"),
    "create-scatter-brush": _$$t("fullscreen_actions.create-scatter-brush"),
    "create-scatter-brush-qc": _$$t("fullscreen_actions.create-scatter-brush-qc"),
    "create-stretch-brush-qc": _$$t("fullscreen_actions.create-stretch-brush-qc"),
    "break-vector-network-into-paths": getFeatureFlags().ce_il_var_width_strings ? _$$t("fullscreen_actions.split_vector") : _$$t("fullscreen_actions.break-vector-network-into-paths"),
    "dev-mode-mcp-server-settings": _$$t("fullscreen_actions.dev-mode-mcp-server-settings"),
    "component-insert": _$$t("fullscreen_actions.resources"),
    "component-insert-display-name": _$$t("fullscreen_actions.keyboard_shortcuts_panel.insert"),
    "component-insert-display-name-ui3": _$$t("fullscreen_actions.keyboard_shortcuts_panel.component-search"),
    components: "Components",
    "text-content-panel-heading": "Content",
    "convert-to-raster": _$$t("fullscreen_actions.convert-to-raster"),
    "copy-attachment": _$$t("comments.copy_attachment"),
    "copy-as-menu": _$$t("fullscreen_actions.copy-as-menu"),
    "copy-paste-menu": _$$t("fullscreen_actions.copy-paste-menu"),
    "copy-as-code": _$$t("fullscreen_actions.copy-as-code"),
    "copy-as-css": _$$t("fullscreen_actions.copy-as-css"),
    "copy-as-css-recursive": _$$t("fullscreen_actions.copy-as-css-recursive"),
    "copy-as-android": _$$t("fullscreen_actions.copy-as-android"),
    "copy-as-ios": _$$t("fullscreen_actions.copy-as-ios"),
    "copy-as-svg": _$$t("fullscreen_actions.copy-as-svg"),
    "copy-as-png": _$$t("fullscreen_actions.copy-as-png"),
    "copy-link": _$$t("fullscreen_actions.copy_link_to_selection"),
    "copy-properties": _$$t("fullscreen_actions.copy-properties"),
    "copy-text": _$$t("fullscreen_actions.copy-text"),
    "copy-to-figma-sites": _$$t("selection_context_menu.copy_to_figma_sites"),
    "copy-layer-name": _$$t("fullscreen_actions.copy_layer_name"),
    "copy-code": "Copy element",
    "copy-to-figma-slides": _$$t("slides.general.copy_to_figma_slides"),
    copy: _$$t("fullscreen_actions.copy"),
    "create-section-from-selection": _$$t("fullscreen_actions.create-section-from-selection"),
    "replace-selected-frame-with-section": _$$t("fullscreen_actions.replace-selected-frame-with-section"),
    "replace-selected-section-with-frame": _$$t("fullscreen_actions.replace-selected-section-with-frame"),
    "convert-table-to-sticky-grid": _$$t("fullscreen_actions.convert_to_stickies"),
    "create-state-group-row": _$$t("design_systems.templates.create_template_set"),
    "create-symbol": _$$t("fullscreen_actions.create-symbol"),
    "create-template": _$$t("fullscreen_actions.create-template"),
    "create-templates-from-row": _$$t("design_systems.templates.create_multiple_templates"),
    "convert-to-slot": _$$t("fullscreen_actions.convert-to-slot"),
    "empty-slot-contents": _$$t("fullscreen_actions.empty-slot-contents"),
    "create-multiple-symbols": _$$t("fullscreen_actions.create-multiple-symbols"),
    "create-multiple-symbols-and-state-group": _$$t("fullscreen_actions.create-multiple-symbols-and-state-group"),
    "publish-selection": _$$t("fullscreen_actions.publish-selection"),
    "publish-changes-to-library": _$$t("fullscreen_actions.publish-changes-to-library"),
    "publish-library-for-ai": _$$t("fullscreen_actions.publish_library_for_ai"),
    "publish-template": _$$t("fullscreen_actions.publish-template"),
    "create-state": _$$t("fullscreen_actions.create_variant"),
    "crop-image": _$$t("fullscreen_actions.crop-image"),
    cut: _$$t("fullscreen_actions.cut"),
    "debug-menu": "Debug",
    "better-noodles-menu": "Better Noodles settings",
    "magic-link-debug-group": "Magic Link",
    "debug-selection": _$$t("fullscreen_actions.debug-selection"),
    "deep-select": _$$t("fullscreen_actions.deep_select"),
    "deep-select-rectangle": _$$t("fullscreen_actions.deep_select_within_rectangle"),
    "delete-and-heal-selection": _$$t("fullscreen_actions.delete-and-heal-selection"),
    "delete-current-table-column": _$$t("fullscreen_actions.delete-current-table-column"),
    "add-default-cell-styles-to-tables": _$$t("fullscreen_actions.add-default-cell-styles-to-tables"),
    "delete-current-table-row": _$$t("fullscreen_actions.delete-current-table-row"),
    "delete-gradient-stop": _$$t("fullscreen.properties_panel.gradient_picker.delete_stop_shorthand"),
    "delete-prototype-starting-point": _$$t("fullscreen_actions.delete-prototype-starting-point"),
    "delete-selection": _$$t("fullscreen_actions.delete-selection"),
    "delete-table-contents": _$$t("fullscreen_actions.delete-table-contents"),
    "deselect-all": _$$t("fullscreen_actions.deselect-all"),
    "destroy-all-auto-layout": _$$t("fullscreen_actions.destroy-all-auto-layout"),
    "detach-all-instances": _$$t("fullscreen_actions.detach-all-instances"),
    "detach-deleted-styles": _$$t("fullscreen_actions.detach-deleted-styles"),
    "detach-deleted-variables": _$$t("fullscreen_actions.detach-deleted-variables"),
    "detach-locked-template": _$$t("fullscreen_actions.detach-locked-template"),
    "detach-instance": _$$t("fullscreen_actions.detach-instance"),
    "restore-soft-deleted-selection": _$$t("fullscreen_actions.restore-soft-deleted-selection"),
    "detach-multiplayer": "Detach multiplayer",
    "dev-handoff-code-settings-menu": _$$t("dev_handoff.code.settings"),
    "dev-handoff-code-settings-language": _$$t("dev_handoff.code.language"),
    "dev-handoff-css-language": _$$t("dev_handoff.code.lang_css"),
    "dev-handoff-ios-language-group": _$$t("dev_handoff.code.lang_ios"),
    "dev-handoff-swiftui-language": _$$t("dev_handoff.code.lang_swiftui"),
    "dev-handoff-uikit-language": _$$t("dev_handoff.code.lang_uikit"),
    "dev-handoff-android-language-group": _$$t("dev_handoff.code.lang_android"),
    "dev-handoff-xml-language": _$$t("dev_handoff.code.lang_android_xml"),
    "dev-handoff-compose-language": _$$t("dev_handoff.code.lang_compose"),
    "dev-handoff-code-settings-unit": _$$t("dev_handoff.alternative_units.dimension_unit"),
    "dev-handoff-code-settings-unit-pixel": _$$t("dev_handoff.alternative_units.pixel_unit"),
    "dev-handoff-code-settings-unit-pixel-quick-command": _$$t("dev_handoff.alternative_units.use_pixel_unit"),
    "dev-handoff-code-settings-unit-scaled": "#{scaledUnit}",
    "dev-handoff-code-settings-unit-scaled-quick-command": e => _$$t("dev_handoff.alternative_units.use_scaled_unit", e),
    "dev-handoff-code-settings-unit-settings": _$$t("dev_handoff.alternative_units.unit_settings_menu_option"),
    "disable-all-unframed-masks": _$$t("fullscreen_actions.disable-all-unframed-masks"),
    "discard-all-images": _$$t("fullscreen_actions.discard_all_images"),
    "distribute-bottom": _$$t("fullscreen_actions.distribute-bottom"),
    "distribute-horizontal-center": _$$t("fullscreen_actions.distribute-horizontal-center"),
    "distribute-horizontal-spacing": _$$t("fullscreen_actions.distribute-horizontal-spacing"),
    "distribute-left": _$$t("fullscreen_actions.distribute-left"),
    "distribute-right": _$$t("fullscreen_actions.distribute-right"),
    "distribute-top": _$$t("fullscreen_actions.distribute-top"),
    "distribute-spacing": _$$t("fullscreen_actions.distribute_spacing"),
    "distribute-vertical-center": _$$t("fullscreen_actions.distribute-vertical-center"),
    "distribute-vertical-spacing": _$$t("fullscreen_actions.distribute-vertical-spacing"),
    "dlt-shape-collage-button": _$$t("whiteboard.delightful_toolbar.shapes_and_connectors_label"),
    "downgrade-vector-operation-version": _$$t("fullscreen_actions.downgrade-vector-operation-version"),
    "download-attachment": _$$t("comments.download_attachment"),
    "download-webgl-trace": _$$t("fullscreen_actions.download-webgl-trace"),
    "duplicate-in-place": _$$t("fullscreen_actions.duplicate-in-place"),
    duplicate: _$$t("fullscreen_actions.duplicate_selection"),
    "edit-annotation": _$$t("dev_handoff.layers.edit_annotation"),
    "edit-menu": _$$t("fullscreen_actions.edit"),
    "edit-shape-or-image": _$$t("fullscreen_actions.edit-shape-or-image"),
    "edit-text": _$$t("fullscreen_actions.edit-text"),
    "enter-layout-mode": _$$t("fullscreen_actions.edit"),
    "enter-design-mode": _$$t("fullscreen_actions.enter-design-mode"),
    "enter-inspect-mode": _$$t("fullscreen_actions.enter-inspect-mode"),
    "enter-draw-mode": _$$t("fullscreen_actions.enter-draw-mode"),
    "enter-slides-design-mode": _$$t("slides.inserts_menu.design"),
    "enter-slides-design-mode-description": _$$t("slides.keyboard_shortcuts.enter-slides-design-mode-description"),
    "enter-slides-mode": _$$t("slides.inserts_menu.exit_design_mode"),
    "toggle-buzz-tool-mode": _$$t("cooper.keyboard_shortcuts.toggle-cooper-tool-mode"),
    "toggle-buzz-tool-mode-description": _$$t("cooper.keyboard_shortcuts.toggle-cooper-tool-mode-description"),
    "expand-element": _$$t("dev_handoff.layers.expand_children"),
    "explicit-text-layout-version-info": _$$t("type_settings.explicit_text_layout_update_tooltip"),
    "export-all-cooper-templates-to-pdf": _$$t("fullscreen_actions.export-all-cooper-templates-to-pdf"),
    "export-all-frames-to-pdf": _$$t("fullscreen_actions.export-all-frames-to-pdf"),
    "export-slides-to": _$$t("fullscreen_actions.export-slides-to"),
    "export-slides-to-pdf": _$$t("fullscreen_actions.export-slides-to-pdf"),
    "export-cooper-assets": _$$t("fullscreen_actions.export-cooper-assets"),
    "export-for-framer": _$$t("fullscreen_actions.export-for-framer"),
    "export-selected-exportables": _$$t("fullscreen_actions.export-selected-exportables"),
    "export-selected-exportables-desc": _$$t("fullscreen_actions.export"),
    "export-selected-video": _$$t("fullscreen.context_menu.export_selected_video"),
    "export-selection-or-current-page": _$$t("fullscreen_actions.export-selection-or-current-page"),
    "export-selection-or-current-page-desc": _$$t("fullscreen_actions.export_selection_or_current_page_desc"),
    "extensions-menu-dev-import-from-manifest": _$$t("whiteboard.inserts.development_options_import"),
    "figma-account-menu": _$$t("fullscreen_actions.figma-account-menu"),
    "file-menu": _$$t("fullscreen_actions.file-menu"),
    "file-new-menu": _$$t("fullscreen_actions.file-new-menu"),
    "find-symbol": _$$t("fullscreen_actions.find-symbol"),
    "flatten-selection": _$$t("fullscreen_actions.flatten-selection-short"),
    "flip-horizontal": _$$t("fullscreen_actions.flip-horizontal"),
    "flip-vertical": _$$t("fullscreen_actions.flip-vertical"),
    "focus-next-area": _$$t("fullscreen_actions.focus_next_area"),
    "focus-previous-area": _$$t("fullscreen_actions.focus_previous_area"),
    "frame-selection": _$$t("fullscreen_actions.frame-selection"),
    "get-desktop-app": _$$t("fullscreen_actions.get_desktop_app"),
    "group-selection": _$$t("fullscreen_actions.group-selection"),
    "hide-selected-nodes": _$$t("fullscreen_actions.hide_selection"),
    "hide-sibling-layers": _$$t("fullscreen_actions.hide-sibling-layers"),
    "ignore-constraints": _$$t("fullscreen_actions.ignore_constraints"),
    "ignore-constraints-desc": _$$t("fullscreen_actions.ignore_constraints_frames_only"),
    images: "Images",
    "images-description": "From your computer or device",
    "import-from-csv": _$$t("fullscreen_actions.import-from-csv"),
    import: _$$t("fullscreen_actions.import"),
    "collapse-layers": _$$t("fullscreen_actions.collapse-layers"),
    "insert-component-right-text": e => _$$t("fullscreen_actions.insert-component-right-text", e),
    "insert-slide-numbers-all-slides": _$$t("fullscreen_actions.insert-slide-numbers-all-slides"),
    "interface-scale-menu": "Interface scale",
    "community-hub-menu": "Community hub",
    "user-color-profile-menu-option": _$$t("fullscreen.color_management.user_color_profile.menu_item"),
    "user-color-profile-quick-action": _$$t("fullscreen.color_management.user_color_profile.quick_action"),
    "join-ui3-ai-waitlist": _$$t("help_widget.menu.join_ui3_ai_waitlist"),
    "keyboard-layout-menu-option": _$$t("keyboard_settings.keyboard_layout"),
    "keyboard-layout-us-qwerty": _$$t("keyboard_settings.us_qwerty"),
    "keyboard-layout-dvorak": _$$t("keyboard_settings.us_dvorak"),
    "keyboard-layout-german": _$$t("keyboard_settings.german_qwertz"),
    "keyboard-layout-french-azerty": _$$t("keyboard_settings.french_azerty"),
    "keyboard-layout-hiragana-kana": _$$t("keyboard_settings.japanese_kana"),
    "keyboard-layout-reset": _$$t("keyboard_settings.default_unknown"),
    "keyboard-layout-uk-mac": _$$t("keyboard_settings.uk_mac"),
    "keyboard-layout-uk-pc": _$$t("keyboard_settings.uk_pc"),
    "keyboard-layout-swedish": _$$t("keyboard_settings.swedish"),
    "keyboard-layout-finnish": _$$t("keyboard_settings.finnish"),
    "keyboard-layout-danish": _$$t("keyboard_settings.danish"),
    "keyboard-layout-norwegian": _$$t("keyboard_settings.norwegian"),
    "keyboard-layout-italian": _$$t("keyboard_settings.italian"),
    "keyboard-layout-spanish": _$$t("keyboard_settings.spanish"),
    "keyboard-layout-spanish-latam": _$$t("keyboard_settings.spanish_latin_america"),
    "keyboard-layout-chinese": _$$t("keyboard_settings.chinese"),
    "keyboard-layout-portuguese": _$$t("keyboard_settings.portuguese"),
    "keyboard-layout-korean": _$$t("keyboard_settings.korean"),
    "migrate-effect-repeats-to-transforms": _$$t("fullscreen_actions.migrate-effect-repeats-to-transforms"),
    "migrate-pattern-spacing": "Migrate pattern spacing field",
    "plugins-menu": _$$t("fullscreen_actions.plugins-menu"),
    "plugins-menu-manage": _$$t("fullscreen_actions.plugins-menu-manage"),
    "plugins-menu-manage-development": _$$t("fullscreen_actions.manage_plugins_in_development"),
    "plugins-menu-browse": _$$t("fullscreen_actions.plugins-menu-browse"),
    "plugins-menu-dev": _$$t("widgets.development"),
    "plugins-menu-item": "#{extensionName}",
    "plugins-menu-item-run": `Run\u2026`,
    "plugins-menu-item-share": `Share\u2026`,
    "plugins-menu-show-deprecated": `Deprecated plugins\u2026`,
    "plugins-menu-use-desktop": "Not available",
    "plugins-menu-dev-create-new": _$$t("whiteboard.inserts.plugin_development_options_new_plugin"),
    "plugins-menu-dev-import-from-manifest": _$$t("whiteboard.inserts.plugin_development_options_import_plugin"),
    "plugins-menu-dev-add": `Add plugin from file\u2026`,
    "plugins-menu-dev-toggle-hot-reload": _$$t("fullscreen_actions.hot_reload_plugin"),
    "plugins-menu-dev-toggle-realms": _$$t("fullscreen_actions.use_developer_vm"),
    "plugins-menu-add-from-key": `Add plugin from key\u2026`,
    "plugins-menu-item-reload": "Reload",
    "plugins-menu-item-remove": `Remove\u2026`,
    "plugins-menu-open-directory-mac": _$$t("whiteboard.inserts.plugin_development_options_finder"),
    "plugins-menu-open-directory-win": _$$t("whiteboard.inserts.plugin_development_options_explorer"),
    "plugins-menu-open-directory-vscode": _$$t("fullscreen.plugins_menu.open_directory_vscode"),
    "plugins-menu-toggle-console": _$$t("fullscreen_actions.toggle_console"),
    "plugins-menu-use-local-related-link-plugin": _$$t("fullscreen_actions.use_local_related_link_plugin"),
    "plugins-menu-show-error": `Show error details\u2026`,
    "plugins-menu-plugin-missing": `\u26A0 Plugin missing`,
    "plugins-menu-manifest-issue": `\u26A0 Manifest issue`,
    "plugins-menu-view-only": "Unavailable in view-only",
    "plugins-menu-view-documentation": _$$t("fullscreen_actions.view_api_documentation"),
    "plugins-run-last": _$$t("fullscreen_actions.plugins-run-last"),
    "plugins-realms-vm": "Developer VM",
    "plugins-background": e => _$$t("fullscreen.plugins.background", e),
    "plugins-cancel": _$$t("fullscreen.plugins.cancel"),
    "plugins-inserting": e => _$$t("fullscreen.plugins.inserting", e),
    "plugins-running": e => _$$t("fullscreen.plugins.running", e),
    "plugins-stop": _$$t("fullscreen.plugins.stop"),
    "plugins-stopped": e => _$$t("fullscreen.plugins.stopped", e),
    "prune-invalid-component-prop-refs": _$$t("fullscreen_actions.prune_invalid_component_prop_refs"),
    "prune-orphaned-slot-content": _$$t("fullscreen_actions.prune-orphaned-slot-content"),
    "join-selection": _$$t("fullscreen_actions.join-selection"),
    labs: _$$t("lab.menu.labs"),
    "lab-menu-item-enable": e => _$$t("lab.enable", e),
    "lab-ui3-menu-item-enable-ga": _$$t("lab.ui3_enable_ga"),
    "lab-menu-item": "#{labName}",
    "lab-menu-reset": _$$t("lab.menu.reset_all"),
    "labeled-menu-item": "#{label}",
    "leave-edit-mode": _$$t("fullscreen_actions.leave_edit_mode"),
    "leave-vector-edit-mode": _$$t("fullscreen_actions.exit_vector_edit_mode_esc"),
    "library-updates-from-current-file": "Updates from the current file occur when outdated styles or instances are added to the file.",
    "line-height-update-info": "The new rendering changes the line height behavior and fixes many bugs. You can always undo the update.",
    "link-copied": _$$t("copy_to_clipboard.link_copied_to_clipboard"),
    "live-boolean-intersect": _$$t("fullscreen_actions.live-boolean-intersect-short"),
    "live-boolean-subtract": _$$t("fullscreen_actions.live-boolean-subtract-short"),
    "live-boolean-union": _$$t("fullscreen_actions.live-boolean-union-short"),
    "live-boolean-xor": _$$t("fullscreen_actions.live-boolean-xor-short"),
    "add-transform-modifier-to-selection": _$$t("fullscreen_actions.add-transform-modifier-to-selection"),
    "add-skew-modifier-to-selection": _$$t("fullscreen_actions.add_transform-modifier-skew"),
    "add-linear-repeat-to-selection": _$$t("fullscreen_actions.add_transform-modifier-linear"),
    "add-radial-repeat-to-selection": _$$t("fullscreen_actions.add_transform-modifier-radial"),
    "set-tool-vector-lasso": _$$t("fullscreen_actions.set-tool-vector-lasso"),
    "set-tool-offset-path": _$$t("fullscreen_actions.set-tool-offset-path"),
    "set-tool-simplify-vector": _$$t("fullscreen_actions.set-tool-simplify-vector"),
    "lock-selected-nodes": "Lock selection",
    "mask-selection": _$$t("fullscreen_actions.mask-selection"),
    "remove-mask": _$$t("fullscreen.menu.remove_mask"),
    "create-comment": _$$t("fullscreen_actions.create-comment"),
    "create-diamond": _$$t("fullscreen_actions.create-diamond"),
    "create-triangle": _$$t("fullscreen_actions.create-triangle"),
    "create-ellipse": _$$t("fullscreen_actions.create-ellipse"),
    "create-slides-outline-from-figjam": _$$t("fullscreen_actions.create-slides-outline-from-figjam"),
    "create-responsive-set": _$$t("fullscreen_actions.create-responsive-set"),
    "focus-mode-responsive-set": _$$t("fullscreen_actions.focus-mode-responsive-set"),
    "focus-mode-responsive-set-enable": _$$t("fullscreen_actions.focus-mode-responsive-set-enable"),
    "focus-mode-responsive-set-disable": _$$t("fullscreen_actions.focus-mode-responsive-set-disable"),
    "create-rounded-rectangle": _$$t("fullscreen_actions.create-rounded-rectangle"),
    "create-text-node": _$$t("fullscreen_actions.create-text-node"),
    "create-sticky": _$$t("fullscreen_actions.create-sticky"),
    "create-section": _$$t("fullscreen_actions.create-section"),
    "create-slide": _$$t("fullscreen_actions.create-slide"),
    "main-component": _$$t("fullscreen_actions.main-component"),
    "main-menu": _$$t("fullscreen_actions.main_menu"),
    "mark-as-read": _$$t("comments.mark_as_read"),
    "mark-as-unread": _$$t("comments.mark_as_unread"),
    "measure-to-selection": _$$t("fullscreen_actions.measure_to_selection"),
    "minimize-ui": _$$t("fullscreen_actions.minimize-ui"),
    miter: _$$t("fullscreen.properties_panel.stroke_settings.miter"),
    "move-while-resizing": _$$t("fullscreen_actions.move_while_resizing"),
    "new-from-templates": _$$t("fullscreen_actions.new-from-templates"),
    "new-from-templates-description": _$$t("fullscreen_actions.new-from-templates-description"),
    "next-artboard": _$$t("fullscreen_actions.next-artboard"),
    "next-artboard-same-zoom": _$$t("fullscreen_actions.next-artboard-same-zoom"),
    "move-table-row-up": _$$t("fullscreen_actions.move-table-row-up"),
    "move-table-row-down": _$$t("fullscreen_actions.move-table-row-down"),
    "move-table-column-left": _$$t("fullscreen_actions.move-table-column-left"),
    "move-table-column-right": _$$t("fullscreen_actions.move-table-column-right"),
    "move-to-file": _$$t("fullscreen_actions.move_to_file"),
    "object-menu": _$$t("fullscreen_actions.object-menu"),
    "open-account-settings": _$$t("fullscreen_actions.open-account-settings"),
    "open-file-right-text": "in #{folder_name}",
    "open-font-settings": _$$t("fullscreen_actions.open-font-settings"),
    "open-in-desktop-app": _$$t("fullscreen_actions.open-in-desktop-app"),
    "open-legal-summary": _$$t("fullscreen_actions.open-legal-summary"),
    "open-link": _$$t("fullscreen_actions.open-link"),
    "open-links-in-desktop-app": _$$t("fullscreen_actions.open-links-in-desktop-app"),
    "open-release-notes": _$$t("fullscreen_actions.open-release-notes"),
    "open-help": _$$t("fullscreen_actions.open-help"),
    "open-shortcuts": _$$t("fullscreen_actions.open-shortcuts"),
    "open-support-forum": _$$t("fullscreen_actions.open-support-forum"),
    "open-tutorials": _$$t("fullscreen_actions.open-tutorials"),
    "toggle-variables": _$$t("fullscreen_actions.toggle-variables"),
    "open-preferences-modal": _$$t("fullscreen_actions.open-preferences-modal"),
    "outline-stroke": _$$t("fullscreen_actions.outline-stroke"),
    "pack-horizontal": _$$t("fullscreen_actions.pack-horizontal"),
    "pack-vertical": _$$t("fullscreen_actions.pack-vertical"),
    "page-convert-to-figjam": _$$t("fullscreen_actions.page-convert-to-figjam"),
    "page-convert-to-figma": _$$t("fullscreen_actions.page-convert-to-figma"),
    "page-copy-link": _$$t("fullscreen_actions.page-copy-link"),
    "page-delete": _$$t("fullscreen_actions.page-delete"),
    "page-duplicate": _$$t("fullscreen_actions.page-duplicate"),
    "page-move-to": _$$t("fullscreen_actions.page-move-to", {
      name: "#{name}"
    }),
    "page-move-to-menu": _$$t("fullscreen_actions.page-move-to-menu"),
    "page-move-to-new-file": _$$t("fullscreen_actions.page-move-to-new-file"),
    "page-new": _$$t("fullscreen_actions.new_page"),
    "page-next": _$$t("fullscreen_actions.page-next"),
    "page-previous": _$$t("fullscreen_actions.page-previous"),
    "page-rename": _$$t("fullscreen_actions.page-rename"),
    "batch-page-rename": _$$t("fullscreen_actions.page-rename"),
    pan: _$$t("fullscreen_actions.pan"),
    "panels-menu": _$$t("fullscreen_actions.panels-menu"),
    paste: _$$t("fullscreen_actions.paste"),
    "paste-here": _$$t("fullscreen_actions.paste-here"),
    "paste-over-selection": _$$t("fullscreen_actions.paste-over-selection"),
    "paste-properties": _$$t("fullscreen_actions.paste-properties"),
    "paste-to-replace": _$$t("fullscreen_actions.paste-to-replace"),
    "place-all-images": _$$t("fullscreen_actions.place_all_images"),
    place: () => {
      let {
        openFile
      } = debugState?.getState();
      return Qn(openFile) ? _$$t("fullscreen_actions.place") : _$$t("fullscreen_actions.place_image");
    },
    "plugin-dock": "Open in the inspect panel",
    "position-panel-fixed-disabled": _$$t("sites.panel.position_panel.fixed_disabled"),
    "position-panel-relative-disabled": _$$t("sites.panel.position_panel.relative_disabled"),
    "preferences-menu": _$$t("fullscreen_actions.preferences-menu"),
    "previous-artboard": _$$t("fullscreen_actions.previous-artboard"),
    "previous-artboard-same-zoom": _$$t("fullscreen_actions.previous-artboard-same-zoom"),
    "print-image-diagnostics": _$$t("fullscreen_actions.print-image-diagnostics"),
    "print-render-tree": _$$t("fullscreen_actions.print-render-tree"),
    "toggle-display-dirty-rects": _$$t("fullscreen_actions.toggle-display-dirty-rects"),
    "toggle-display-dirty-tiles": _$$t("fullscreen_actions.toggle-display-dirty-tiles"),
    "toggle-display-pixel-heat-map": _$$t("fullscreen_actions.toggle-display-pixel-heat-map"),
    "toggle-display-expensive-tiles": _$$t("fullscreen_actions.toggle-display-expensive-tiles"),
    "toggle-display-gpu-metrics": _$$t("fullscreen_actions.toggle-display-gpu-metrics"),
    "toggle-display-cpu-timer-tree": _$$t("fullscreen_actions.toggle-display-cpu-timer-tree"),
    "toggle-perf-mode-medium": _$$t("fullscreen_actions.toggle-perf-mode-medium"),
    "redistribute-gradient-stops": _$$t("fullscreen.properties_panel.gradient_picker.redistribute_stops"),
    "repair-corrupt-override-keys-for-selected": _$$t("fullscreen_actions.repair-corrupt-override-keys-for-selected"),
    "repair-missing-override-keys": _$$t("fullscreen_actions.repair-missing-override-keys"),
    "purge-all-memory": _$$t("fullscreen_actions.purge-all-memory"),
    "push-changes-to-main": _$$t("fullscreen_actions.push-changes-to-main"),
    "quick-actions-modal-placeholder": _$$t("fullscreen_actions.search_menus_commands_and_plugins"),
    "quick-actions-with-wand-modal-placeholder": _$$t("fullscreen_actions.search"),
    "regenerate-all-instances": _$$t("fullscreen_actions.regenerate-all-instances"),
    "regenerate-file-geometry": _$$t("fullscreen_actions.regenerate-file-geometry"),
    "regenerate-missing-thumbnails": _$$t("fullscreen_actions.regenerate-missing-thumbnails"),
    "backup-all-overrides": _$$t("fullscreen_actions.backup-all-overrides"),
    "select-broken-fixed-scrolling-nodes": _$$t("fullscreen_actions.select-broken-fixed-scrolling-nodes"),
    redo: _$$t("fullscreen_actions.redo"),
    "quick-create-immutable-frame": _$$t("fullscreen_actions.quick_create_immutable_frame"),
    "stamp-on-node": _$$t("fullscreen_actions.stamp_on_node"),
    "reattach-multiplayer": "Reattach multiplayer",
    "reflow-immutable-frames": _$$t("fullscreen_actions.reflow-immutable-frames"),
    "swap-nodes": _$$t("fullscreen_actions.swap-nodes"),
    "regenerate-component-props": _$$t("fullscreen_actions.regenerate-component-props"),
    "remove-annotations": _$$t("fullscreen_actions.remove-annotations"),
    "remove-fill": _$$t("fullscreen_actions.remove-fill"),
    "remove-guide": _$$t("fullscreen_actions.remove-guide"),
    "remove-horizontal-guides": _$$t("fullscreen_actions.remove-horizontal-guides"),
    "remove-orphaned-variables": _$$t("fullscreen_actions.remove-orphaned-variables"),
    "remove-responsive-text-style-variants": _$$t("fullscreen_actions.remove-responsive-text-style-variants"),
    "remove-stroke": _$$t("fullscreen_actions.remove-stroke"),
    "remove-vertical-guides": _$$t("fullscreen_actions.remove-vertical-guides"),
    "rename-selection": _$$t("fullscreen_actions.rename-selection"),
    "repair-duplicate-subscribed-assets": _$$t("fullscreen_actions.repair-duplicate-subscribed-assets"),
    "repair-selected-instances": _$$t("fullscreen_actions.repair-selected-instances"),
    "repair-breakpoint-multiedit": _$$t("fullscreen_actions.repair-breakpoint-multiedit"),
    "repair-state-group-versions": _$$t("fullscreen_actions.repair-state-group-versions"),
    "repair-variable-connections": _$$t("fullscreen_actions.repair-variable-connections"),
    "repair-variable-mode-values": _$$t("fullscreen_actions.repair-variable-mode-values"),
    "reresolve-variable-references": _$$t("fullscreen_actions.reresolve-variable-references"),
    "restore-soft-deleted-variable-sets": _$$t("fullscreen_actions.restore-soft-deleted-variable-sets"),
    "relink-instances-to-local-component": _$$t("fullscreen_actions.relink-instances-to-local-component"),
    "restore-autolayout-position": _$$t("fullscreen_actions.restore-autolayout-position"),
    "find-shared-instances-need-relinking": _$$t("fullscreen_actions.find-shared-instances-need-relinking"),
    "calculate-deleted-components-published-version": _$$t("fullscreen_actions.calculate-deleted-components-published-version"),
    "republish-selected-components": _$$t("fullscreen_actions.republish-selected-components"),
    "republish-auto-layout-components": _$$t("fullscreen_actions.republish-auto-layout-components"),
    "request-edit-mode-via-toolbar": _$$t("fullscreen_actions.edit_object"),
    "request-edit-mode": _$$t("fullscreen_actions.edit_object"),
    "reset-thumbnail": _$$t("fullscreen_actions.restore_default_thumbnail"),
    "reset-file-thumbnail": _$$t("fullscreen_actions.restore_default_file_thumbnail"),
    "reset-page-thumbnail": _$$t("fullscreen_actions.restore_default_page_thumbnail"),
    "reset-symbol": _$$t("fullscreen_actions.reset-instance"),
    "reset-fauxverride": _$$t("fullscreen_actions.reset-changes"),
    "reset-size": _$$t("design_systems.instance_panel.reset_size"),
    "reset-exports": _$$t("design_systems.instance_panel.reset_exports"),
    "reset-effects": _$$t("design_systems.instance_panel.reset_effects"),
    "reset-layer": _$$t("design_systems.instance_panel.reset_others"),
    "reset-visible": _$$t("design_systems.instance_panel.reset_visibility"),
    "reset-name": _$$t("design_systems.instance_panel.reset_name"),
    "reset-fill": _$$t("design_systems.instance_panel.reset_fill"),
    "reset-stroke": _$$t("design_systems.instance_panel.reset_stroke"),
    "reset-text": _$$t("design_systems.instance_panel.reset_text"),
    "reset-text-style": _$$t("design_systems.instance_panel.reset_text_style"),
    "reset-prototype-interactions": _$$t("design_systems.instance_panel.reset_interactions"),
    "reset-overlay": _$$t("design_systems.instance_panel.reset_overlay"),
    "reset-variable-modes": _$$t("fullscreen_actions.reset-variable-modes"),
    "reset-transform": _$$t("fullscreen_actions.reset-transform"),
    "resize-proportionally": _$$t("fullscreen_actions.resize_proportionally"),
    "resize-to-fit": _$$t("fullscreen_actions.resize-to-fit"),
    "remove-interactions-on-selection": _$$t("fullscreen_actions.remove-interactions-on-selection"),
    "remove-all-plugin-actions": "Remove all plugin actions",
    "remove-interactions-on-page": _$$t("fullscreen_actions.remove-interactions-on-page"),
    "remove-plugin-actions": "Remove plugin actions",
    "remove-selection-status": _$$t("fullscreen_actions.ready-status-remove"),
    "replace-selected-text": "#{replacementText}",
    "report-issue": _$$t("help_widget.menu.report_issue"),
    "report-issue-performance": _$$t("help_widget.menu.report_performance_issue"),
    resolve: _$$t("comments.mark_as_resolved"),
    "restore-symbol-or-state-group": _$$t("fullscreen_actions.restore-symbol-or-state-group"),
    "rotate-180": _$$t("fullscreen_actions.rotate-180"),
    "rotate-90-clockwise": _$$t("fullscreen_actions.rotate-90-clockwise"),
    "rotate-90-counterclockwise": _$$t("fullscreen_actions.rotate-90-counterclockwise"),
    round: _$$t("fullscreen.properties_panel.stroke_settings.round"),
    "round-to-pixels": _$$t("fullscreen_actions.round-to-pixels"),
    "ruler-unit-menu": _$$t("fullscreen_actions.ruler-unit-menu"),
    "toggle-ruler-unit-pixels": _$$t("fullscreen_actions.ruler-unit-pixels"),
    "toggle-ruler-unit-inches": _$$t("fullscreen_actions.ruler-unit-inches"),
    "toggle-ruler-unit-centimeters": _$$t("fullscreen_actions.ruler-unit-centimeters"),
    "run-auto-auto-layout": "Run MSAL (with responsive)",
    "run-auto-auto-layout-skip-responsive": "Run MSAL (skip responsive)",
    "run-set-responsive-settings": "Make Responsive: Set responsive settings",
    "run-auto-auto-layout-with-section-detection": "Run Auto Auto Layout (AAL) with Section Detection",
    "run-auto-auto-layout-section-detection": "Test AAL Section Detection",
    "run-multi-stack-auto-layout": _$$t("fullscreen_actions.run-multi-stack-auto-layout"),
    "save-as": _$$t("fullscreen_actions.save-as"),
    "save-as-desc": "Save as",
    "set-commit-sha": _$$t("help_widget.menu.set_commit_sha"),
    "create-savepoint": _$$t("fullscreen_actions.create-savepoint"),
    "create-savepoint-desc": "Save to version history",
    "toggle-version-history": _$$t("fullscreen_actions.toggle-version-history"),
    "create-branch": _$$t("fullscreen_actions.create-branch"),
    "view-branches": _$$t("fullscreen_actions.see-all-branches"),
    "open-branch-source": _$$t("fullscreen_actions.view_main_file"),
    "view-branch-diff": _$$t("fullscreen_actions.review_changes"),
    "merge-branch": _$$t("fullscreen_actions.review_and_merge_changes"),
    "merge-branch-force": _$$t("fullscreen_actions.force_merge_branch"),
    "view-source-diff": `Review changes from main\u2026`,
    "update-branch": _$$t("fullscreen_actions.update_from_main"),
    "update-branch-force": _$$t("fullscreen_actions.force_update_from_main"),
    "update-branch-from-version": "Update from version\u2026",
    "search-results-empty": "No results found",
    "search-results-overflow": "More",
    search: "Search",
    "select-all": _$$t("fullscreen_actions.select-all"),
    "select-all-text": _$$t("fullscreen_actions.select-all-text"),
    "select-all-with-menu-options": _$$t("fullscreen_actions.select-all-with-menu-options"),
    "select-inverse": _$$t("fullscreen_actions.select-inverse"),
    "select-matching": _$$t("fullscreen_actions.select-matching"),
    "select-child": _$$t("fullscreen_actions.select-child"),
    "select-node": _$$t("fullscreen_actions.select-node", {
      name: "#{name}"
    }),
    "select-node-menu": _$$t("fullscreen_actions.select-node-menu"),
    "select-parent": _$$t("fullscreen_actions.select-parent"),
    "select-next-sibling": _$$t("fullscreen_actions.select-next-sibling"),
    "select-previous-sibling": _$$t("fullscreen_actions.select-previous-sibling"),
    "select-next-node": _$$t("fullscreen_actions.select-next-sibling"),
    "select-previous-node": _$$t("fullscreen_actions.select-previous-sibling"),
    "select-similar": _$$t("fullscreen_actions.select-similar"),
    "swap-to-related-state": _$$t("fullscreen_actions.change_variant"),
    "swap-to-related-symbol": _$$t("fullscreen_actions.swap_instance"),
    "select-same-effect": _$$t("fullscreen_actions.select-same-effect"),
    "select-same-fill": _$$t("fullscreen_actions.select-same-fill"),
    "select-same-font": _$$t("fullscreen_actions.select-same-font"),
    "select-same-instance": _$$t("fullscreen_actions.select-same-instance"),
    "select-same-stroke": _$$t("fullscreen_actions.select-same-stroke"),
    "select-same-style": _$$t("fullscreen_actions.select-same-style"),
    "select-same-text": _$$t("fullscreen_actions.select-same-text"),
    "select-same-variant": _$$t("fullscreen_actions.select-same-variant"),
    "send-backward": _$$t("fullscreen_actions.send-backward"),
    "send-to-back": _$$t("fullscreen_actions.send-to-back"),
    "set-constraints-automatically-toggle": _$$t("fullscreen_actions.set-constraints-automatically-toggle"),
    "set-constraints-automatically": _$$t("fullscreen_actions.set-constraints-automatically"),
    "set-constraints-manually": _$$t("fullscreen_actions.set-constraints-manually"),
    "set-default-style": _$$t("fullscreen_actions.set-default-style"),
    "set-selection-hug-horizontal": _$$t("fullscreen_actions.set-hug-width"),
    "set-selection-hug-vertical": _$$t("fullscreen_actions.set-hug-height"),
    "set-selection-fill-horizontal": _$$t("fullscreen_actions.set-fill-width"),
    "set-selection-fill-vertical": _$$t("fullscreen_actions.set-fill-height"),
    "set-favicon": _$$t("fullscreen_actions.set_as_favicon"),
    "set-thumbnail": _$$t("fullscreen_actions.set_as_thumbnail"),
    "set-file-thumbnail": _$$t("fullscreen_actions.set_as_file_thumbnail"),
    "set-page-thumbnail": _$$t("fullscreen_actions.set_as_page_thumbnail"),
    "set-image-as-profile-picture": _$$t("fullscreen_actions.set_image_as_profile_picture"),
    "set-missing-font": _$$t("fullscreen_actions.set-missing-font-on-text"),
    "set-opacity-00": _$$t("fullscreen_actions.set-opacity-00"),
    "set-opacity-0": _$$t("fullscreen_actions.set-opacity-0"),
    "set-opacity-1": _$$t("fullscreen_actions.set-opacity-1"),
    "set-opacity-2": _$$t("fullscreen_actions.set-opacity-2"),
    "set-opacity-3": _$$t("fullscreen_actions.set-opacity-3"),
    "set-opacity-4": _$$t("fullscreen_actions.set-opacity-4"),
    "set-opacity-5": _$$t("fullscreen_actions.set-opacity-5"),
    "set-opacity-6": _$$t("fullscreen_actions.set-opacity-6"),
    "set-opacity-7": _$$t("fullscreen_actions.set-opacity-7"),
    "set-opacity-8": _$$t("fullscreen_actions.set-opacity-8"),
    "set-opacity-9": _$$t("fullscreen_actions.set-opacity-9"),
    "show-rotation-origin": _$$t("fullscreen_actions.show-rotation-origin"),
    "open-timer": _$$t("fullscreen_actions.open-timer"),
    "present-as-prototype": _$$t("fullscreen_actions.present-as-prototype"),
    "present-sites-full-preview": _$$t("fullscreen_actions.present-sites-full-preview"),
    "present-slides-audience-view": _$$t("fullscreen_actions.present-slides-audience-view"),
    "present-slides-presenter-view": _$$t("fullscreen_actions.present-slides-presenter-view"),
    "set-as-primary-breakpoint": _$$t("fullscreen_actions.set-as-primary-breakpoint"),
    "toggle-inline-preview": _$$t("fullscreen_actions.toggle-inline-preview"),
    "toggle-inline-html-preview": _$$t("fullscreen_actions.toggle-inline-html-preview"),
    "set-tool-arrow": _$$t("fullscreen_actions.set-tool-arrow"),
    "set-tool-bend": _$$t("fullscreen_actions.set-tool-bend"),
    "set-tool-cut": _$$t("fullscreen_actions.set-tool-cut"),
    "set-tool-code-component": _$$t("fullscreen_actions.set-tool-code-component"),
    "set-tool-comments": _$$t("fullscreen_actions.set-tool-comments"),
    "set-tool-connector-straight": _$$t("fullscreen_actions.set-tool-connector-straight"),
    "set-tool-connector-elbowed": _$$t("fullscreen_actions.set-tool-connector-elbowed"),
    "set-tool-connector-elbowed-description": _$$t("fullscreen_actions.set-tool-connector-elbowed-description"),
    "set-tool-default": _$$t("fullscreen_actions.set-tool-default"),
    "set-tool-default-figjam": _$$t("fullscreen_actions.set-tool-default-figjam"),
    "set-tool-default-dev-handoff": _$$t("fullscreen_actions.set-tool-default-dev-handoff"),
    "set-tool-ellipse": _$$t("fullscreen_actions.set-tool-ellipse"),
    "set-tool-eraser": _$$t("fullscreen_actions.set-tool-eraser"),
    "set-tool-frame": _$$t("fullscreen_actions.set-tool-frame"),
    "set-tool-hand": _$$t("fullscreen_actions.set-tool-hand"),
    "set-tool-highlighter": _$$t("fullscreen_actions.set-tool-highlighter"),
    "set-tool-line": _$$t("fullscreen_actions.set-tool-line"),
    "set-tool-media": _$$t("fullscreen_actions.set-tool-media"),
    "set-tool-media-description": _$$t("fullscreen_actions.set-tool-media-description"),
    "set-tool-paint-bucket": _$$t("fullscreen_actions.set-tool-paint-bucket"),
    "set-tool-shape-builder": _$$t("fullscreen_actions.shape_builder_tool"),
    "set-tool-pen": _$$t("fullscreen_actions.set-tool-pen"),
    "set-tool-pencil": _$$t("fullscreen_actions.set-tool-pencil"),
    "set-tool-brush": _$$t("fullscreen_actions.set-tool-brush"),
    "set-tool-marker": _$$t("fullscreen_actions.set-tool-marker"),
    "set-tool-rectangle": _$$t("fullscreen_actions.set-tool-rectangle"),
    "set-tool-regular-polygon": _$$t("fullscreen_actions.set-tool-regular-polygon"),
    "set-tool-scale": _$$t("fullscreen_actions.set-tool-scale"),
    "set-tool-slice": _$$t("fullscreen_actions.set-tool-slice"),
    "set-tool-star": _$$t("fullscreen_actions.set-tool-star"),
    "set-tool-sticky": _$$t("fullscreen_actions.set-tool-sticky"),
    "set-tool-sticky-description": _$$t("fullscreen_actions.set-tool-sticky-description"),
    "set-tool-stamp": _$$t("fullscreen_actions.set-tool-stamp"),
    "set-tool-washi-tape": _$$t("fullscreen_actions.set-tool-washi-tape"),
    "set-as-default-responsive-set": _$$t("sites.fullscreen_actions.set-as-default-responsive-set"),
    "set-tool-section": _$$t("fullscreen_actions.set-tool-section"),
    "set-tool-section-description": _$$t("fullscreen_actions.set-tool-section-description"),
    "set-tool-table": _$$t("fullscreen_actions.set-tool-table"),
    "set-tool-table-description": _$$t("fullscreen_actions.set-tool-table-description"),
    "set-tool-annotate": _$$t("fullscreen_actions.set-tool-annotate"),
    "set-tool-annotate-desc": _$$t("fullscreen_actions.set-tool-annotate-desc"),
    "set-tool-measure": _$$t("fullscreen_actions.set-tool-measure"),
    "set-tool-stamp-description": _$$t("fullscreen_actions.set-tool-stamp-description"),
    "set-tool-shape-whiteboard-square": _$$t("fullscreen_actions.set-tool-shape-whiteboard-square"),
    "set-tool-shape-whiteboard-ellipse": _$$t("fullscreen_actions.set-tool-shape-whiteboard-ellipse"),
    "set-tool-shape-whiteboard-diamond": _$$t("fullscreen_actions.set-tool-shape-whiteboard-diamond"),
    "set-tool-shape-whiteboard-triangle-up": _$$t("fullscreen_actions.set-tool-shape-whiteboard-triangle-up"),
    "set-tool-shape-whiteboard-triangle-down": _$$t("fullscreen_actions.set-tool-shape-whiteboard-triangle-down"),
    "set-tool-shape-whiteboard-rounded-rectangle": _$$t("fullscreen_actions.set-tool-shape-whiteboard-rounded-rectangle"),
    "set-tool-shape-whiteboard-parallelogram-right": _$$t("fullscreen_actions.set-tool-shape-whiteboard-parallelogram-right"),
    "set-tool-shape-whiteboard-parallelogram-left": _$$t("fullscreen_actions.set-tool-shape-whiteboard-parallelogram-left"),
    "set-tool-shape-whiteboard-eng-database": _$$t("fullscreen_actions.set-tool-shape-whiteboard-eng-database"),
    "set-tool-shape-whiteboard-eng-queue": _$$t("fullscreen_actions.set-tool-shape-whiteboard-eng-queue"),
    "set-tool-shape-whiteboard-eng-file": _$$t("fullscreen_actions.set-tool-shape-whiteboard-eng-file"),
    "set-tool-shape-whiteboard-eng-folder": _$$t("fullscreen_actions.set-tool-shape-whiteboard-eng-folder"),
    "set-tool-shape-whiteboard-trapezoid": _$$t("fullscreen_actions.set-tool-shape-whiteboard-trapezoid"),
    "set-tool-shape-whiteboard-star": _$$t("fullscreen_actions.set-tool-shape-whiteboard-star"),
    "set-tool-shape-whiteboard-shield": _$$t("fullscreen_actions.set-tool-shape-whiteboard-shield"),
    "set-tool-shape-whiteboard-hexagon": _$$t("fullscreen_actions.set-tool-shape-whiteboard-hexagon"),
    "set-tool-shape-whiteboard-manual-input": _$$t("fullscreen_actions.set-tool-shape-whiteboard-manual-input"),
    "set-tool-shape-whiteboard-predefined-process": _$$t("fullscreen_actions.set-tool-shape-whiteboard-predefined-process"),
    "set-tool-shape-whiteboard-pentagon": _$$t("fullscreen_actions.set-tool-shape-whiteboard-pentagon"),
    "set-tool-shape-whiteboard-octagon": _$$t("fullscreen_actions.set-tool-shape-whiteboard-octagon"),
    "set-tool-shape-whiteboard-plus": _$$t("fullscreen_actions.set-tool-shape-whiteboard-plus"),
    "set-tool-shape-whiteboard-chevron": _$$t("fullscreen_actions.set-tool-shape-whiteboard-chevron"),
    "set-tool-shape-whiteboard-document-single": _$$t("fullscreen_actions.set-tool-shape-whiteboard-document-single"),
    "set-tool-shape-whiteboard-document-multiple": _$$t("fullscreen_actions.set-tool-shape-whiteboard-document-multiple"),
    "set-tool-shape-whiteboard-arrow-left": _$$t("fullscreen_actions.set-tool-shape-whiteboard-arrow-left"),
    "set-tool-shape-whiteboard-arrow-right": _$$t("fullscreen_actions.set-tool-shape-whiteboard-arrow-right"),
    "set-tool-shape-whiteboard-summing-junction": _$$t("fullscreen_actions.set-tool-shape-whiteboard-summing-junction"),
    "set-tool-shape-whiteboard-or": _$$t("fullscreen_actions.set-tool-shape-whiteboard-or"),
    "set-tool-shape-whiteboard-speech-bubble": _$$t("fullscreen_actions.set-tool-shape-whiteboard-speech-bubble"),
    "set-tool-shape-whiteboard-internal-storage": _$$t("fullscreen_actions.set-tool-shape-whiteboard-internal-storage"),
    "set-tool-type": _$$t("fullscreen_actions.set-tool-type"),
    "set-tool-type-description": _$$t("fullscreen_actions.set-tool-type-description"),
    "set-tool-arrow-desc": _$$t("fullscreen_actions.arrow_tool"),
    "set-tool-code-block": _$$t("fullscreen_actions.set-tool-code-block"),
    "set-tool-code-block-description": _$$t("fullscreen_actions.set-tool-code-block-description"),
    "set-tool-default-desc-figjam": _$$t("fullscreen_actions.set-tool-default-desc-figjam"),
    "set-tool-default-desc-figma": _$$t("fullscreen_actions.set-tool-default-desc-figma"),
    "set-tool-ellipse-desc": _$$t("fullscreen_actions.ellipse_tool"),
    "set-tool-frame-desc": _$$t("fullscreen_actions.frame_tool"),
    "set-tool-line-desc": _$$t("fullscreen_actions.line_tool"),
    "set-tool-pen-desc": _$$t("fullscreen_actions.pen_tool"),
    "set-tool-pencil-desc": _$$t("fullscreen_actions.pencil_tool"),
    "set-tool-rectangle-desc": _$$t("fullscreen_actions.rectangle_tool"),
    "set-tool-slice-desc": _$$t("fullscreen_actions.slice_tool"),
    "set-tool-type-desc": _$$t("fullscreen_actions.set_tool_type_desc"),
    "set-tool-mindmap-tree-nucleus": _$$t("fullscreen_actions.set_tool_mindmap_tree_nucleus"),
    "set-tool-sites-responsive-set": _$$t("fullscreen_actions.set-tool-sites-responsive-set"),
    "set-tool-sites-webpage": _$$t("fullscreen_actions.set-tool-sites-webpage"),
    "set-tool-sites-responsive-node-set": _$$t("fullscreen_actions.set-tool-sites-responsive-node-set"),
    "show-inspect-panel": _$$t("fullscreen_actions.show-properties-panel"),
    "show-design-panel": _$$t("fullscreen_actions.show-design-panel"),
    "show-templates-for-new-figjam-files": _$$t("fullscreen_actions.show-templates-for-new-figjam-files"),
    "sites-copy-link": _$$t("sites.fullscreen_actions.copy-external-url"),
    "straight-line": _$$t("fullscreen_actions.straight-line"),
    style: _$$t("fullscreen.properties_panel.style"),
    "spotlight-me": _$$t("fullscreen_actions.spotlight_me"),
    "follow-presenter": _$$t("fullscreen_actions.follow_presenter"),
    "toggle-downtime-banner": "Toggle downtime banner",
    "show-prototype-panel": _$$t("fullscreen_actions.show-prototype-panel"),
    "toggle-memory-usage-indicator": _$$t("fullscreen_actions.toggle-memory-usage-indicator"),
    "toggle-prototyping-info": _$$t("fullscreen_actions.toggle-prototyping-info"),
    "toggle-animate-info": _$$t("fullscreen_actions.toggle-animate-info"),
    "toggle-animate-info-description": _$$t("slides.keyboard_shortcuts.toggle-animate-info-description"),
    "toggle-grid-focus-view": _$$t("fullscreen_actions.toggle-slide-view"),
    "toggle-slide-view-short-description": _$$t("slides.keyboard_shortcuts.toggle-slide-view-short-description"),
    "toggle-view-short-description": _$$t("fullscreen_actions.toggle-view-short-description"),
    "toggle-figment-debugger": _$$t("fullscreen_actions.toggle-figment-debugger"),
    "show-nudge-amount-picker": _$$t("fullscreen_actions.show-nudge-amount-picker"),
    "show-pixel-grid": _$$t("fullscreen_actions.show_pixel_grid"),
    "show-layout-grids": _$$t("fullscreen_actions.show_layout_guides"),
    "enter-staging-mode": "Enter staging mode",
    "commit-staged-changes": "Commit staged changes",
    "rollback-staged-changes": "Rollback staged changes",
    "show-rulers": _$$t("fullscreen_actions.show_rulers"),
    "show-print-marks": _$$t("fullscreen_actions.show_print_marks"),
    "show-slices": _$$t("fullscreen_actions.show_slices"),
    "show-comments": _$$t("fullscreen_actions.show_comments"),
    "show-annotations": _$$t("fullscreen_actions.show_annotations"),
    "show-outlines": _$$t("fullscreen_actions.show_outlines"),
    "show-pixel-preview": _$$t("fullscreen_actions.show_pixel_preview"),
    "show-mask-outlines": _$$t("fullscreen_actions.show_mask_outlines"),
    "show-frame-outlines": _$$t("fullscreen_actions.show_frame_outlines"),
    "sign-out": _$$t("fullscreen_actions.sign-out"),
    "similar-includes-matching": _$$t("fullscreen_actions.similar-includes-matching"),
    "simplify-selected-instance-panels": _$$t("fullscreen_actions.simplify-selected-instance-panels"),
    "simulate-back-to-files": _$$t("fullscreen_actions.simulate-back-to-files"),
    "slides-rewrite-text": _$$t("fullscreen_actions.slides-rewrite-text"),
    "slides-generate-speaker-notes": _$$t("fullscreen_actions.slides-draft-speaker-notes"),
    "smooth-join-selection": _$$t("fullscreen_actions.smooth-join-selection"),
    "multi-stack-selection-submenu": _$$t("fullscreen_actions.multi-stack-selection-submenu"),
    "apply-multi-stack-selection": _$$t("fullscreen_actions.run-multi-stack-auto-layout"),
    "unstack-multi-stack-selection": _$$t("fullscreen_actions.destroy-all-auto-layout"),
    "stack-selection": _$$t("fullscreen_actions.stack-selection"),
    "unstack-selection": _$$t("fullscreen_actions.unstack-selection"),
    "stack-counter-align-left": _$$t("fullscreen_actions.align-left"),
    "stack-counter-align-horizontal-center": _$$t("fullscreen_actions.align-center"),
    "stack-counter-align-horizontal-stretch": "Stretch left and right",
    "stack-counter-align-right": _$$t("fullscreen_actions.align-right"),
    "stack-counter-align-top": _$$t("fullscreen_actions.align-top"),
    "stack-counter-align-vertical-center": _$$t("fullscreen_actions.align-center"),
    "stack-counter-align-vertical-stretch": _$$t("fullscreen_actions.stretch_top_and_bottom"),
    "stack-counter-align-bottom": _$$t("fullscreen_actions.align-bottom"),
    "stack-reorder-up": _$$t("fullscreen_actions.move_up"),
    "stack-reorder-up-end": _$$t("fullscreen_actions.move_to_top"),
    "stack-reorder-down": _$$t("fullscreen_actions.move_down"),
    "stack-reorder-down-end": _$$t("fullscreen_actions.move_to_bottom"),
    "stack-reorder-left": _$$t("fullscreen_actions.move_left"),
    "stack-reorder-left-end": _$$t("fullscreen_actions.move_to_left_edge"),
    "stack-reorder-right": _$$t("fullscreen_actions.move_right"),
    "stack-reorder-right-end": _$$t("fullscreen_actions.move_to_right_edge"),
    "start-chat": _$$t("fullscreen_actions.start-chat"),
    "start-magic-link": _$$t("fullscreen_actions.start-magic-link"),
    "end-magic-link": _$$t("fullscreen_actions.end-magic-link"),
    "straight-connector": _$$t("fullscreen_actions.straight_connector"),
    "supabase-menu": "Enable/Update Supabase",
    "foundry-menu": "Foundry Debug",
    "swap-fill-and-stroke": _$$t("fullscreen_actions.swap-fill-and-stroke"),
    "test-action": _$$t("fullscreen_actions.test-action"),
    "test-multiplayer-reject-invalid-permissions": _$$t("fullscreen_actions.test-multiplayer-reject-invalid-permissions"),
    "test-multiplayer-reject-not-logged-in": _$$t("fullscreen_actions.test-multiplayer-reject-not-logged-in"),
    "test-multiplayer-reject-too-many-connections": _$$t("fullscreen_actions.test-multiplayer-reject-too-many-connections"),
    "test-multiplayer-reject-too-old": _$$t("fullscreen_actions.test-multiplayer-reject-too-old"),
    "test-multiplayer-upgrade": _$$t("fullscreen_actions.test-multiplayer-upgrade"),
    "text-align-menu": _$$t("fullscreen_actions.text-align-menu"),
    "text-align-left": _$$t("fullscreen_actions.text-align-left"),
    "text-align-center": _$$t("fullscreen_actions.text-align-center"),
    "text-align-right": _$$t("fullscreen_actions.text-align-right"),
    "text-align-justified": _$$t("fullscreen_actions.text-align-justified"),
    "text-align-top": _$$t("fullscreen_actions.text-align-top"),
    "text-align-middle": _$$t("fullscreen_actions.text-align-middle"),
    "text-align-bottom": _$$t("fullscreen_actions.text-align-bottom"),
    "text-style-title": _$$t("fullscreen_actions.text_style_title"),
    "text-style-h1": _$$t("fullscreen_actions.text_style_h1"),
    "text-style-h2": _$$t("fullscreen_actions.text_style_h2"),
    "text-style-h3": _$$t("fullscreen_actions.text_style_h3"),
    "text-style-normal": _$$t("fullscreen_actions.text_style_normal"),
    "text-bold-adjust": _$$t("fullscreen_actions.adjust_font_weight"),
    "text-bold-increase": _$$t("fullscreen_actions.text-bold-increase"),
    "text-bold-decrease": _$$t("fullscreen_actions.text-bold-decrease"),
    "text-edit-hyperlink": _$$t("fullscreen_actions.text-edit-hyperlink"),
    "text-forced-small-caps": _$$t("fullscreen_actions.text-forced-small-caps"),
    "text-letter-spacing-increase": _$$t("fullscreen_actions.text-letter-spacing-increase"),
    "text-letter-spacing-decrease": _$$t("fullscreen_actions.text-letter-spacing-decrease"),
    "text-letter-spacing-adjust": _$$t("fullscreen_actions.adjust_letter_spacing"),
    "text-font-size-increase": _$$t("fullscreen_actions.text-font-size-increase"),
    "text-font-size-decrease": _$$t("fullscreen_actions.text-font-size-decrease"),
    "text-font-size-adjust": _$$t("fullscreen_actions.adjust_font_size"),
    "text-line-height-increase": _$$t("fullscreen_actions.text-line-height-increase"),
    "text-line-height-decrease": _$$t("fullscreen_actions.text-line-height-decrease"),
    "text-line-height-adjust": _$$t("fullscreen_actions.adjust_line_height"),
    "text-lower-case": _$$t("fullscreen_actions.text-lower-case"),
    "text-menu": _$$t("fullscreen_actions.text-menu"),
    "text-original-case": _$$t("fullscreen_actions.text-original-case"),
    "text-relayout": _$$t("fullscreen_actions.text-relayout"),
    "text-toggle-italic": _$$t("fullscreen_actions.text-toggle-italic"),
    "bold-and-italic": _$$t("fullscreen_actions.bold_and_italic"),
    "text-toggle-strikethrough": _$$t("fullscreen_actions.text-toggle-strikethrough"),
    "text-toggle-underline": _$$t("fullscreen_actions.text-toggle-underline"),
    "text-small-caps": _$$t("fullscreen_actions.text-small-caps"),
    "text-title-case": _$$t("fullscreen_actions.text-title-case"),
    "text-upper-case": _$$t("fullscreen_actions.text-upper-case"),
    "text-adjust-menu": _$$t("fullscreen_actions.text-adjust-menu"),
    "text-case-menu": _$$t("fullscreen_actions.text-case-menu"),
    "text-set-directionality-ltr": _$$t("fullscreen_actions.text-set-directionality-ltr"),
    "text-set-directionality-rtl": _$$t("fullscreen_actions.text-set-directionality-rtl"),
    "text-set-directionality-ltr-qa": _$$t("fullscreen_actions.text-set-directionality-ltr-qa"),
    "text-set-directionality-rtl-qa": _$$t("fullscreen_actions.text-set-directionality-rtl-qa"),
    "text-directionality-menu": _$$t("fullscreen_actions.text-directionality-menu"),
    "text-toggle-unordered-list": _$$t("fullscreen_actions.text-toggle-unordered-list"),
    "text-toggle-ordered-list": _$$t("fullscreen_actions.text-toggle-ordered-list"),
    "bulleted-and-numbered-list": _$$t("fullscreen_actions.bulleted_and_numbered_list"),
    "text-indent-list": _$$t("fullscreen_actions.text-indent-list"),
    "text-dedent-list": _$$t("fullscreen_actions.text-dedent-list"),
    "text-indent-and-dedent-list": _$$t("fullscreen_actions.text_indent_and_dedent_list"),
    "text-upgrade-explicit-layout-version": _$$t("fullscreen_actions.text-upgrade-explicit-layout-version"),
    "text-upgrade-to-bidi": _$$t("fullscreen_actions.text-upgrade-to-bidi"),
    "theme-dark-mode": _$$t("fullscreen_actions.theme.dark"),
    "theme-dark-mode-quick-command": _$$t("fullscreen_actions.theme.use_dark_mode"),
    "theme-debug-mode": _$$t("fullscreen_actions.theme.debug"),
    "theme-debug-mode-quick-command": _$$t("fullscreen_actions.theme.use_debug_mode"),
    "theme-legacy-mode": _$$t("fullscreen_actions.theme.light_legacy"),
    "theme-legacy-mode-quick-command": _$$t("fullscreen_actions.theme.use_light_legacy_mode"),
    "theme-light-mode": _$$t("fullscreen_actions.theme.light"),
    "theme-light-mode-quick-command": _$$t("fullscreen_actions.theme.use_light_mode"),
    "theme-system": _$$t("fullscreen_actions.theme.system_theme"),
    "theme-system-quick-command": _$$t("fullscreen_actions.theme.use_system_theme"),
    "theme-wildcard": _$$t("fullscreen_actions.theme-wildcard"),
    "theme-wildcard-quick-command": _$$t("fullscreen_actions.theme-wildcard-quick-command"),
    "theme-menu-option": _$$t("fullscreen_actions.theme-menu-option"),
    "theme-enhanced-contrast-quick-command": _$$t("fullscreen_actions.theme.enhanced_contrast"),
    "tidy-up": _$$t("fullscreen_actions.tidy-up"),
    "toggle-annotations": _$$t("fullscreen_actions.toggle-annotations"),
    "toggle-bold": _$$t("fullscreen_actions.toggle-bold"),
    "toggle-comments-debug-settings": "Toggle comments settings",
    "toggle-comments-debug-disable-sidebar": "Disable comments sidebar",
    "toggle-cursor-bot": "Toggle Cursor Bot",
    "toggle-cursor-bot-primary-cta": "Flip Cursor Bot Primary CTA",
    "toggle-enable-codegen-mcp-server": _$$t("fullscreen_actions.toggle-enable-codegen-mcp-server"),
    "toggle-sites-template-picker": "Toggle Sites template Picker",
    "toggle-tooltips-plus": "Toggle Tooltips+",
    "toggle-visual-asset-tooltips": "Toggle Visual Asset tooltips",
    "debug-ml-export": "Export to ML account",
    "toggle-copy-renaming": _$$t("fullscreen_actions.toggle-copy-renaming"),
    "toggle-layers-dom-order": _$$t("fullscreen_actions.toggle-layers-dom-order"),
    "toggle-canvas-search-debug": "Toggle canvas search debug",
    "toggle-accessibility-dom-debug": "Toggle accessibility dom debug",
    "open-fpl-debug": "Open FPL debug...",
    "open-template-generator": "Open template generator",
    "toggle-plugin-api-debug": "Toggle Plugin API debug",
    "toggle-overlay-ui-rendering": _$$t("fullscreen_actions.toggle-overlay-ui-rendering"),
    "toggle-allow-time-sliced-edit-rendering-optimization": _$$t("fullscreen_actions.toggle-allow-time-sliced-edit-rendering-optimization"),
    "toggle-similar-highlights": _$$t("fullscreen_actions.toggle-similar-highlights"),
    "toggle-noodles-without-dragging": _$$t("fullscreen_actions.toggle-noodles-without-dragging"),
    "toggle-sync-cursor-rendering": _$$t("fullscreen_actions.toggle-sync-cursor-rendering"),
    "restart-desktop-app-color-space-managed": _$$t("fullscreen_actions.restart-desktop-app-color-space-managed"),
    "download-memory-profile": _$$t("fullscreen_actions.download-memory-profile"),
    "restart-desktop-app-color-space-unmanaged": _$$t("fullscreen_actions.restart-desktop-app-color-space-unmanaged"),
    "show-toggle-prototype-mode-button": _$$t("fullscreen_actions.show-toggle-prototyping-mode-button"),
    "toggle-show-guids": _$$t("fullscreen_actions.toggle-show-guids"),
    "debug-toggle-figma-scope": _$$t("fullscreen_actions.debug-toggle-figma-scope"),
    "force-publish-state-group": _$$t("fullscreen_actions.force-publish-state-group"),
    "test-independent-layer-animation": _$$t("fullscreen_actions.test-independent-layer-animation"),
    "test-independent-layer-animation-eased": _$$t("fullscreen_actions.test-independent-layer-animation-eased"),
    "test-independent-layer-animation-opacity": _$$t("fullscreen_actions.test-independent-layer-animation-opacity"),
    "typescript-animations": "Typescript animations",
    "test-typescript-bezier-animation": "Test Typescript Bezier Animation",
    "test-typescript-oscillating-opacity-animation": "Test Typescript Oscillating Opacity Animation",
    "test-typescript-spring-animation": "Test Typescript Spring Animation",
    "test-typescript-spring-animation-high-bounciness": "Test Spring Animation - High Bounciness",
    "test-typescript-spring-animation-low-bounciness": "Test Spring Animation - Low Bounciness",
    "test-typescript-jiggle-animation": "Test Typescript Jiggle Animation",
    "cancel-last-animation": _$$t("fullscreen_actions.cancel-last-animation"),
    "test-non-independent-layer-animation": _$$t("fullscreen_actions.test-non-independent-layer-animation"),
    "debug-print-as-test-code": _$$t("fullscreen_actions.debug-print-as-test-code"),
    "debug-print-vector-network-as-test-code": _$$t("fullscreen_actions.debug-print-vector-network-as-test-code"),
    "toggle-show-quick-command-rank-debug": _$$t("fullscreen_actions.toggle-show-quick-command-rank-debug"),
    "toggle-show-immutable-frame-sublayers": _$$t("fullscreen_actions.toggle-show-immutable-frame-sublayers"),
    "toggle-force-publish-flattened": _$$t("fullscreen_actions.toggle-force-publish-flattened"),
    "toggle-debug-dark-theme": _$$t("fullscreen_actions.toggle_dark_theme"),
    "toggle-dropper": _$$t("fullscreen_actions.toggle-dropper"),
    "toggle-flip-during-resize": _$$t("fullscreen_actions.toggle-flip-during-resize"),
    "toggle-frame-clipping": _$$t("fullscreen_actions.toggle-frame-clipping"),
    "toggle-full-screen": _$$t("fullscreen_actions.toggle_full_screen"),
    "toggle-google-fonts": _$$t("fullscreen_actions.toggle-google-fonts"),
    "toggle-gradient-edit-mode": _$$t("fullscreen_actions.edit_gradient_paint"),
    "toggle-grid": _$$t("fullscreen_actions.toggle-grid"),
    "toggle-perf-hud": _$$t("fullscreen_actions.toggle-perf-hud"),
    "toggle-fake-mp-activity": _$$t("fullscreen_actions.toggle-fake-mp-activity"),
    "toggle-tsmer-config": _$$t("fullscreen_actions.toggle-tsmer-config"),
    "toggle-debug-layout-logs": _$$t("fullscreen_actions.toggle-debug-layout-logs"),
    "toggle-debug-doc-sync-logs": _$$t("fullscreen_actions.toggle-debug-doc-sync-logs"),
    "toggle-debug-user-sync-logs": _$$t("fullscreen_actions.toggle-debug-user-sync-logs"),
    "toggle-debug-page-sync-logs": _$$t("fullscreen_actions.toggle-debug-page-sync-logs"),
    "debug-incremental-loading-all-pages": _$$t("fullscreen_actions.debug-incremental-loading-all-pages"),
    "debug-incremental-loading-current-only": _$$t("fullscreen_actions.debug-incremental-loading-current-only"),
    "toggle-debug-materializer-logs": _$$t("fullscreen_actions.toggle-debug-materializer-logs"),
    "clear-constraint-info": _$$t("fullscreen_actions.clear-constraint-info"),
    "toggle-help-widget": _$$t("fullscreen_actions.hide_help_ui"),
    "toggle-invert-zoom": _$$t("fullscreen_actions.toggle-invert-zoom"),
    "toggle-cursor-high-five-wiggle": _$$t("fullscreen_actions.toggle-cursor-high-five-wiggle"),
    "toggle-keyboard-zoom-to-selection": _$$t("fullscreen_actions.toggle-keyboard-zoom-to-selection"),
    "toggle-layer-hover": _$$t("fullscreen_actions.toggle-layer-hover"),
    "toggle-layers": _$$t("fullscreen_actions.toggle-layers"),
    "toggle-publish": _$$t("fullscreen_actions.toggle-publish"),
    "toggle-publish-description": "Stickers and shared components",
    "toggle-library": _$$t("fullscreen_actions.team_library"),
    "toggle-layers-desc": _$$t("fullscreen_actions.show_layers"),
    "toggle-scroll-wheel-zoom": _$$t("fullscreen_actions.toggle-use-scroll-wheel-zoom"),
    "toggle-publish-desc": _$$t("fullscreen_actions.show_assets"),
    "toggle-locked-for-selected-nodes": _$$t("fullscreen_actions.toggle-locked-for-selected-nodes"),
    "toggle-menu": _$$t("fullscreen_actions.toggle-menu"),
    "toggle-actions-menu": _$$t("fullscreen_actions.toggle-actions-menu"),
    "toggle-multiplayer-cursors": _$$t("fullscreen_actions.toggle-multiplayer-cursors"),
    "toggle-outlines": _$$t("fullscreen_actions.toggle-outlines"),
    "toggle-pen-tool-avoid-single-handles": _$$t("fullscreen_actions.toggle-pen-tool-avoid-single-handles"),
    "toggle-pixel-preview": _$$t("fullscreen_actions.toggle-pixel-preview"),
    "toggle-raster-edit-mode": _$$t("fullscreen_actions.edit_image_crop"),
    "toggle-right-click-pan": _$$t("fullscreen_actions.toggle-right-click-pan"),
    "toggle-recording-interactions": _$$t("fullscreen_actions.toggle-recording-interactions"),
    "toggle-retina-mode": _$$t("fullscreen_actions.retina_mode"),
    "toggle-rulers": _$$t("fullscreen_actions.toggle-rulers"),
    "toggle-print-marks": _$$t("fullscreen_actions.toggle-print-marks"),
    "toggle-stack-debug-mode": _$$t("fullscreen_actions.toggle-stack-debug-mode"),
    "toggle-stack-shadows": _$$t("fullscreen_actions.toggle-stack-shadows"),
    "toggle-show-property-labels": _$$t("fullscreen_actions.toggle-show-property-labels"),
    "toggle-dynamic-insertion-points": _$$t("fullscreen_actions.toggle-dynamic-insertion-points"),
    "toggle-auto-fill-full-width-children": _$$t("fullscreen_actions.toggle-auto-fill-full-width-children"),
    "toggle-resource-use": _$$t("fullscreen_actions.toggle-resource-use"),
    "toggle-icon-detection": _$$t("fullscreen_actions.toggle-icon-detection"),
    "toggle-show-masks": _$$t("fullscreen_actions.toggle-show-masks"),
    "toggle-show-artboard-outlines": _$$t("fullscreen_actions.toggle-show-artboard-outlines"),
    "toggle-show-slices": _$$t("fullscreen_actions.toggle-show-slices"),
    "toggle-show-comments": _$$t("fullscreen_actions.toggle-show-comments"),
    "toggle-show-annotations": _$$t("fullscreen_actions.toggle-show-annotations"),
    "toggle-always-expand-annotations": _$$t("fullscreen_actions.toggle-always-expand-annotations"),
    "toggle-shown-for-selected-nodes": _$$t("fullscreen_actions.toggle-shown-for-selected-nodes"),
    "toggle-shown-layout-grids": _$$t("fullscreen_actions.toggle-shown-layout-guides"),
    "toggle-sidebar": _$$t("fullscreen_actions.toggle-sidebar"),
    "toggle-smart-quotes": _$$t("fullscreen_actions.toggle-smart-quotes"),
    "toggle-smart-text-substitution": _$$t("fullscreen_actions.toggle-smart-text-substitution"),
    "toggle-snapping-to-geometry": _$$t("fullscreen_actions.toggle-snapping-to-geometry"),
    "toggle-snapping-to-objects": _$$t("fullscreen_actions.toggle-snapping-to-objects"),
    "toggle-snapping-to-pixels": _$$t("fullscreen_actions.toggle-snapping-to-pixels"),
    "toggle-prototyping-information": _$$t("fullscreen_actions.toggle-prototyping-information"),
    "single-properties-panel": _$$t("fullscreen_actions.single-properties-panel"),
    "toggle-snapping-to-dots": _$$t("fullscreen_actions.toggle-snapping-to-dots"),
    "toggle-show-dot-grid": _$$t("fullscreen_actions.toggle-show-dot-grid"),
    "toggle-sticky-tools": _$$t("fullscreen_actions.toggle-sticky-tools"),
    "toggle-ctrl-click-context-menu": _$$t("fullscreen_actions.toggle-ctrl-click-context-menu"),
    "disable-pinch-zoom-fix": _$$t("fullscreen_actions.disable-pinch-zoom-fix"),
    "toggle-ui": _$$t("fullscreen_actions.toggle-ui"),
    "debug-inspect-layer-figma-scope": _$$t("fullscreen_actions.debug-inspect-layer-figma-scope"),
    "debug-toggle-show-canvas-axis": _$$t("fullscreen_actions.debug-toggle-show-canvas-axis"),
    "debug-toggle-show-mouse-position": _$$t("fullscreen_actions.debug-toggle-show-mouse-position"),
    "debug-toggle-whiteboard-pdf-import-node-replacement": _$$t("fullscreen_actions.debug-toggle-whiteboard-pdf-import-node-replacement"),
    "debug-toggle-show-vector-network-labels": _$$t("fullscreen_actions.debug-toggle-show-vector-network-labels"),
    "toggle-undo-redo-debug": _$$t("fullscreen_actions.toggle-undo-redo-debug"),
    "toggle-collaborative-text-debug": _$$t("fullscreen_actions.toggle-collaborative-text-debug"),
    "toggle-use-numbers-for-opacity": _$$t("fullscreen_actions.toggle-use-numbers-for-opacity"),
    "toggle-use-old-outline-shortcuts": _$$t("fullscreen_actions.toggle-use-old-outline-shortcuts"),
    "toggle-text-suggestions-preference": _$$t("fullscreen_actions.show-text-suggestions"),
    "toggle-verbose-tooltips": "Show verbose tooltips",
    "toggle-viewport-overlay-hiding": _$$t("fullscreen_actions.toggle-viewport-overlay-hiding"),
    "toolbar-place-image": _$$t("fullscreen_actions.click_or_drag_to_place"),
    "troubleshooting-menu": _$$t("fullscreen_actions.troubleshooting"),
    undo: _$$t("fullscreen_actions.undo"),
    "ungroup-selection": _$$t("fullscreen_actions.ungroup-selection"),
    "unhide-all": _$$t("fullscreen_actions.unhide-all"),
    "unlock-all": _$$t("fullscreen_actions.unlock-all"),
    "update-instance-layout-version": _$$t("fullscreen_actions.update-instance-layout-version"),
    "update-via-instance-swap": _$$t("fullscreen_actions.update-via-instance-swap"),
    "vector-menu": _$$t("fullscreen_actions.vector-menu"),
    "savepoint-edit": _$$t("collaboration.feedback.context_menu.edit_version_info"),
    "savepoint-label": _$$t("collaboration.feedback.context_menu.name_this_version"),
    "savepoint-restore": _$$t("collaboration.feedback.context_menu.restore_this_version"),
    "savepoint-link": _$$t("collaboration.feedback.context_menu.copy_link"),
    "savepoint-duplicate": _$$t("collaboration.feedback.context_menu.duplicate"),
    "savepoint-clear": _$$t("collaboration.feedback.context_menu.delete_version_info"),
    "savepoint-compare": _$$t("collaboration.feedback.context_menu.compare_version"),
    "savepoint-undo-merge": _$$t("collaboration.feedback.context_menu.undo_merge"),
    "show-ui-hints-in-toolbar": _$$t("fullscreen_actions.show_ui_hints_in_toolbar"),
    "swap-instance": _$$t("fullscreen_actions.swap_component_instance"),
    variant: "Variant",
    "view-menu": _$$t("fullscreen_actions.view-menu"),
    "view-widget-details": _$$t("fullscreen_actions.view-widget-details"),
    "widgets-menu": _$$t("fullscreen_actions.widgets-menu"),
    "widgets-menu-manage-development": _$$t("fullscreen_actions.manage_widgets_in_development"),
    "widgets-menu-item": "#{widget_name}",
    "widgets-menu-dev-import-from-manifest": _$$t("whiteboard.inserts.widget_development_options_import_widget"),
    "widgets-menu-show-error": `Show error details\u2026`,
    "widgets-menu-manifest-issue": `\u26A0 Manifest issue`,
    "widgets-menu-dev-create-new": _$$t("whiteboard.inserts.widget_development_options_new_widget"),
    "widgets-menu-view-only": "Unavailable in view-only",
    "wheel-react": _$$t("fullscreen_actions.wheel-react"),
    "wheel-stamp": _$$t("fullscreen_actions.wheel-stamp"),
    "stamp-or-reaction-wheel": _$$t("fullscreen_actions.stamp_or_reaction_wheel"),
    "while-clicking": _$$t("fullscreen_actions.while_clicking"),
    "while-dragging-to-select": _$$t("fullscreen_actions.while_dragging_to_select"),
    "while-editing-shape": _$$t("fullscreen_actions.while_editing_a_shape"),
    "while-editing-shape-or-sticky": _$$t("fullscreen_actions.while_editing_shape_or_sticky"),
    "while-stamping": _$$t("fullscreen_actions.while_stamping"),
    "while-inserting-a-component": _$$t("fullscreen_actions.while_inserting_a_component"),
    "while-moving": _$$t("fullscreen_actions.while_moving"),
    "while-pointing": _$$t("fullscreen_actions.while_pointing"),
    "while-resizing": _$$t("fullscreen_actions.while_resizing"),
    "while-text-shape-or-sticky-selected": _$$t("fullscreen_actions.while_text_shape_or_sticky_selected"),
    "whiteboard-overflow-menu": _$$t("fullscreen_actions.collaborate"),
    "whiteboard-generate-content": _$$t("fullscreen_actions.whiteboard-generate-content"),
    "mind-map-generate-ideas": _$$t("fullscreen_actions.mind-map-generate-ideas"),
    "sort-stickies-by-topic": _$$t("fullscreen_actions.sort-stickies-by-topic"),
    "sort-stickies-by-color": _$$t("fullscreen_actions.sort-stickies-by-color"),
    "sort-stickies-by-author": _$$t("fullscreen_actions.sort-stickies-by-author"),
    "sort-stickies-by-stamp-count": _$$t("fullscreen_actions.sort-stickies-by-stamp-count"),
    "sort-stickies-by-stamp-type": _$$t("fullscreen_actions.sort-stickies-by-stamp-type"),
    "summarize-stickies": _$$t("fullscreen_actions.summarize-stickies"),
    "zoom-in": _$$t("fullscreen_actions.zoom-in"),
    "zoom-out": _$$t("fullscreen_actions.zoom-out"),
    "zoom-reset": _$$t("fullscreen_actions.zoom-reset"),
    "zoom-to-fit": _$$t("fullscreen_actions.zoom-to-fit"),
    "zoom-to-selection": _$$t("fullscreen_actions.zoom-to-selection"),
    "outline-mode": _$$t("fullscreen_actions.outlines-menu"),
    "toggle-outline-mode-hidden-layers": _$$t("fullscreen_actions.outline-mode-hidden-layers"),
    "toggle-outline-mode-object-bounds": _$$t("fullscreen_actions.outline-mode-object-bounds"),
    "toggle-outline-mode-hidden-layers-qc": _$$t("fullscreen_actions.outline-mode-hidden-layers-qc"),
    "toggle-outline-mode-object-bounds-qc": _$$t("fullscreen_actions.outline-mode-object-bounds-qc"),
    "record-macro-start": "Record actions",
    "change-document-color-profile-to-display-p3": _$$t("fullscreen_actions.color-profile-set-display-p3"),
    "change-document-color-profile-to-display-p3-quick-action": _$$t("fullscreen_actions.color-profile-set-display-p3.quick-action"),
    "change-document-color-profile-to-srgb": _$$t("fullscreen_actions.color-profile-set-srgb"),
    "change-document-color-profile-to-srgb-quick-action": _$$t("fullscreen_actions.color-profile-set-srgb.quick_action"),
    "assign-document-color-profile-legacy": _$$t("fullscreen_actions.color-profile-assign-legacy"),
    "assign-document-color-profile-legacy-quick-action": _$$t("fullscreen_actions.color-profile-assign-legacy.quick_action"),
    "ready-status-copy-dev-link": _$$t("dev_handoff.status.copy_dev_link"),
    "enter-dev-mode-focus-view": _$$t("dev_handoff.status.show_in_focus"),
    "ready-status-open-in-dev-mode": _$$t("dev_handoff.status.open_in_dev_mode"),
    "completed-status-remark-as-ready": _$$t("dev_handoff.status.remark_as_ready"),
    "status-copy-focus-link": _$$t("dev_handoff.status.copy_focus_link"),
    "status-mark-as-completed": _$$t("dev_handoff.status.mark_as_completed"),
    "status-mark-as-ready": _$$t("dev_handoff.status.mark_as_ready"),
    "status-remove": _$$t("dev_handoff.status.remove"),
    "view-annotations": _$$t("dev_handoff.annotation.view_annotations"),
    "find-inspiration": getFeatureFlags().fragment_search_tweaks ? _$$t("fullscreen_actions.find-inspiration-compact") : _$$t("fullscreen_actions.find-inspiration"),
    "find-inspiration-quick-command": _$$t("fullscreen_actions.quick_actions.find-inspiration-with-selection-vague"),
    "find-codebase-suggestions": _$$t("fullscreen_actions.find-codebase-suggestions"),
    "inspect-fragment": _$$t("fullscreen_actions.inspect-fragment"),
    "debug-toggle-diagram-layout-paused": "Toggle diagram layout paused",
    "debug-magic-link-ai-model": "Debug Magic Link AI model",
    "missing-plugin": _$$t("fullscreen_actions.missing-plugin", {
      pluginCommand: "#{pluginCommand}",
      pluginName: "#{pluginName}"
    }),
    "check-network-compatibility": _$$t("check_network_compatibility.dropdown_title"),
    "find-files-matching": _$$t("fullscreen_actions.quick_actions.find-files-matching", {
      searchQuery: "#{searchQuery}"
    }),
    "find-community-matching": _$$t("fullscreen_actions.quick_actions.find-community-matching", {
      searchQuery: "#{searchQuery}"
    }),
    "find-assets-and-community-matching": _$$t("fullscreen_actions.quick_actions.find-at-plan-file-and-community", {
      searchQuery: "#{searchQuery}",
      planFileName: "#{planFileName}"
    }),
    "go-to-page": _$$t("fullscreen_actions.quick_actions.go-to-page", {
      pageName: "#{pageName}"
    }),
    "find-components-matching": _$$t("fullscreen_actions.quick_actions.find-components-matching", {
      searchQuery: "#{searchQuery}"
    }),
    "find-extensions-matching": _$$t("fullscreen_actions.quick_actions.find-extensions-matching", {
      searchQuery: "#{searchQuery}"
    }),
    "find-assets-matching": _$$t("fullscreen_actions.quick_actions.find-assets-matching", {
      searchQuery: "#{searchQuery}"
    }),
    "find-in-community": _$$t("fullscreen_actions.quick_actions.find-in-community", {
      searchQuery: "#{searchQuery}"
    }),
    "find-at-plan-file": _$$t("fullscreen_actions.quick_actions.find-at-plan-file", {
      searchQuery: "#{searchQuery}",
      planFileName: "#{planFileName}"
    }),
    "find-components": _$$t("fullscreen_actions.quick_actions.find-components", {
      searchQuery: "#{searchQuery}"
    }),
    "find-plugins-widgets": _$$t("fullscreen_actions.quick_actions.find-plugins-widgets", {
      searchQuery: "#{searchQuery}"
    }),
    "link-to-component": _$$t("fullscreen_actions.quick_actions.link-to-component"),
    "translate-text": _$$t("fullscreen_actions.quick_actions.translate-text"),
    "rewrite-text": _$$t("fullscreen_actions.quick_actions.rewrite-this"),
    "shorten-text": _$$t("fullscreen_actions.quick_actions.shorten-text"),
    "content-fill": _$$t("fullscreen_actions.ai_content_fill.replace_content"),
    "remove-background": _$$t("fullscreen_actions.remove_background"),
    "upscale-image": _$$t("fullscreen_actions.upscale_image"),
    "generate-image": _$$t("fullscreen.properties_panel.make_a_picture"),
    "edit-image": _$$t("fullscreen_actions.edit_image"),
    "make-video": _$$t("fullscreen_actions.make_video"),
    "auto-rename-layers": _$$t("fullscreen_actions.quick_actions.name-all-layers"),
    "detect-violations": _$$t("fullscreen_actions.quick_actions.detect-violations"),
    "magic-link": _$$t("fullscreen_actions.quick_actions.add-interactions-v2"),
    "first-draft": _$$t("fullscreen_actions.quick_actions.first-draft-relaunch"),
    "first-draft-make-changes": _$$t("fullscreen_actions.quick_actions.first-draft-make-changes"),
    "first-draft-make-kit": _$$t("fullscreen_actions.quick_actions.first-draft-make-kit"),
    "first-draft-make-kit-debug": _$$t("fullscreen_actions.quick_actions.first-draft-make-kit-debug"),
    "first-draft-linting": _$$t("fullscreen_actions.quick_actions.first-draft-linting"),
    "first-draft-debug": _$$t("fullscreen_actions.quick_actions.first-draft-debug"),
    "make-edits": _$$t("fullscreen_actions.quick_actions.make-edits"),
    "make-edits-debug": _$$t("fullscreen_actions.make-edits-debug"),
    "make-edits-debug-review": _$$t("fullscreen_actions.make_edits_debug_review"),
    "first-draft-fine-tune": _$$t("fullscreen_actions.quick_actions.first-draft-fine-tune"),
    "image-to-design": _$$t("fullscreen_actions.image-to-design"),
    "image-to-design-oracle": _$$t("fullscreen_actions.image-to-design-oracle"),
    "toggle-code-connect-debug-tools": "Toggle Code Connect Debug Tools",
    "request-to-edit": _$$t("fullscreen.toolbar.request.ask_to_edit"),
    "slides-edit-theme-color": _$$t("slides.properties_panel.color_picker.edit_template_color"),
    "slides-delete-theme-color": _$$t("slides.properties_panel.color_picker.delete_template_color"),
    "slides-move-to-theme-colors": _$$t("slides.properties_panel.color_picker.move_to_template_colors"),
    "slides-delete-object-animation": _$$t("slides.properties_panel.object_animations.delete"),
    "slides-merge-object-animation-with-above": _$$t("slides.properties_panel.object_animations.merge_with_step_above"),
    "slides-merge-object-animation-with-below": _$$t("slides.properties_panel.object_animations.merge_with_step_below"),
    "slides-separate-object-animation": _$$t("slides.properties_panel.object_animations.separate_into_new_step"),
    "dakota-export-collection-internal": _$$t("dakota.collections_context_menu.export_internal"),
    "dakota-delete-collection": _$$t("dakota.collections_context_menu.delete"),
    "dakota-duplicate-field": _$$t("dakota.field_context_menu.duplicate"),
    "dakota-delete-field": _$$t("dakota.field_context_menu.delete"),
    "dakota-delete-item": _$$t("dakota.item_context_menu.delete"),
    "add-platform-shape-definition": _$$t("fullscreen_actions.add-platform-shape-definition"),
    "remove-platform-shape-definition": _$$t("fullscreen_actions.remove-platform-shape-definition"),
    "skip-slide": _$$t("fullscreen_actions.skip-slide"),
    "unskip-slide": _$$t("fullscreen_actions.unskip-slide"),
    "skip-slides": _$$t("fullscreen_actions.skip-slides"),
    "unskip-slides": _$$t("fullscreen_actions.unskip-slides"),
    "add-slide-object-animation": _$$t("fullscreen_actions.add-slide-object-animation"),
    "assistant-chat": _$$t("fullscreen_actions.assistant-chat"),
    "assistant-chat-query": _$$t("fullscreen_actions.assistant-chat-query", {
      query: "#{searchQuery}"
    }),
    "debug-toggle-cooper-mode": "Debug Toggle Cooper Editor Type",
    "cooper-delete-frame": _$$t("cooper.left_panel.context_menu.delete"),
    "edit-code": _$$t("fullscreen_actions.edit-code"),
    "create-code-layer-from-design": _$$t("fullscreen_actions.create-code-layer-from-design"),
    "create-code-layer-from-design-disabled": _$$t("fullscreen_actions.create-code-layer-from-design-disabled"),
    "create-make-from-design": _$$t("fullscreen_actions.create-make-from-design"),
    "bulk-export-design-to-react": _$$t("fullscreen_actions.bulk-export-design-to-react"),
    "restore-design-in-place-from-code": _$$t("fullscreen_actions.restore-design-in-place-from-code"),
    "copy-out-design-from-code": _$$t("fullscreen_actions.copy-out-design-from-code"),
    "delete-code-file": _$$t("sites.code-components-context-menu.delete-code-file"),
    "delete-code-layer": _$$t("sites.code-components-context-menu.delete-code-layer"),
    "delete-code-interaction": _$$t("sites.code-components-context-menu.delete-code-interaction"),
    "fire-several-visual-bells": "Fire several visual bells",
    "toggle-visible-canvas-inputs": "Toggle visibility of canvas text inputs",
    "open-shapes-sidebar": _$$t("whiteboard.shapes_sidebar.open_sidebar"),
    "throw-frontend-error": "Throw uncaught frontend error",
    "toggle-show-feature-flag-bisector": _$$t("fullscreen_actions.toggle-debug-feature-flag-bisector"),
    "mermaid-to-diagram": _$$t("fullscreen_actions.mermaid-to-diagram"),
    "send-to-make-from-design": _$$t("fullscreen_actions.send-to-make-from-design"),
    "send-to-buzz-from-design": _$$t("buzz.send_from_design.send_to_figma_buzz"),
    "send-selection-to-buzz-from-design": _$$t("buzz.send_from_design.send_to_figma_buzz"),
    "change-tag": _$$t("fullscreen_actions.sites_change_semantic_tag")
  });
  let i = n[e];
  "function" == typeof i && (i = i(t));
  i && "string" == typeof i || (console.warn(`Fullscreen_strings missing for key: ${e}`), i = "");
  t && (i = i.replace(/#\{(\w+)\}/g, (e, i) => t[i] ? t[i] : ""));
  return i;
}
export const A = $$l0;