var $$n0 = (e => (e.TO_SOURCE = "to_source", e.FROM_SOURCE = "from_source", e))($$n0 || {});
var $$r2 = (e => (e.ON_MERGE = "on_merge", e.UNHANDLED = "unhandled", e.CPP = "cpp", e.MODAL = "modal", e))($$r2 || {});
var $$a4 = (e => (e.TOTAL = "total", e.GRANULAR = "granular", e))($$a4 || {});
var $$s1 = (e => (e.CPP_ONLY = "cpp_only", e.JAVACRIPT_ONLY = "js_only", e))($$s1 || {});
var $$o5 = (e => (e.SUMMARY = "summary", e.DETAIL = "detail", e.COMPARE_THUMBNAIL = "compare_thumbnail", e))($$o5 || {});
var $$l3 = (e => (e.MAIN = "main", e.BRANCH = "branch", e))($$l3 || {});
export const Kn = $$n0;
export const NQ = $$s1;
export const PW = $$r2;
export const Wo = $$l3;
export const ap = $$a4;
export const mg = $$o5;