import { parsePxNumber } from "../figma_app/783094";
import { ZGX } from "../figma_app/27776";
let $$a4 = "VariableDetailModal";
let $$s3 = "MatchingVariablesModal";
let $$o7 = "StyleDetailModal";
let $$l6 = parsePxNumber(ZGX);
let $$d5 = 343;
let $$c1 = 272;
let $$u8 = 4;
let $$p9 = 360;
var $$m0 = ((e) => (e.CodeWell = "code", e.Properties = "properties", e.FullTable = "full_table", e))($$m0 || {});
var $$h2 = ((e) => (e.InspectNoSelection = "inspect_no_selection", e.VariableDetailsModal = "variable_details_modal", e.DirectUrl = "direct_url", e))($$h2 || {});
export const E6 = $$m0;
export const Gw = $$c1;
export const Nh = $$h2;
export const W8 = $$s3;
export const WP = $$a4;
export const b6 = $$d5;
export const iB = $$l6;
export const vl = $$o7;
export const wR = $$u8;
export const xX = $$p9;
