let $$n0 = 'button__button__-U-QJ'
let $$r8 = 'button__icon__OodK0'
let $$a2 = 'button__buttonText__nvCyD'
let $$s1 = 'button__buttonContent__tVdQi'
let $$o15 = 'button__shortcut__OKjxS'
let $$l13 = 'button__regularSize__a-pyp'
let $$d9 = 'button__largeSize__Xuk-e'
let $$c17 = 'button__wideSize__fyONU'
let $$u7 = 'button__hasIcon__Z33Hl'
let $$p10 = 'button__largeWideSize__-YVn9'
let $$m14 = 'button__secondary__8YIhr'
let $$h5 = 'button__destructiveSecondary__dJTw3'
let $$g12 = 'button__primary__tP7NU'
let $$f3 = 'button__destructive__EwVR5'
let $$_16 = 'button__signup__O-43y'
let $$A6 = 'button__ghost__0pJzW'
let $$y11 = 'button__link__5iZjR'
let $$b4 = 'button__destructiveLink__oQbdL'
export const button = $$n0
export const buttonContent = $$s1
export const buttonText = $$a2
export const destructive = $$f3
export const destructiveLink = $$b4
export const destructiveSecondary = $$h5
export const ghost = $$A6
export const hasIcon = $$u7
export const icon = $$r8
export const largeSize = $$d9
export const largeWideSize = $$p10
export const link = $$y11
export const primary = $$g12
export const regularSize = $$l13
export const secondary = $$m14
export const shortcut = $$o15
export const signup = $$_16
export const wideSize = $$c17
