let $$n1 = 'form__label__BD7QK'
let $$r3 = 'form__primary__oNz7D'
let $$a4 = 'form__secondary__EB-qH'
let $$s0 = 'form__description__34H0g'
let $$o2 = 'form__legend__EIZxi'
export const description = $$s0
export const label = $$n1
export const legend = $$o2
export const primary = $$r3
export const secondary = $$a4
