var $$n6 = (e => (e.ORG_VIEW = "org_view", e.ORG_EDIT = "org_edit", e.VIEW = "view", e.EDIT = "edit", e.INHERIT = "inherit", e))($$n6 || {});
var r = (e => (e.ORG_VIEW = "org_view", e.VIEW = "view", e.INHERIT = "inherit", e))(r || {});
var $$a10 = (e => (e.PUBLIC = "public", e.PRIVATE = "private", e.SECRET = "secret", e))($$a10 || {});
var s = (e => (e.AUTO_APPROVE = "auto_approve", e.AUTO_APPROVE_WITH_SURPLUS_SEATS = "auto_approve_with_surplus_seats", e.ADMIN_APPROVAL = "admin_approval", e))(s || {});
var $$o12 = (e => (e.ADMIN = "admin", e.MEMBER = "member", e.GUEST = "guest", e))($$o12 || {});
var $$l3 = (e => (e.ADMIN = "admin", e.MEMBER = "member", e.GUEST = "guest", e))($$l3 || {});
var $$d0 = (e => (e.STARTER = "starter", e.STUDENT = "student", e.PRO = "pro", e.ORG = "org", e.ENTERPRISE = "enterprise", e))($$d0 || {});
var c = (e => (e.INCOMPLETE = "incomplete", e.ACTIVE = "active", e.UNPAID = "unpaid", e.SUSPENDED = "suspended", e.SUSPENDED_MONTHLY_SUB_EDITOR_COUNT_EXCEEDED = "suspended_monthly_sub_editor_count_exceeded", e.DEACTIVATED = "deactivated", e))(c || {});
var $$u1 = (e => (e.STARTER = "starter", e.FULL = "full", e.RESTRICTED = "restricted", e))($$u1 || {});
var $$p7 = (e => (e.ALLOWED = "allowed", e.MEMBERS_ONLY = "members_only", e.BANNED = "banned", e))($$p7 || {});
var m = (e => (e.MEMBERS = "members", e.ALL_USERS = "all_users", e))(m || {});
var $$h9 = (e => (e.DESIGN = "design", e.WHITEBOARD = "whiteboard", e.SLIDES = "slides", e.SITES = "sites", e.COOPER = "cooper", e.FIGMAKE = "figmake", e))($$h9 || {});
var $$g4 = (e => (e.DESIGN = "design", e.WHITEBOARD = "whiteboard", e.DEV_MODE = "dev_mode", e.SLIDES = "slides", e.SITES = "sites", e.FIGMAKE = "figmake", e.COOPER = "cooper", e))($$g4 || {});
var $$f14 = (e => (e.CANVAS = "canvas", e.PROTOTYPE = "prototype", e.WHITEBOARD = "whiteboard", e.LIBRARY = "library", e.SLIDE_TEMPLATE = "slide_template", e.SITE_TEMPLATE = "site_template", e.COOPER_TEMPLATE_FILE = "cooper_template_file", e.FIGMAKE_TEMPLATE = "figmake_template", e))($$f14 || {});
var $$_11 = (e => (e.ORG = "org", e.TEAM = "team", e.COMMUNITY = "community", e))($$_11 || {});
var A = (e => (e.ALLOW_TEMPLATES = "ALLOW", e.DISABLE_TEMPLATES = "DISABLE", e))(A || {});
var y = (e => (e.VIEW = "view", e.EDIT = "edit", e))(y || {});
var $$b5 = (e => (e.FOLDER = "folder", e))($$b5 || {});
var v = (e => (e.COLLABORATOR = "collaborator", e.DEVELOPER = "developer", e.EXPERT = "expert", e.CONTENT = "content", e))(v || {});
var $$I8 = (e => (e.APPROVED_PUBLIC = "approved_public", e.BLOCKED = "blocked", e.DELISTED = "delisted", e.DELISTED_CREATOR_STRIPE_DISABLED = "delisted_creator_stripe_disabled", e.ORG_PRIVATE = "org_private", e.ORG_PRIVATE_PENDING_PUBLIC = "org_private_pending_public", e.PENDING_PUBLIC = "pending_public", e.PENDING_USER_VISUAL_COMPLIANCE = "pending_user_visual_compliance", e))($$I8 || {});
var $$E13 = (e => (e.DESIGN_TEMPLATE = "design_template", e.FIGJAM_TEMPLATE = "figjam_template", e.PLUGIN = "plugin", e.WIDGET = "widget", e.UI_KIT = "ui_kit", e.SLIDE_TEMPLATE = "slide_template", e.PROTOTYPE = "prototype", e.SITE_TEMPLATE = "site_template", e.COOPER_TEMPLATE_FILE = "cooper_template_file", e.COOPER_TEMPLATE_ASSET = "cooper_template_asset", e.FIGMAKE_TEMPLATE = "figmake_template", e))($$E13 || {});
var x = (e => (e.ORG = "Org", e.WORKSPACE = "Workspace", e))(x || {});
var $$S2 = (e => (e.GUESTS = "guests", e.MEMBERS = "members", e.ALL_USERS = "all_users", e))($$S2 || {});
export const Ag = $$d0;
export const CO = $$u1;
export const CT = $$S2;
export const En = $$l3;
export const G_ = $$g4;
export const Go = $$b5;
export const PQ = $$n6;
export const RR = $$p7;
export const _B = $$I8;
export const _Y = $$h9;
export const bU = $$a10;
export const iY = $$_11;
export const vK = $$o12;
export const vt = $$E13;
export const y4 = $$f14;