import { atom } from "../figma_app/27355";
import { Wh } from "../figma_app/615482";
let $$a0 = Wh(() => atom(null));
let $$s2 = Wh(() => atom(null));
let $$o1 = Wh(() => atom(null));
let $$l3 = Wh(() => atom(""));
export const LQ = $$a0;
export const MX = $$o1;
export const h1 = $$s2;
export const wm = $$l3;