import { atom } from "../figma_app/27355";
import { setupRemovableAtomFamily } from "../figma_app/615482";
let $$a0 = setupRemovableAtomFamily(() => atom(null));
let $$s2 = setupRemovableAtomFamily(() => atom(null));
let $$o1 = setupRemovableAtomFamily(() => atom(null));
let $$l3 = setupRemovableAtomFamily(() => atom(""));
export const LQ = $$a0;
export const MX = $$o1;
export const h1 = $$s2;
export const wm = $$l3;