let $$n1 = "dialog-trigger-button__ghost__OrMww"
let $$r4 = "dialog-trigger-button__secondary__w-GC7"
let $$a0 = "dialog-trigger-button__dialogTriggerButton__bjzvt base-icon-button__baseIconButton__TXKzr"
let $$s3 = "dialog-trigger-button__lg__yHNjf"
let $$o2 = "dialog-trigger-button__icon__G9c8f base-icon-button__icon__FIIFq"
export const dialogTriggerButton = $$a0
export const ghost = $$n1
export const icon = $$o2
export const lg = $$s3
export const secondary = $$r4
