var $$n4 = (e => (e.SIGN_UP = "sign_up", e.SIGN_IN = "sign_in", e.SAML_START = "saml_start", e.CHECK_EMAIL_MAGIC_LINK_SIGN_IN_AFTER_PASSWORD = "check_email_magic_link_sign_in_after_password", e.FORGOT_PASSWORD = "forgot_password", e.RESET_PASSWORD = "reset_password", e.SENT_PASSWORD_RESET = "sent_password_reset", e.VALIDATE_EMAIL = "validate_email", e.VALIDATE_CODE = "validate_code", e.APP_AUTH_GRANT = "app_auth_grant", e.APP_AUTH_REDEEM = "app_auth_redeem", e.SSO_GATE = "sso_gate", e.EMAIL_ONLY = "email_only", e.ACCOUNT_PICKER = "account_picker", e.JOIN_ORG = "join_org", e.VERIFY_HUMAN = "verify_human", e.GOOGLE_SSO_SIGNUP_ACTION_REDIRECT = "google_sso_signup_action_redirect", e.TWO_FACTOR = "two_factor", e))($$n4 || {});
var $$r0 = (e => (e[e.UNAUTHORIZED = 0] = "UNAUTHORIZED", e[e.BAD_REQUEST = 1] = "BAD_REQUEST", e[e.NO_SAML = 2] = "NO_SAML", e[e.SAML_REQUIRED = 3] = "SAML_REQUIRED", e[e.MAGIC_LINK_LOGIN_NO_ACCOUNT = 4] = "MAGIC_LINK_LOGIN_NO_ACCOUNT", e))($$r0 || {});
var $$a2 = (e => (e.EMAIL = "email", e.PASSWORD = "password", e.VERIFICATION_CODE = "verification_code", e.TOTP_KEY = "totp_key", e.JOB_TITLE = "job_title", e.USAGE_PURPOSE = "usage_purpose", e))($$a2 || {});
var s = (e => (e.WORK = "For work", e.PERSONAL = "For personal use", e.EDU = "For teaching or taking a class", e))(s || {});
var $$o5 = (e => (e.GOOGLE = "google", e.SAML = "saml", e))($$o5 || {});
var $$l1 = (e => (e.DESKTOP = "desktop", e.MIRROR = "mirror", e.MOBILE = "mobile", e.VSCODE = "vscode", e.VSCODE_INSIDERS = "vscode-insiders", e.VSCODE_CURSOR = "vscode-cursor", e.FIGJAM_MOBILE = "figjam_mobile", e.MSFT_TEAMS = "msft-teams", e))($$l1 || {});
export let $$d6 = "signed_up_from_open_sessions";
export var $$c3 = (e => (e.SIGN_UP = "sign_up", e.SIGN_UP_GOOGLE_ONE_TAP = "sign_up_google_one_tap", e.FORGOT_PASSWORD = "forgot_password", e))($$c3 || {});
export const By = $$r0;
export const DP = $$l1;
export const RE = $$a2;
export const cc = $$c3;
export const qB = $$n4;
export const vR = $$o5;
export const zl = $$d6;