import { getFeatureFlags } from '../905/601108'
import { generateUUIDv4 } from '../905/871474'

enum RenderStrategy {
  RENDER_SINGLE_PROPERTY = 'RENDER_SINGLE_PROPERTY',
  RENDER_MULTI_PROPERTY = 'RENDER_MULTI_PROPERTY',
  RENDER_MULTI_NODE = 'RENDER_MULTI_NODE',
  RENDER_DISPLAY_NODE_SINGLE_PROPERTY = 'RENDER_DISPLAY_NODE_SINGLE_PROPERTY',

}

enum ReviewPhase {
  MERGE_REVIEW = 0,
  CONFLICT_REVIEW = 1,
}

let visualAttributes = {
  derivedTextData: !1,
  name: !0,
  visible: !0,
  locked: !0,
  lockMode: !0,
  parentIndex: !0,
  transform: !0,
  description: !0,
  symbolDescription: !0,
  symbolLinks: !0,
  type: !0,
  booleanOperation: !0,
  horizontalConstraint: !0,
  verticalConstraint: !0,
  hyperlink: !0,
  mention: !0,
  proportionsConstrained: !0,
  targetAspectRatio: !0,
  layoutGrids: !0,
  inheritGridStyleID: !1,
  inheritTextStyleID: !1,
  inheritFillStyleID: !1,
  inheritFillStyleIDForStroke: !1,
  inheritEffectStyleID: !1,
  inheritExportStyleID: !1,
  inheritStrokeStyleID: !1,
  styleIdForFill: !0,
  styleIdForStrokeFill: !0,
  styleIdForText: !0,
  styleIdForEffect: !0,
  styleIdForGrid: !0,
  scrollBehavior: !0,
  transitionType: !0,
  transitionDuration: !0,
  easingType: !0,
  scrollDirection: !0,
  transitionPreserveScroll: !0,
  connectionType: !0,
  interactionType: !0,
  transitionTimeout: !0,
  interactionMaintained: !0,
  interactionDuration: !0,
  overlayPositionType: !0,
  transitionShouldSmartAnimate: !0,
  overlayRelativePosition: !0,
  overlayBackgroundInteraction: !0,
  overlayBackgroundAppearance: !0,
  keyTrigger: !0,
  prototypeInteractions: !0,
  prototypeStartNodeID: !0,
  prototypeStartingPoint: !0,
  videoPlayback: !0,
  stackMode: !0,
  stackSpacing: !0,
  stackCounterSizing: !0,
  stackPrimarySizing: !0,
  stackChildPrimaryGrow: !0,
  stackChildAlignSelf: !0,
  stackPrimaryAlignItems: !0,
  stackCounterAlignItems: !0,
  stackHorizontalPadding: !0,
  stackVerticalPadding: !0,
  stackPaddingRight: !0,
  stackPaddingBottom: !0,
  stackPositioning: !0,
  stackReverseZIndex: !0,
  bordersTakeSpace: !0,
  stackWrap: !0,
  stackCounterSpacing: !0,
  stackCounterAlignContent: !0,
  gridRows: !1,
  gridColumns: !1,
  gridRowGap: !1,
  gridColumnGap: !1,
  gridRowAnchor: !1,
  gridColumnAnchor: !1,
  gridRowSpan: !1,
  gridColumnSpan: !1,
  gridRowsSizing: !1,
  gridColumnsSizing: !1,
  gridChildHorizontalAlign: !1,
  gridChildVerticalAlign: !1,
  minSize: !0,
  maxSize: !0,
  maxLines: !0,
  pluginData: !0,
  pluginRelaunchData: !0,
  stackPadding: !1,
  stackJustify: !1,
  codeBlockLanguage: !0,
  codeBlockTheme: !1,
  fontVariations: !0,
  detachOpticalSizeFromFontSize: !0,
  widgetMetadata: !0,
  widgetPropertyMenuItems: !0,
  widgetSyncedState: !0,
  renderedSyncedState: !0,
  widgetEvents: !1,
  widgetInputBehavior: !1,
  widgetCachedAncestor: !0,
  widgetInputTextNodeType: !1,
  interactiveSlideConfigData: !1,
  interactiveSlideParticipantData: !1,
  flappType: !1,
  isEmbeddedPrototype: !1,
  themeID: !1,
  slideThemeMap: !1,
  slideTemplateFileKey: !1,
  slideNumber: !1,
  slideNumberSeparator: !1,
  componentPropDefs: !0,
  componentPropRefs: !0,
  componentPropAssignments: !1,
  simplifyInstancePanels: !0,
  propsAreBubbled: !0,
  size: !1,
  guid: !1,
  phase: !0,
  opacity: !1,
  blendMode: !1,
  count: !1,
  dashPattern: !1,
  autoRename: !1,
  backgroundEnabled: !1,
  mask: !1,
  maskType: !1,
  exportContentsOnly: !1,
  maskIsOutline: !1,
  backgroundOpacity: !1,
  cornerRadius: !1,
  fontSize: !1,
  paragraphIndent: !1,
  paragraphSpacing: !1,
  listSpacing: !1,
  starInnerScale: !1,
  miterLimit: !1,
  strokeWeight: !1,
  textTracking: !1,
  strokeAlign: !1,
  strokeCap: !1,
  strokeCapSize: !1,
  strokeJoin: !1,
  textAlignHorizontal: !1,
  textAlignVertical: !1,
  textCase: !1,
  textDecoration: !1,
  textDecorationStyle: !1,
  textDecorationSkipInk: !1,
  textUnderlineOffset: !1,
  textDecorationThickness: !1,
  leadingTrim: !1,
  hangingPunctuation: !1,
  hangingList: !1,
  fillPaints: !1,
  strokePaints: !1,
  textDecorationFillPaints: !1,
  lineHeight: !1,
  fontName: !1,
  textData: !1,
  effects: !1,
  handleMirroring: !1,
  exportSettings: !1,
  textAutoResize: !1,
  vectorData: !1,
  styleID: !1,
  backgroundColor: !1,
  fillGeometry: !1,
  strokeGeometry: !1,
  guidPath: !1,
  symbolData: !1,
  frameMaskDisabled: !1,
  resizeToFit: !1,
  exportBackgroundDisabled: !1,
  sharedSymbolReference: !1,
  isSymbolPublishable: !1,
  sharedSymbolMappings: !1,
  derivedSymbolData: !1,
  sharedSymbolVersion: !1,
  overrideLevel: !1,
  nestedInstanceResizeEnabled: !1,
  fontVariantCommonLigatures: !1,
  fontVariantContextualLigatures: !1,
  fontVariantDiscretionaryLigatures: !1,
  fontVariantHistoricalLigatures: !1,
  fontVariantOrdinal: !1,
  fontVariantSlashedZero: !1,
  fontVariantNumericFigure: !1,
  fontVariantNumericSpacing: !1,
  fontVariantNumericFraction: !1,
  fontVariantCaps: !1,
  fontVariantPosition: !1,
  responsiveTextStyleVariants: !1,
  guides: !1,
  transitionNodeID: !1,
  prototypeBackgroundColor: !1,
  internalOnly: !1,
  overriddenSymbolID: !1,
  rectangleTopLeftCornerRadius: !1,
  rectangleTopRightCornerRadius: !1,
  rectangleBottomLeftCornerRadius: !1,
  rectangleBottomRightCornerRadius: !1,
  rectangleCornerRadiiIndependent: !1,
  rectangleCornerToolIndependent: !1,
  sharedComponentMasterData: !1,
  cornerSmoothing: !1,
  styleType: !1,
  styleDescription: !1,
  unflatteningMappings: !1,
  letterSpacing: !1,
  version: !1,
  userFacingVersion: !1,
  sharedStyleMasterData: !1,
  sharedStyleReference: !1,
  sortPosition: !1,
  isPublishable: !1,
  exportTextAsSVGText: !1,
  isSoftDeletedStyle: !1,
  isSoftDeleted: !1,
  isNonUpdateable: !1,
  isOverrideOverTextStyle: !1,
  connectionURL: !1,
  prototypeDevice: !1,
  backgroundPaints: !1,
  arcData: !1,
  derivedSymbolDataLayoutVersion: !1,
  navigationType: !1,
  fontVersion: !1,
  textUserLayoutVersion: !1,
  textExplicitLayoutVersion: !1,
  textBidiVersion: !1,
  toggledOnOTFeatures: !1,
  toggledOffOTFeatures: !1,
  overrideKey: !1,
  publishFile: !1,
  sourceLibraryKey: !1,
  publishID: !1,
  key: !1,
  componentKey: !1,
  isC2: !1,
  fileAssetIds: !1,
  publishedVersion: !1,
  containerSupportsFillStrokeAndCorners: !1,
  isStateGroup: !1,
  voiceEventPhrase: !1,
  forceUnflatteningMappings: !1,
  ancestorPathBeforeDeletion: !1,
  stateGroupPropertyValueOrders: !1,
  variantPropSpecs: !1,
  nodeGenerationData: !1,
  derivedImmutableFrameData: !1,
  derivedImmutableFrameDataVersion: !1,
  jsxData: !1,
  derivedJsxData: !1,
  stableKey: !1,
  shapeWithTextType: !1,
  connectorStart: !1,
  connectorEnd: !1,
  connectorLineStyle: !1,
  connectorStartCap: !1,
  connectorEndCap: !1,
  connectorType: !1,
  shapeUserHeight: !1,
  overrideStash: !1,
  internalEnumForTest: !1,
  internalDataForTest: !1,
  connectorControlPoints: !1,
  connectorBezierControlPoints: !1,
  connectorTextMidpoint: !1,
  annotations: !!getFeatureFlags().dt_annotations_branch_merge,
  measurements: !1,
  libraryMoveInfo: !1,
  libraryMoveHistory: !1,
  developerRelatedLinks: !1,
  stampData: !1,
  embedData: !1,
  linkPreviewData: !1,
  richMediaData: !1,
  textTruncation: !0,
  shapeTruncates: !1,
  sectionContentsHidden: !1,
  widgetTooltip: !1,
  borderTopWeight: !1,
  borderBottomWeight: !1,
  borderLeftWeight: !1,
  borderRightWeight: !1,
  borderStrokeWeightsIndependent: !1,
  widgetHoverStyle: !1,
  hasHadRTLText: !1,
  emojiImageSet: !1,
  slideThumbnailHash: !1,
  isWidgetStickable: !1,
  shouldHideCursorsOnWidgetHover: !1,
  variableDataValues: !1,
  variableConsumptionMap: !1,
  parameterConsumptionMap: !0,
  variableModeBySetMap: !1,
  variableSetModes: !1,
  variableSetID: !1,
  backingVariableSetId: !1,
  overriddenVariableId: !1,
  rootVariableKey: !1,
  variableResolvedType: !1,
  isCollectionExtendable: !1,
  variableScopes: !1,
  codeSyntax: !0,
  agendaPositionMap: !1,
  agendaMetadataMap: !1,
  migrationStatus: !1,
  editInfo: !1,
  documentColorProfile: !1,
  accessibleHTMLTag: !0,
  ariaAttributes: !0,
  accessibleLabel: !0,
  isDecorativeImage: !1,
  tableRowPositions: !1,
  tableColumnPositions: !1,
  tableRowHeights: !1,
  tableColumnWidths: !1,
  areSlidesManuallyIndented: !1,
  detachedSymbolId: !1,
  childReadingDirection: !1,
  readingIndex: !1,
  sectionStatusInfo: !0,
  handoffStatusMap: !0,
  slideActiveThemeLibKey: !1,
  slideSpeakerNotes: !1,
  isSkippedSlide: !1,
  diagramParentIndex: !1,
  diagramLayoutRuleType: !1,
  diagramLayoutPaused: !1,
  editScopeInfo: !1,
  sectionPresetInfo: !1,
  platformShapeDefinition: !1,
  semanticWeight: !1,
  semanticItalic: !1,
  isPageDivider: !1,
  moduleType: !1,
  pageType: !1,
  derivedBreakpointData: !1,
  breakpointMinWidth: !1,
  defaultResponsiveSetId: !1,
  responsiveSetSettings: !1,
  behaviors: !1,
  aiEditedNodeChangeFieldNumbers: !1,
  aiEditScopeLabel: !1,
  sortedMovingChildIndices: !1,
  firstDraftData: !1,
  firstDraftKitElementData: !1,
  sourceCode: !1,
  collaborativeSourceCode: !1,
  belongsToCodeLibraryId: !1,
  exportedFromCodeFileId: !1,
  backingCodeComponentId: !1,
  codeFilePath: !1,
  importedCodeFiles: !1,
  codeFileCanvasNodeId: !1,
  codeExportName: !1,
  chatMessages: !1,
  chatCompressionState: !1,
  codeChatMessagesKey: !1,
  aiChatThread: !1,
  cmsSelector: !1,
  cmsConsumptionMap: !1,
  cmsRichTextStyleMap: !1,
  cooperTemplateData: !1,
  hubFileAttribution: !1,
  rotationOrigin: !1,
  vectorOperationVersion: !1,
  objectAnimations: !1,
  textPathStart: !1,
  strokeBrushGuid: !1,
  strokeSeed: !1,
  variableWidthPoints: !1,
  dynamicStrokeSettings: !1,
  scatterStrokeSettings: !1,
  stretchStrokeSettings: !1,
  brushType: !1,
  annotationCategories: !1,
  managedStringData: !1,
  transformModifiers: !0,
  isPrimaryBreakpoint: !1,
  codeSnapshot: !1,
  codeSnapshotState: !1,
  codeSnapshotInvalidatedAt: !1,
  multiEditGlueId: !1,
  isSlot: !1,
  isSlotContent: !1,
  isCodeBehavior: !1,
  thumbnailInfo: !1,
  autoForkCode: !1,
  hasBeenManuallyRenamed: !1,
  codeCreatedFromDesign: !1,
  codeCreatedFromDesignNodeId: !1,
  imageImports: !1,
  codeBehaviorData: !1,
  isMainCodeComponent: !1,
  scatterBrushTransforms: !1,
  jsxProps: !1,
  aiCanvasPrompt: !1,
  isEntrypointCodeFile: !1,
  backingNodeId: !1,
  componentOrStateGroupKey: !1,
  componentOrStateGroupVersion: !1,
}
let styleIdMapping = new Map(Object.entries({
  styleIdForText: ['fontName', 'fontSize', 'textCase', 'textDecoration', 'textDecorationFillPaints', 'letterSpacing', 'fontVariations', 'fontVariantCommonLigatures', 'fontVariantContextualLigatures', 'fontVariantDiscretionaryLigatures', 'fontVariantHistoricalLigatures', 'fontVariantOrdinal', 'fontVariantSlashedZero', 'fontVariantNumericFigure', 'fontVariantNumericSpacing', 'fontVariantNumericFraction', 'fontVariantCaps', 'fontVariantPosition'],
  styleIdForFill: ['fillPaints'],
  styleIdForStrokeFill: ['strokePaints'],
  styleIdForEffect: ['effects'],
}))
let visualAttributes2 = {
  derivedTextData: !1,
  name: !1,
  visible: !0,
  locked: !1,
  lockMode: !1,
  parentIndex: !1,
  transform: !0,
  description: !1,
  symbolDescription: !1,
  symbolLinks: !1,
  type: !1,
  booleanOperation: !1,
  horizontalConstraint: !0,
  verticalConstraint: !0,
  hyperlink: !0,
  mention: !1,
  proportionsConstrained: !1,
  targetAspectRatio: !0,
  inheritGridStyleID: !1,
  layoutGrids: !1,
  inheritTextStyleID: !1,
  inheritFillStyleID: !1,
  inheritFillStyleIDForStroke: !1,
  inheritEffectStyleID: !1,
  inheritExportStyleID: !1,
  inheritStrokeStyleID: !1,
  styleIdForFill: !0,
  styleIdForStrokeFill: !0,
  styleIdForText: !0,
  styleIdForEffect: !0,
  styleIdForGrid: !0,
  scrollBehavior: !1,
  transitionType: !1,
  transitionDuration: !1,
  easingType: !1,
  scrollDirection: !1,
  transitionPreserveScroll: !1,
  connectionType: !1,
  interactionType: !1,
  transitionTimeout: !1,
  interactionMaintained: !1,
  interactionDuration: !1,
  overlayPositionType: !1,
  transitionShouldSmartAnimate: !1,
  overlayRelativePosition: !1,
  overlayBackgroundInteraction: !1,
  overlayBackgroundAppearance: !1,
  keyTrigger: !1,
  prototypeInteractions: !1,
  prototypeStartNodeID: !1,
  prototypeStartingPoint: !1,
  videoPlayback: !1,
  stackMode: !0,
  stackSpacing: !0,
  stackCounterSizing: !0,
  stackPrimarySizing: !0,
  stackChildPrimaryGrow: !0,
  stackChildAlignSelf: !0,
  stackPrimaryAlignItems: !0,
  stackCounterAlignItems: !0,
  stackHorizontalPadding: !0,
  stackVerticalPadding: !0,
  stackPaddingRight: !0,
  stackPaddingBottom: !0,
  stackPositioning: !0,
  stackReverseZIndex: !0,
  bordersTakeSpace: !0,
  stackWrap: !0,
  stackCounterSpacing: !0,
  stackCounterAlignContent: !0,
  gridRows: !1,
  gridColumns: !1,
  gridRowGap: !1,
  gridColumnGap: !1,
  gridRowAnchor: !1,
  gridColumnAnchor: !1,
  gridRowSpan: !1,
  gridColumnSpan: !1,
  gridRowsSizing: !1,
  gridColumnsSizing: !1,
  gridChildHorizontalAlign: !1,
  gridChildVerticalAlign: !1,
  minSize: !0,
  maxSize: !0,
  maxLines: !0,
  pluginData: !1,
  pluginRelaunchData: !1,
  stackPadding: !1,
  stackJustify: !1,
  codeBlockLanguage: !1,
  codeBlockTheme: !1,
  fontVariations: !0,
  detachOpticalSizeFromFontSize: !1,
  widgetMetadata: !1,
  widgetPropertyMenuItems: !1,
  widgetSyncedState: !1,
  renderedSyncedState: !1,
  widgetEvents: !1,
  widgetInputBehavior: !1,
  widgetCachedAncestor: !1,
  widgetInputTextNodeType: !1,
  interactiveSlideConfigData: !1,
  interactiveSlideParticipantData: !1,
  flappType: !1,
  isEmbeddedPrototype: !1,
  themeID: !1,
  slideThemeMap: !1,
  slideTemplateFileKey: !1,
  slideNumber: !1,
  slideNumberSeparator: !1,
  componentPropDefs: !1,
  componentPropRefs: !1,
  componentPropAssignments: !1,
  simplifyInstancePanels: !1,
  propsAreBubbled: !1,
  size: !0,
  guid: !1,
  phase: !1,
  opacity: !0,
  blendMode: !0,
  count: !0,
  dashPattern: !0,
  autoRename: !1,
  backgroundEnabled: !1,
  mask: !0,
  maskType: !0,
  exportContentsOnly: !1,
  maskIsOutline: !1,
  backgroundOpacity: !1,
  cornerRadius: !1,
  fontSize: !0,
  paragraphIndent: !0,
  paragraphSpacing: !0,
  listSpacing: !0,
  starInnerScale: !0,
  miterLimit: !0,
  strokeWeight: !0,
  textTracking: !0,
  strokeAlign: !0,
  strokeCap: !0,
  strokeCapSize: !0,
  strokeJoin: !0,
  textAlignHorizontal: !0,
  textAlignVertical: !0,
  textCase: !0,
  textDecoration: !0,
  textDecorationStyle: !0,
  textDecorationSkipInk: !0,
  textUnderlineOffset: !0,
  textDecorationThickness: !0,
  leadingTrim: !0,
  hangingPunctuation: !1,
  hangingList: !1,
  fillPaints: !0,
  strokePaints: !0,
  textDecorationFillPaints: !0,
  lineHeight: !0,
  fontName: !0,
  textData: !0,
  effects: !0,
  handleMirroring: !1,
  exportSettings: !1,
  textAutoResize: !1,
  vectorData: !0,
  styleID: !1,
  backgroundColor: !1,
  fillGeometry: !1,
  strokeGeometry: !1,
  guidPath: !1,
  symbolData: !1,
  frameMaskDisabled: !1,
  resizeToFit: !0,
  exportBackgroundDisabled: !1,
  sharedSymbolReference: !1,
  isSymbolPublishable: !1,
  sharedSymbolMappings: !1,
  derivedSymbolData: !1,
  sharedSymbolVersion: !1,
  overrideLevel: !1,
  nestedInstanceResizeEnabled: !1,
  fontVariantCommonLigatures: !0,
  fontVariantContextualLigatures: !0,
  fontVariantDiscretionaryLigatures: !0,
  fontVariantHistoricalLigatures: !0,
  fontVariantOrdinal: !0,
  fontVariantSlashedZero: !0,
  fontVariantNumericFigure: !0,
  fontVariantNumericSpacing: !0,
  fontVariantNumericFraction: !0,
  fontVariantCaps: !0,
  fontVariantPosition: !0,
  guides: !1,
  transitionNodeID: !1,
  prototypeBackgroundColor: !1,
  internalOnly: !1,
  overriddenSymbolID: !1,
  rectangleTopLeftCornerRadius: !0,
  rectangleTopRightCornerRadius: !0,
  rectangleBottomLeftCornerRadius: !0,
  rectangleBottomRightCornerRadius: !0,
  rectangleCornerRadiiIndependent: !1,
  rectangleCornerToolIndependent: !1,
  sharedComponentMasterData: !1,
  cornerSmoothing: !0,
  styleType: !1,
  styleDescription: !1,
  unflatteningMappings: !1,
  letterSpacing: !0,
  version: !1,
  userFacingVersion: !1,
  sharedStyleMasterData: !1,
  sharedStyleReference: !1,
  sortPosition: !1,
  isPublishable: !1,
  exportTextAsSVGText: !1,
  isSoftDeletedStyle: !1,
  isSoftDeleted: !1,
  isNonUpdateable: !1,
  isOverrideOverTextStyle: !1,
  connectionURL: !1,
  prototypeDevice: !1,
  backgroundPaints: !1,
  arcData: !1,
  derivedSymbolDataLayoutVersion: !1,
  navigationType: !1,
  fontVersion: !1,
  textUserLayoutVersion: !1,
  textExplicitLayoutVersion: !1,
  textBidiVersion: !1,
  toggledOnOTFeatures: !1,
  toggledOffOTFeatures: !1,
  overrideKey: !1,
  publishFile: !1,
  sourceLibraryKey: !1,
  publishID: !1,
  key: !1,
  componentKey: !1,
  isC2: !1,
  fileAssetIds: !1,
  publishedVersion: !1,
  containerSupportsFillStrokeAndCorners: !1,
  isStateGroup: !1,
  voiceEventPhrase: !1,
  forceUnflatteningMappings: !1,
  ancestorPathBeforeDeletion: !1,
  stateGroupPropertyValueOrders: !1,
  variantPropSpecs: !1,
  nodeGenerationData: !0,
  derivedImmutableFrameData: !1,
  derivedImmutableFrameDataVersion: !1,
  jsxData: !1,
  derivedJsxData: !1,
  stableKey: !1,
  shapeWithTextType: !0,
  connectorStart: !1,
  connectorEnd: !1,
  connectorLineStyle: !1,
  connectorStartCap: !1,
  connectorEndCap: !1,
  connectorType: !1,
  shapeUserHeight: !0,
  overrideStash: !1,
  internalEnumForTest: !1,
  internalDataForTest: !1,
  connectorControlPoints: !1,
  connectorBezierControlPoints: !1,
  connectorTextMidpoint: !1,
  annotations: !1,
  measurements: !1,
  libraryMoveInfo: !1,
  libraryMoveHistory: !1,
  developerRelatedLinks: !1,
  stampData: !1,
  embedData: !0,
  linkPreviewData: !0,
  richMediaData: !0,
  textTruncation: !0,
  shapeTruncates: !0,
  sectionContentsHidden: !0,
  widgetTooltip: !1,
  borderTopWeight: !0,
  borderBottomWeight: !0,
  borderLeftWeight: !0,
  borderRightWeight: !0,
  borderStrokeWeightsIndependent: !1,
  widgetHoverStyle: !1,
  hasHadRTLText: !1,
  emojiImageSet: !1,
  slideThumbnailHash: !1,
  isWidgetStickable: !1,
  shouldHideCursorsOnWidgetHover: !1,
  variableDataValues: !1,
  variableConsumptionMap: !0,
  parameterConsumptionMap: !0,
  variableModeBySetMap: !1,
  variableSetModes: !1,
  variableSetID: !1,
  backingVariableSetId: !1,
  overriddenVariableId: !1,
  rootVariableKey: !1,
  isCollectionExtendable: !1,
  variableResolvedType: !1,
  variableScopes: !1,
  codeSyntax: !0,
  agendaPositionMap: !1,
  agendaMetadataMap: !1,
  migrationStatus: !1,
  editInfo: !1,
  documentColorProfile: !1,
  accessibleHTMLTag: !1,
  ariaAttributes: !1,
  accessibleLabel: !1,
  isDecorativeImage: !1,
  tableRowPositions: !1,
  tableColumnPositions: !1,
  tableRowHeights: !1,
  tableColumnWidths: !1,
  areSlidesManuallyIndented: !1,
  detachedSymbolId: !1,
  childReadingDirection: !1,
  readingIndex: !1,
  sectionStatusInfo: !1,
  handoffStatusMap: !1,
  slideActiveThemeLibKey: !1,
  slideSpeakerNotes: !1,
  isSkippedSlide: !1,
  diagramLayoutRuleType: !1,
  diagramParentIndex: !1,
  diagramLayoutPaused: !1,
  editScopeInfo: !1,
  sectionPresetInfo: !1,
  platformShapeDefinition: !1,
  semanticWeight: !1,
  semanticItalic: !1,
  isPageDivider: !1,
  moduleType: !1,
  pageType: !1,
  derivedBreakpointData: !1,
  breakpointMinWidth: !1,
  defaultResponsiveSetId: !0,
  responsiveSetSettings: !1,
  behaviors: !1,
  aiEditedNodeChangeFieldNumbers: !1,
  aiEditScopeLabel: !1,
  sortedMovingChildIndices: !1,
  firstDraftData: !1,
  firstDraftKitElementData: !1,
  sourceCode: !1,
  collaborativeSourceCode: !1,
  belongsToCodeLibraryId: !1,
  exportedFromCodeFileId: !1,
  backingCodeComponentId: !1,
  codeFilePath: !1,
  codeFileCanvasNodeId: !1,
  importedCodeFiles: !1,
  codeExportName: !1,
  chatMessages: !1,
  chatCompressionState: !1,
  codeChatMessagesKey: !1,
  aiChatThread: !1,
  responsiveTextStyleVariants: !1,
  cmsSelector: !1,
  cmsConsumptionMap: !1,
  cmsRichTextStyleMap: !1,
  cooperTemplateData: !1,
  hubFileAttribution: !1,
  rotationOrigin: !1,
  vectorOperationVersion: !1,
  objectAnimations: !1,
  textPathStart: !1,
  strokeBrushGuid: !1,
  strokeSeed: !1,
  variableWidthPoints: !1,
  dynamicStrokeSettings: !1,
  scatterStrokeSettings: !1,
  stretchStrokeSettings: !1,
  brushType: !1,
  annotationCategories: !1,
  managedStringData: !1,
  transformModifiers: !1,
  isPrimaryBreakpoint: !1,
  codeSnapshot: !1,
  codeSnapshotState: !1,
  codeSnapshotInvalidatedAt: !1,
  multiEditGlueId: !1,
  isSlot: !1,
  isSlotContent: !1,
  isCodeBehavior: !1,
  thumbnailInfo: !1,
  autoForkCode: !1,
  hasBeenManuallyRenamed: !1,
  codeCreatedFromDesign: !1,
  codeCreatedFromDesignNodeId: !1,
  imageImports: !1,
  codeBehaviorData: !1,
  isMainCodeComponent: !1,
  scatterBrushTransforms: !1,
  jsxProps: !1,
  aiCanvasPrompt: !1,
  isEntrypointCodeFile: !1,
  backingNodeId: !1,
  componentOrStateGroupKey: !1,
  componentOrStateGroupVersion: !1,
}
let activeVisualAttributes = Object.keys(visualAttributes2).filter(e => visualAttributes2[e])

enum ProjectDevelopmentPhases {
  LEGO = 0,
  BRANCHING = 1,
  COMPARE_CHANGES = 2,
  TEST_SUITE = 3,
  LINTER = 4,
}
/**
 * Converts a string to lowercase and replaces underscores with spaces.
 * Original name: $$p11
 * @param value - The string to format.
 * @returns The formatted string.
 */
export function formatRenderName(value: string): string {
  return value.toLowerCase().replace('_', ' ')
}

/**
 * Creates a render treatment object for a single property.
 * Original name: $$m9
 * @param renderName - The name to render.
 * @param oldValue - The old value.
 * @param newValue - The new value.
 * @returns The treatment object.
 */
export function createSinglePropertyRenderTreatment(renderName: string, oldValue: string | (() => any), newValue: string | (() => any)) {
  return {
    treatmentType: RenderStrategy.RENDER_SINGLE_PROPERTY,
    renderName,
    renderOldValue: typeof oldValue === 'string' ? () => formatRenderName(oldValue) : oldValue,
    renderNewValue: typeof newValue === 'string' ? () => formatRenderName(newValue) : newValue,
  }
}

/**
 * Creates a render treatment object for multiple nodes.
 * Original name: $$h1
 * @param renderName - The name to render.
 * @param oldValue - The old value.
 * @param newValue - The new value.
 * @returns The treatment object.
 */
export function createMultiNodeRenderTreatment(renderName: string, oldValue: string | (() => any), newValue: string | (() => any)) {
  return {
    identifier: generateUUIDv4(),
    treatmentType: RenderStrategy.RENDER_MULTI_NODE,
    renderName,
    renderOldValue: typeof oldValue === 'string' ? () => oldValue : oldValue,
    renderNewValue: typeof newValue === 'string' ? () => newValue : newValue,
  }
}

/**
 * Creates a render treatment object for multiple properties.
 * Original name: $$g6
 * @param renderName - The name to render.
 * @param oldValue - The old value.
 * @param newValue - The new value.
 * @returns The treatment object.
 */
export function createMultiPropertyRenderTreatment(renderName: string, oldValue: string | (() => any), newValue: string | (() => any)) {
  return {
    identifier: generateUUIDv4(),
    treatmentType: RenderStrategy.RENDER_MULTI_PROPERTY,
    renderName,
    renderOldValue: typeof oldValue === 'string' ? () => oldValue : oldValue,
    renderNewValue: typeof newValue === 'string' ? () => newValue : newValue,
  }
}

/**
 * Creates a render treatment object for display node single property.
 * Original name: $$f8
 * @param renderName - The name to render.
 * @param oldValue - The old value.
 * @param newValue - The new value.
 * @returns The treatment object.
 */
export function createDisplayNodeSinglePropertyRenderTreatment(renderName: string, oldValue: string | (() => any), newValue: string | (() => any)) {
  return {
    treatmentType: RenderStrategy.RENDER_DISPLAY_NODE_SINGLE_PROPERTY,
    renderName,
    renderOldValue: typeof oldValue === 'string' ? () => oldValue : oldValue,
    renderNewValue: typeof newValue === 'string' ? () => newValue : newValue,
  }
}
export const AW = styleIdMapping
export const EY = createMultiNodeRenderTreatment
export const FO = ProjectDevelopmentPhases
export const Rv = RenderStrategy
export const b2 = visualAttributes
export const cs = activeVisualAttributes
export const de = createMultiPropertyRenderTreatment
export const fE = ReviewPhase
export const oZ = createDisplayNodeSinglePropertyRenderTreatment
export const wR = createSinglePropertyRenderTreatment
export const yC = visualAttributes2
export const zX = formatRenderName
