import { A } from "../905/268204";
let r = A ? navigator.userAgent : "";
let $$a2 = !!A && (navigator.webdriver ?? !1);
let $$s1 = /macintosh/i.test(r);
let o = /ipad|iphone|ipod/.test(r);
let $$l0 = $$s1 || o;
let $$d4 = /android/i.test(r);
let c = /firefox|iceweasel|fxios/i.test(r);
let u = !c && /chrome|crios|crmo/i.test(r);
let $$p3 = $$l0 && !c && !u && /safari|applewebkit/i.test(r);
export const Bt = $$l0;
export const Md = $$s1;
export const Uo = $$a2;
export const VM = $$p3;
export const yA = $$d4;