var $$n3;
var $$r6;
var $$a2;
var $$s1;
var $$o0;
var $$l4;
var $$d5;
var $$c7;
(function (e) {
  e.Appear = "appear";
  e.Hover = "hover";
  e.Press = "press";
  e.Focus = "focus";
  e.ScrollParallax = "scrollParallax";
  e.ScrollTransform = "scrollTransform";
  e.Cursor = "cursor";
  e.Marquee = "marquee";
  e.Code = "code";
})($$n3 || ($$n3 = {}));
(function (e) {
  e.IN_CUBIC = "IN_CUBIC";
  e.OUT_CUBIC = "OUT_CUBIC";
  e.INOUT_CUBIC = "INOUT_CUBIC";
  e.LINEAR = "LINEAR";
  e.IN_BACK_CUBIC = "IN_BACK_CUBIC";
  e.OUT_BACK_CUBIC = "OUT_BACK_CUBIC";
  e.INOUT_BACK_CUBIC = "INOUT_BACK_CUBIC";
  e.CUSTOM_CUBIC = "CUSTOM_CUBIC";
  e.GENTLE_SPRING = "GENTLE_SPRING";
  e.SPRING_PRESET_ONE = "SPRING_PRESET_ONE";
  e.SPRING_PRESET_TWO = "SPRING_PRESET_TWO";
  e.SPRING_PRESET_THREE = "SPRING_PRESET_THREE";
  e.CUSTOM_SPRING = "CUSTOM_SPRING";
  e.SPRING = "SPRING";
})($$r6 || ($$r6 = {}));
(function (e) {
  e.PASS_THROUGH = "PASS_THROUGH";
  e.NORMAL = "NORMAL";
  e.DARKEN = "DARKEN";
  e.MULTIPLY = "MULTIPLY";
  e.LINEAR_BURN = "LINEAR_BURN";
  e.COLOR_BURN = "COLOR_BURN";
  e.LIGHTEN = "LIGHTEN";
  e.SCREEN = "SCREEN";
  e.LINEAR_DODGE = "LINEAR_DODGE";
  e.COLOR_DODGE = "COLOR_DODGE";
  e.OVERLAY = "OVERLAY";
  e.SOFT_LIGHT = "SOFT_LIGHT";
  e.HARD_LIGHT = "HARD_LIGHT";
  e.DIFFERENCE = "DIFFERENCE";
  e.EXCLUSION = "EXCLUSION";
  e.HUE = "HUE";
  e.SATURATION = "SATURATION";
  e.COLOR = "COLOR";
  e.LUMINOSITY = "LUMINOSITY";
})($$a2 || ($$a2 = {}));
(function (e) {
  e.LEFT = "LEFT";
  e.RIGHT = "RIGHT";
  e.CENTER = "CENTER";
  e.LEFT_RIGHT = "LEFT_RIGHT";
  e.SCALE = "SCALE";
})($$s1 || ($$s1 = {}));
(function (e) {
  e.TOP = "TOP";
  e.BOTTOM = "BOTTOM";
  e.CENTER = "CENTER";
  e.TOP_BOTTOM = "TOP_BOTTOM";
  e.SCALE = "SCALE";
})($$o0 || ($$o0 = {}));
(function (e) {
  e.SUPER = "SUPER";
  e.SUB = "SUB";
  e.NORMAL = "NORMAL";
})($$l4 || ($$l4 = {}));
(function (e) {
  e.NONE = "NONE";
  e.STRIKETHROUGH = "STRIKETHROUGH";
  e.UNDERLINE = "UNDERLINE";
})($$d5 || ($$d5 = {}));
(function (e) {
  e.ORDERED = "ORDERED";
  e.UNORDERED = "UNORDERED";
  e.NONE = "NONE";
})($$c7 || ($$c7 = {}));
export const Gx = $$o0;
export const M9 = $$s1;
export const Nx = $$a2;
export const Xc = $$n3;
export const eT = $$l4;
export const i8 = $$d5;
export const mg = $$r6;
export const wj = $$c7;