export let $$n0 = {
  id: ["nodeId"],
  guid: [],
  parentGuid: ["parent", "parentId"],
  type: ["nodeType"],
  field: ["property"],
  phase: [],
  overrideKey: ["okey"],
  backingSymbolId: ["symbol", "symbolId"],
  consumedStyleIds: ["consumedStyleId", "consumedStyle", "consumedStyles"],
  name: [],
  text: [],
  key: [],
  version: ["assetVersion", "sharedSymbolVersion"],
  publishId: [],
  imageHashes: [],
  symbolId: ["symbol"],
  stateGroupId: ["stateGroup"],
  styleId: ["style"],
  variableId: ["variable"],
  variableOverrideId: ["variableOverride"],
  variableCollectionId: ["variableSetId", "collectionId", "variableCollection", "variableSet"],
  codeComponentId: ["codeComponent"],
  codeFileId: ["codeFile", "exportedFromCodeFileId"],
  codeLibraryId: ["codeLibrary", "belongsToCodeLibraryId"],
  editScopeLabel: ["editScope"],
  startSequenceNumber: ["start", "startSequence"],
  endSequenceNumber: ["end", "endSequence"],
  userId: ["user"],
  createdAt: ["created", "date", "time"]
};
export const L = $$n0;