import { atom, t_ } from "../figma_app/27355";
import { ProductAccessTypeEnum } from "../905/513035";
import { N_ } from "../905/332483";
import { qG } from "../figma_app/545877";
let $$o8 = atom([]);
let $$l21 = atom(void 0);
let $$d27 = atom(e => {
  let t = e($$o8);
  return 0 !== t.length && e($$l21) === t[t.length - 1];
});
let $$c25 = atom("default");
let $$u16 = atom(!1);
let $$p7 = atom("");
let $$m24 = atom(!1);
let $$h0 = atom(["", "", ""]);
let $$g33 = ["sneha@example.com", "oscar@example.com ", "molly@example.com", "shiva@example.com", "elynn@example.com", "dian@example.com", "linda@example.com"];
let $$f15 = $$g33.map(e => e.split("@")[0]);
let $$_28 = atom(!1);
export var $$A11 = (e => (e.STARTER = "starter", e.PROFESSIONAL = "professional", e.ORG = "org", e))($$A11 || {});
let $$y19 = atom("");
let $$b31 = atom("");
let $$v17 = atom(new Set());
let $$I9 = atom(void 0);
let $$E22 = atom("");
let $$x29 = atom(new Set());
let $$S26 = atom(e => e($$v17).has("student") || e($$v17).has("educator") || e($$R6).has("school"));
let $$w30 = atom(e => e($$v17).has("student"));
let $$C5 = atom(new Set());
let $$T13 = atom(new Set());
let $$k20 = atom(new Set());
let $$R6 = atom(new Set());
let $$N32 = atom(new Set());
let $$P12 = atom(new Set());
let $$O10 = atom(e => {
  let t = e($$T13);
  let i = e($$k20);
  return t.has("yes_many_times") || i.has("yes_many_times") ? "yes_many_times" : t.has("yes_a_few_times") || i.has("yes_a_few_times") ? "yes_a_few_times" : t.has("no_first_time") || i.has("no_first_time") ? "no_first_time" : void 0;
});
let $$D14 = atom(void 0);
let $$L18 = atom(!1);
let $$F3 = atom(N_.dict(e => !1));
let $$M4 = atom(e => {
  let t = e($$j23);
  return !!t && !!N_.has(t) && (e($$F3)[t] || !1);
});
let $$j23 = atom(null);
let $$U2 = atom(e => e($$j23) === ProductAccessTypeEnum.DEVELOPER);
let $$B1 = t_(e => !!e(qG).data?.opted_in_email);
export const $l = $$h0;
export const BG = $$B1;
export const FP = $$U2;
export const JA = $$F3;
export const JC = $$M4;
export const Nz = $$C5;
export const PG = $$R6;
export const Q7 = $$p7;
export const S0 = $$o8;
export const SL = $$I9;
export const T$ = $$O10;
export const VN = $$A11;
export const VQ = $$P12;
export const X9 = $$T13;
export const Xw = $$D14;
export const YH = $$f15;
export const YX = $$u16;
export const ZE = $$v17;
export const _D = $$L18;
export const aV = $$y19;
export const bT = $$k20;
export const bk = $$l21;
export const eL = $$E22;
export const fj = $$j23;
export const kd = $$m24;
export const ni = $$c25;
export const nt = $$S26;
export const pC = $$d27;
export const pr = $$_28;
export const qV = $$x29;
export const r3 = $$w30;
export const uN = $$b31;
export const xO = $$N32;
export const xo = $$g33;