import { createMapperFactory, processAdditionalConfig } from "../905/508958";
export let $$a0 = createMapperFactory()(e => ({
  id: e.camel(),
  name: e.camel().custom({
    toLiveGraph: e => e,
    toSinatra: e => e || ""
  }),
  handle: e.camel(),
  img_url: e.camel(),
  email: e.camel().custom({
    toLiveGraph: e => e,
    toSinatra: e => e || ""
  }),
  description: e.camel(),
  org_id: e.drop(),
  appData: e.drop(),
  auto_open_in_desktop: e.drop(),
  backup_codes: e.drop(),
  can_sell_on_community: e.drop(),
  cmty_buyer_tos_accepted_at: e.drop(),
  cmty_seller_capabilities: e.drop(),
  color_profile: e.drop(),
  community_beta_at: e.drop(),
  community_blocked_at: e.drop(),
  community_commenting_blocked_at: e.drop(),
  community_profile_handle: e.drop(),
  community_profile_id: e.drop(),
  community_purchasing_blocked_at: e.drop(),
  created_at: e.drop(),
  delete_user_loading: e.drop(),
  dev_tokens: e.drop(),
  drafts_folder_id: e.drop(),
  email_validated_at: e.drop(),
  experiment_assignments: e.drop(),
  external_restricted_org_id: e.drop(),
  google_sso_only: e.drop(),
  has_content_from_other_plans: e.drop(),
  has_passed_visual_compliance: e.drop(),
  hub_file_publishing_blocked_at: e.drop(),
  job_title: e.drop(),
  job_title_source: e.drop(),
  keyboard_layout: e.drop(),
  locale: e.drop(),
  mfa_setup_token: e.drop(),
  mouse_scroll_to_zoom: e.drop(),
  oauth_tokens: e.drop(),
  password_token: e.drop(),
  personal_drafts_folder_id: e.drop(),
  phone_number: e.drop(),
  phone_token: e.drop(),
  plans: e.drop(),
  plugin_publishing_blocked_at: e.drop(),
  profile: e.drop(),
  realtime_token: e.drop(),
  realtime_token_inactive: e.drop(),
  right_click_drag_to_pan: e.drop(),
  saml_sso_only: e.drop(),
  screenreader_enabled: e.drop(),
  sharing_restricted: e.drop(),
  signup_locale: e.drop(),
  stripe_account_status: e.drop(),
  student_validated_at: e.drop(),
  temp_phone: e.drop(),
  track_tags: e.drop(),
  two_factor_app_enabled: e.drop(),
  two_factor_secret_loaded: e.drop(),
  unsubscribed_at: e.drop(),
  usage_purpose: e.drop(),
  utc_offset: e.drop()
}));
processAdditionalConfig((e, n, t) => [e()($$a0), n($$a0)(), t($$a0)()]);
processAdditionalConfig((e, n, t) => [e()($$a0), n($$a0)(), t($$a0)()]);
export const W = $$a0;